### ISSUE TITLE
MacOS: “velociraptor-v0.5.8-darwin-amd64” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by GelosSnake** [Velocidex/velociraptor#1017]
![image](https://user-images.githubusercontent.com/5004714/114509446-2ce45900-9c3e-11eb-8e50-0dd36b974127.png)

Seems like the fact velociraptor is not verified is causing MacOS to prevent execution.

Familiar with it?

**Comment by scudette** [comment]
This is a common issue with newer macos that they can not run un notarized apps.

Here is an example with other software too https://github.com/hashicorp/terraform/issues/23033

We probably need to look into creating a notarized version as well but until then there are some options.

The simplest way is to just download the binary using curl or wget instead of a browser. Otherwise you can remove the quarantine attribute as described in the above issue, or whitelist the binary in system settings.

**Comment by GelosSnake** [comment]
FYI it was fixed by going to security in system settings and click "allow".
![Uploading image.png…]()

**Comment by scudette** [comment]
For larger scale one needs to deploy an TCC policy via MDM.

**Comment by scudette** [comment]
Closing until we find a better solution for this - I suspect it might involve some kind of Apple signing thing.
