### ISSUE TITLE
Notebook - Order by Timestamp in Userassist returns no results

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#1034]
In a Notebook for userassist, if you order by LastExecutionTS, which is a unix timestamp, it returns "no results"
There are definitely results
![image](https://user-images.githubusercontent.com/1241363/115942250-a3117700-a4ec-11eb-9337-19a9ce80a41c.png)

![image](https://user-images.githubusercontent.com/1241363/115942262-b7557400-a4ec-11eb-8158-4d212fc79d90.png)

This does not occur if i predefine a filter on the LastExecution column to show me only 2021 for ex. So i think it's because some items have no timestamp, and it breaks and shows no results.

**Comment by scudette** [comment]
Yeah I think you are quite right! The NULLs are kind of confusing it because NULL compared to anything (event with > or < ) will return false.

This is a valid workaround but maybe we need to look at a proper fix

![Windows](https://user-images.githubusercontent.com/3856546/115947689-a87eb980-a50c-11eb-9d89-d85e01ff1b92.png)

**Comment by randomaccess3** [comment]
Yeah that's what I ended up doing, but took me a minute to figure out that was the cause of the dramas.

**Comment by scudette** [comment]
Should be fixed in 0.5.9-rc1
