### ISSUE TITLE
Schedule File Finder Hunt

### ISSUE THREAD

**Issue by P4T12ICK** [Velocidex/velociraptor#1053]
Is it possible to schedule a file finder hunt and only download the new/changed files to the previous execution?

**Comment by scudette** [comment]
What is it that you are trying to achieve? 

A lot of the time when people want to schedule hunts repeatedly they actually need a client side event monitoring query. 

For example, say you want to hash all the files in `C:\Users\*\Downloads` every hour but only want to see the hashes for new files that just got added, then it is easier to just write a client monitoring query for that (check every 60 seconds instead)

```sql

SELECT FullPath, hash(path=FullPath) AS Hash 
FROM diff(key="FullPath", period=60, query={
        SELECT FullPath FROM glob(globs="C:/Users/*/Downloads/*")
}) WHERE Diff =~ "added"

```

Then the client will automatically push new hashes for new files that appeared checking every say 60 seconds. This then also happens then the client is offline and gets synced later. This is actually way better than a periodic hunt and requires a lot less maintenance because it just runs by itself.

![Test2](https://user-images.githubusercontent.com/3856546/117095201-13e84700-ada9-11eb-9f0e-f9e4fa4f79ec.png)

![Test2](https://user-images.githubusercontent.com/3856546/117095228-26fb1700-ada9-11eb-86f6-f74968ee5532.png)

![Test2](https://user-images.githubusercontent.com/3856546/117095175-fdda8680-ada8-11eb-90e5-b414048bed89.png)

**Comment by scudette** [comment]
I will close this, please reopen if you have more questions. You can also use Server.Monitoring.ScheduleHunt as a template
