### ISSUE TITLE
Windows.KapeFiles.Targets does not extract $SECURE:$SDS

### ISSUE THREAD

**Issue by hunt3vil** [Velocidex/velociraptor#1142]
Windows.KapeFiles.Targets does not extract $SECURE:$SDS currently. I have traced the issue to the the Windows.Collectors.File artifact where there is a "IsDir" check before returning the file path from the glob operation. Without the "IsDir" check the glob returns the correct filepath.

Since $SECURE works like a directory from an NTFS point of view, this NTFS meta file is not extracted. This would also happen if we were to try to download: $Extend\\$ObjId, $Extend\\$Quota or $Extend\\$Reparse.

```
LET hits = SELECT FullPath AS SourceFile, Size,
       Ctime AS Created,
       Mtime AS Modified,
       Atime AS LastAccessed
FROM glob(globs=specs.Glob, accessor=Accessor)
WHERE NOT IsDir AND log(message="Found " + SourceFile)
```

**Comment by scudette** [comment]
It is better to upload that special file directly rather than make glob work on it - as you point out glob assumes an mft entry is either a file or a directory but can not be both. This specific file breaks that assumption.

You can collect that file using an artifact like this:
```yaml
name: Custom.Upload.SDS

sources:
  - precondition:
      SELECT OS From info() where OS = 'windows' 

    query: |
      LET Filename = "c:/$SECURE:$SDS"

      SELECT parse_ntfs(device=Filename, inode=Data.mft) AS MFTEntry,
             upload(accessor="mft", file="C:/" + Data.mft) AS Upload
      FROM stat(accessor="ntfs", filename=Filename)
```

It works by using the "mft" accessor to pull out just the specific MFT stream we care about (This is the $DATA stream of the mft entry). The mft notation is something like "9-128-0" so mft entry 9, type 128 ($DATA) and stream id 0.

**Comment by scudette** [comment]
I will remove this target from the kape files artifact in favor of a specific artifact to handle that
