### ISSUE TITLE
Feature request: Make config generator wizard less confusing

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#117]
For example, if a user wants to use SSO _and_ Let's Encrypt then do they need to run through the wizard twice? There's no indication as to whether multiple runs will update an existing config or replace it?

My proposal to make this less confusing is to have the wizard loop back to the initial set of options and add a Quit option. The config generator should also update the config if one is specified in the command or if one exists in the working directory with the default name.

**Comment by scudette** [comment]
You can't use Google SSO without a valid certificate since Google needs to hand off the authentication to the server and it needs to verify its certificate. So in this sense lets encrypt is the first level of security and SSO is the next level which implies lets encrypt.

Another way to configure is to set up your own certs but this is more complicated and I think the wizard should really accommodate this configuration (but users could edit the config file to make it work).

I think the wizard should be used for the most common configurations and should not offer too many options. Anything more complex than that should require manually editing the config files. We always generate new config files because it is really hard to edit existing ones in a sensible way - we would need to understand how all the options interact with one another in order to preserve the intention of the previous config. For example, say the previous config uses custom certs but this time around the user chose lets encrypt - do we only change the certs? do we also change the pinned server name? It is hard to get to a correct configuration and to figure out how to change an existing configuration.

We only ever intended the wizard to produce an initial configuration which is the starting point - the admin can tweak it from there for a real deployment. Granted we do need to document all the options a lot better and what options to set in each required setup.

WRT the quit option - sure we can add that to any screen but ctrl-c would quit at any point anyway.  Maybe we should refuse to overwrite an existing config file though - so make sure it is clear that we need to generate a new file and we are not editing an existing file?

**Comment by predictiple** [comment]
If I'm understanding correctly then would the following workflow make more sense?

- Warning if existing config file detected (quit / overwrite)
  - overwrite: Do you want to want to use Let's Encrypt? (yes / no)
    - yes: Let's Encrypt wizard and then ask Do you want to use SSO (yes / no)
      - yes: start SSO wizard and then wizard for general options
      - no: wizard for general options
    - no: start self-signed cert wizard and then wizard for general options
  - quit: exit

I agree that interpreting/validating an existing configuration is asking for trouble and would probably add to the confusion for first-time users. 

Reading what you've said about SSO and running a quick test I see that it does add the `autocert` config settings, but it would be nice if the SSO option made it clear that it is going to do that.

So perhaps the simplest option is just better wording of the options? Something like:

Option 1: Generate Self Signed SSL certificates and use Local user accounts
Option 2: Automatically provision certificates with Lets Encrypt and use Local user accounts
Option 3: Automatically provision certificates with Lets Encrypt and authenticate users with Google OAuth SSO

Admittedly that is a bit long-winded...

**Comment by predictiple** [comment]
Another improvement would be to check - or at least strongly suggest - that at least 1 GUI user needs to exist. With SSO it's not intuitive that one still needs to specify authorised users. Maybe at the start of asking for users it could briefly list the already-existing users?

**Comment by scudette** [comment]
Yes this flow looks good.

The issue with the user names is that the config file is typically generated on a different machine than the final deployment. For example we would make a config file,then use the config to make a deb then copy the deb to the cloud instance.

The user creds are stored in the the filestore - so on the final server once it is configured. So this question makes sense when the user configures and installs on the local machine but it wont do anything otherwise.

Maybe we need some extra users in the config file which initialize the users in the file store the first time the server runs.

**Comment by predictiple** [comment]
> The issue with the user names is that the config file is typically generated on a different machine than the final deployment. For example we would make a config file,then use the config to make a deb then copy the deb to the cloud instance.
> 
> The user creds are stored in the the filestore - so on the final server once it is configured. So this question makes sense when the user configures and installs on the local machine but it wont do anything otherwise.

I think this is indicating that "user add" should really not be part of the generate config wizard. It could be replaced by a message at the end that says: "before starting your server instance please remember to create/authorise users with velociraptor.exe user add <username>"

> Maybe we need some extra users in the config file which initialize the users in the file store the first time the server runs.

nah, the fact the VR has no "default admin user", and doesn't allow for the creation of a default user is a security benefit. VR should perhaps log a warning if it is started in server mode and doesn't find any users.

**Comment by scudette** [comment]
But when deploying there is really no place to indicate that a user is missing. I can see this could cause confusion. The steps are:
1. Create config fles
2. Make server and client deb
3. Spin AWS instance then scp deb to it
4. SSH and install deb
5. Go to web browser

Adding a user manually means getting an ssh shell between step 4 and 5. It might not even be possible if you use orchestration like puppet to get an interactive shell.

I dont see a problem in setting a password in the config file - after all the config file contains all the crypto keys as well. Simply initialize that user account if it does not exist. The password is not default - it is set during config time and will be different each time.

**Comment by predictiple** [comment]
hmmm between step 4 and 5 I would just stop the service and add the user using the installed binary in the same SSH session, but I suppose there are rare scenarios where a preconfigured user could be a convenience. I can imagine orchestration tools being used less for the server deployment than for clients.

What I mean regarding the "security benefit" of not having default/pre-populated users is not that I think it's technically more secure, nor that it couldn't be done in a technically secure way. Rather the issue is that decades of vendors supplying default "admin" accounts (with or without default passwords) has set the example of what one should not do. If we can state in no uncertain terms that VR _never_ has pre-populated usernames then it's adds security credibility. We should preclude, as far as possible, the users ability to create insecure configurations. I can imagine that some folks will reuse the same configuration for many deployments and one day someone will accidently post their config on the internet, revealing a username that can then be brute-forced.

I still think that adding users in the config generator seems out of place, given that:

1) `user add` is available and there should ideally not be 2 ways to do the same thing in the CLI
2) the users are not actually added to the config, which is unexpected/misleading behaviour
3) the config generator allows you to add no users, which makes it seem like an optional step, leading to confusion when access then doesn't work.

The above points could be addressed by replacing the add user functionality in the config generator with an informative message like: "Suggested next steps..."

**Comment by scudette** [comment]
The wizard is somewhat more complex now because the user has to choose between mysql or file based access.  This is probably a work in progress to get a better workflow.
