### ISSUE TITLE
Downloading zip file

### ISSUE THREAD

**Issue by marianoka** [Velocidex/velociraptor#1171]
Hi!
I'm having an issue. I cannot download zip file from result after hunting. I get 404. My VR is behind an nginx running with docker inside security onion.
This is my nginx conf
![imagen](https://user-images.githubusercontent.com/9213379/127777757-7d9b318b-b86c-46d1-9f32-1fd662416ace.png)

**Comment by weslambert** [comment]
I believe this was fixed [here](https://github.com/Velocidex/velociraptor/pull/1110), and will be available in the next Velociraptor release.  I have not updated the Docker image used for Security Onion to use the CI version.

**Comment by scudette** [comment]
The fix was a bug fix for the current release which means it should be in 0.6.0-1

**Comment by weslambert** [comment]
Ah, didn't catch the `-1` release. @marianoka this is more of an issue with this Docker image at this point vs. it being available from the Velociraptor side. I'd advise closing this issue for this repo and opening one on the `weslambert/velociraptor-docker` repo if it's still an issue after pulling the latest image.

I've updated the version for the Docker image so that it is now `0.6.0-1`.

**Comment by scudette** [comment]
This should be fixed now
