### ISSUE TITLE
let's encrypt fail after upgrade

### ISSUE THREAD

**Issue by GelosSnake** [Velocidex/velociraptor#120]
Hi,

After upgrading from 0.3.0 to 0.3.5 I am getting the following error:

[INFO] 2019-10-11T16:45:01Z http: TLS handshake error from **.***.**:59738: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

Is there a way to re-generate the let's encrypt certificates after an upgrade? 

Thanks

**Comment by scudette** [comment]
You can regenerate the certs by simply removing the old ones from the cache (specified in autocert_cert_cache in the server config file). The above message suggests this is due to rolling outages and while autocert implements support for the new cert you might be able to just try again within 24 hours and it might work.

Although it seems that new issuances are not going to work at all after November (so this is real soon now!) which might mean we need to solve this issue quickly and push a new release by then.

**Comment by scudette** [comment]
https://github.com/golang/crypto/commit/0e8c3a9068a2fb325459490d2ce7baa4ffe2d00f fixes this issue - I will update to that version. You can use the latest build from the CI pipeline

**Comment by GelosSnake** [comment]
verified its working.
Amazing mate!
