### ISSUE TITLE
how-to: post-processing client events

### ISSUE THREAD

**Issue by siftuser** [Velocidex/velociraptor#1205]
I'm trying to use the new feature of `timeline` in latest rc1, can someone help as to how can I access client_events in notebook ? I want to add results of `$MFT` artifact, along with sysmon_client_events  (which I can see in `client_events` pane) in a  notebook. Thank you

**Comment by scudette** [comment]
Sorry I was meaning to write a blog post to explain this feature better (it is still experimental too :-) 

So the main concepts to understand are:
1. a super timeline is a grouping of several timelines together (you can see them on the same timeline, turn each on or off etc). So the idea is you add timelines to a super-timeline to be able to compare them together.
2. A timeline is a series of rows keyed in a time column - the rows can be anything at all, as long as a single column is specified as the time column. It is even possible (and necessary) to add the same rows multiple times each timeline having a different key column.

So the first step is to view a table in a notebook - any table generated using any query. You might collect the MFT then post process it, filter it whatever. Then once you see a table with some results in it you can add the table to super timeline.

This is an example where I just collect the MFT from the client - but the results have a lot of stuff I dont care about and it would tend to clutter the timeline, so in the collection notebook i can reduce the data a bit to only show the created time and the full path say. This gives me a table with about 380k rows

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/129855083-e90312ea-6f21-4abc-aad3-f0468d59f944.png)

Next I can add **the table** to the supertimeline by generating a timeline from it:

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/129855261-e6cb4fda-54e1-4ed0-ba95-168bf56dcdc3.png)

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/129855601-37851eea-023c-43c7-8dfe-3d7b8512248b.png)

You can see three choices - the super timeline I want to add it to, the name of the child timeline and the column to use as the time index. Right now I have not got any super timeline so I can create a new one by starting to type in the box. Later I can add other tables to the same supertimeline.

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/129856042-937ab32e-6005-4e99-9f5e-976a10811b14.png)

So this will take a little while to copy the data to the timeline (it has to sort it on the time key etc). It is probably worth filtering the total number of rows here so they are not too many - like restrict by time ranges or file types etc.

Once this is done it can be a bit underwhelming - nothing much is showing because we just added a timeline but we are not seeing it :-). So the next step is to actually see the timeline in a new cell. So now we add a cell of type timeline

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/129856614-4ac7281e-f4ff-4dec-95c6-db95794ec9e9.png)

Choose which timeline to add

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/129856667-76443bbe-632b-4d33-a12c-2bc02225d19f.png)

And we get to see the super timeline (which currently has only one timeline). It is actually a bit easier to see with full screen so I recommend to switch to that now.

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/129857190-3992fbb8-549a-43d9-9dbb-3bf86137ce57.png)

So this is what a timeline cell looks like - it is just a markdown cell with a timeline in it so you can actually add markdown to it if you want. 

On the top we see the timeline - it has a bar for each child timeline added as well as the top bar representing the visible range of the table. Below the timeline we see the table of all the events. The table has two columns, on the left is the event time on the right are all the other fields of the original table row. You can expand and contract each row to see more data and the columns here are controlled by the columns the original table is showing so you can tweak the VQL to make sure it is not too crowded here.

You can zoom the time in and out by clicking the year or month headers but I find it easier to just alt scroll the mouse. 

What is very important is to understand that the timeline named Table View represents the start and end range of the visible table. 

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/129857863-1d9dc981-27c3-487d-a1f6-03c958fe1812.png)

You can either step through the table using the regular next/previous buttons or you can click on any time you like. Things tend to get more interesting with Created0x30 around the time the system was actually running

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/129858325-60481cba-1c5c-45d6-8bc3-d74126d1834f.png)

When you add other timelines to the same super timeline you will see the events in order on the same table (they have different colors). You can turn a child timeline on or off by unticking the name on the timeline.

Hope this gets you started - I will write more docs soon. Please report any bugs and feedback.

Oh another important note - dont forget to refresh the timeline cell if you add new timelines to it so it redraw itself.

**Comment by scudette** [comment]
Just adding to that - sorry I didnt read the original question closely enough :-).

Client event monitoring are available in VQL via the `monitoring()` plugin. So here is an example of adding to the timeline above the results from Generic.Client.Info (it doesn't really make any sense to compare these two time series but this is just an example).

First get some data into a VQL cell - here I massage the columns I want. Because client events are collected continuusly you probably need to specify a start time and end time or row limit to lock into the time range you care about.

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/129861337-e6a6d0da-461d-484a-88e9-44fb5960a9ac.png)

Also here I am in the collection notebook so it already knows the client I am interested in from the notebook context. If are in a regular notebook you might want to specify a client id explicitely to the monitoring plugin.

Next I just add it to the same timeline i created before.

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/129861692-fb331dfd-dbb0-45fd-a521-6171158e6929.png)

Make sure you refresh the timeline cell itself so it can pick up the new data, and I can see the two timelines together

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/129861857-0e3b1937-fb39-4665-aa86-d6ec5894ed6a.png)

As I said it makes no sense to compare these two timelines because they are not related in any way but I hope you get the example.

**Comment by siftuser** [comment]
Thank you @scudette! Your kind help greatly appreciated

**Comment by siftuser** [comment]
> You can zoom the time in and out by clicking the year or month headers but I find it easier to just alt scroll the mouse.

EPIC! Thank you!!!

PS: If feasible, please add time scoping ... because MFT results run across decades & found it bit overwhelming to scroll, zoom-in to specific time period

**Comment by scudette** [comment]
Fixed in 0.6.1 - this description is expanded in the release notes http://localhost:1313/blog/2021/2021-09-07-release-notes-0.6.1/

**Comment by siftuser** [comment]
Thank you @scudette 

PS: the detailed release note link points to `localhost` :)

**Comment by scudette** [comment]
Argh thanks! it should be https://docs.velociraptor.app/blog/2021/2021-09-07-release-notes-0.6.1/ of course!
