### ISSUE TITLE
Feature Request: parse_string_with_regex return all matches

### ISSUE THREAD

**Issue by defensivedepth** [Velocidex/velociraptor#1279]
Currently parse_string_with_regex() only returns the last match. Would love to be able to return all capture groups.

**Comment by scudette** [comment]
The reason parse string with regex doesn't support multiple matches is because it is hard to know when multiple matches are expected (this depends on the data itself). So we get a situation where the output can switch between a string and an array randomly making it very hard to use.

Usually when we need to match multiple expressions we use parse records with regex

https://docs.velociraptor.app/vql_reference/parsers/#parse_records_with_regex

This is designed to return multiple matches (records) which we can processed separately.

Currently we don't have a function version of parse records but maybe it's worth doing that to save having a subquery.

Can you describe a practical use case when this might be useful?
