### ISSUE TITLE
Install Binds to IPv6

### ISSUE THREAD

**Issue by joshlemon** [Velocidex/velociraptor#1303]
When installing Velociraptor on a Ubuntu Server 20.04 (which includes IPv4 and IPv6 enabled by default) and using the Let's Encrypt install option, Velociraptor will only bind to IPv6 and not IPv4.

It should really bind to both IPv4 and IPv6.

**Comment by scudette** [comment]
How do you know that it does not bind to ipv4? Are you unable to connect to the IPv4 address of the interface?

Velocirptor will bind to all addresses when the bind address is set to 0.0.0.0 (in the case of lets encrypt this is what happens) the OS will show it is only listening on tcp6 but it will also accept connections on ipv4 as well because the OS is dual stack. For example on my machine:

```
$ netstat -anplt | grep veloci | grep LISTEN
tcp        0      0 127.0.0.1:8889          0.0.0.0:*               LISTEN      1461446/velocirapto
tcp        0      0 127.0.0.1:8003          0.0.0.0:*               LISTEN      1461446/velocirapto
tcp6       0      0 :::8000                 :::*                    LISTEN      1461446/velocirapto
tcp6       0      0 :::8001                 :::*                    LISTEN      1461446/velocirapto
```

The frontend is configured as:
```
Frontend:
  bind_address: 0.0.0.0
  bind_port: 8000
```

While the GUI is configured to listen on 127.0.0.1 only. But you can see that although it is listening on 0.0.0.0 and netstat shows it is bound to tcp6 it still can receive  ipv4 connections as well - its just the way it is shown.

**Comment by joshlemon** [comment]
This is what I'm seeing across two different (attempted) deployments with `velociraptor-v0.6.1-linux-amd64`

```
netstat -anplt | grep veloci | grep LISTEN
tcp        0      0 127.0.0.1:8001          0.0.0.0:*               LISTEN      676/velociraptor.bi
tcp        0      0 127.0.0.1:8003          0.0.0.0:*               LISTEN      676/velociraptor.bi
tcp6       0      0 :::80                   :::*                    LISTEN      676/velociraptor.bi
tcp6       0      0 :::443                  :::*                    LISTEN      676/velociraptor.bi
```

```
Frontend:
  hostname: [REDACTED]
  bind_address: 0.0.0.0
  bind_port: 443
```

**Comment by scudette** [comment]
Yep this looks fine 😊 have you started going through the debugging steps here https://docs.velociraptor.app/docs/deployment/troubleshooting/
