### ISSUE TITLE
Consistent Time Constrains/Timebounds For All Artifacts

### ISSUE THREAD

**Issue by architect00** [Velocidex/velociraptor#1315]
Hi,

I'm currently fixing two artifacts, which do not honor the `DateAfter` and `DateBefore` time constrains. In the process I discovered that the artifacts differ in how they set their time constrains.

## Problem

Example: The `Evtx` artifact uses `>=` and `<=` to check events for the user specified time constrains. The `USN` artifacts on the other hand uses `<` and `>` to check the constrains.

A quick'n'dirty regex check of the artifacts directory resulted in 17 files matching the `<>` time constraint mechanism and only 1 file (evtx) matches `>==<`. 

## Proposal

I would change all artifacts to match the `>=` and `<=` mechanism. In my opinion this is more user friendly. 

*Example:*  
Think of an incident happening on the _2021-10-08_. A analyst would think of: _I want to check artifacts X on the day of the incident 2021-10-08_
The time constrain would likely to be set to _2021-10-08 00:00 - 2021-10-09 00:00_. 

I understand that `>` or `<` would not make a big difference if time constrains are set on days or hours. I would argue it starts to matter on busy machines. Analysts might filter down to minutes or seconds to find a specific event, if they perform time based correlation.

What do you think about the idea? I could implement the change in the process of fixing the two artifacts.

Greetings, David

**Comment by scudette** [comment]
Internally times are stored in nanoseconds so say CTime would be 2021-10-08T08:12:12 and if the bound was 2021-10-08T00:00 then > or >= would be the same. If the CTime is showing  as 2021-10-08T00:00 then probably there is some ns difference either way so the = case wont really match.

The only time it makes a difference is when the times are exactly the same (in ns) so this usually means
1. The time is stomped so it is artificially a whole number 
2. The comparison occurs between two times that are not user settable (eg. Mtime > Ctime )

What you describe with the EventTime filtering out does not sound right - are you sure there were events after 2021-10-08 in UTC? Velociraptor always uses UTC for all times

In VQL calling a function is not free and it depends on how often the function is called. For example the MFT scan is optimized in a special way to ensure we dont do unnecessary operations because mft has to process millions of records. Calling a function there leads to approximately 2x slow down so we avoid it. If the difference is only to improve readability and reuse it is not usually worth it for very hot comparisons (that process a lot of rows). But it is fine for e.g. comparing prefetch files (there are not that many of those). 

So it generally depends on the use case.
