### ISSUE TITLE
Feature request: Ability to selectively hide built-in artifacts 

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#133]
VR provides an excellent set of built-in artifacts, but in the GUI these can be somewhat overwhelming to new users, especially given the fact that some artifacts overlap in functionality. Not loading the default artifacts can also reduce the cognitive load for responders by offering only a limited set of (custom) artifacts: ones which are tested, approved for us, and appropriate for a specific response workflow. 

It would be great to have a CLI switch and/or server.conf setting to prevent loading of the built-in artifacts. The setting doesn't need to enforce the use of `--definitions` because VR will still default to reading `/filestore/artifact_definitions` where custom artifacts are stored, and where a custom set could be placed. Obviously using `--definitions` would be a good way to go about it too.

**Comment by scudette** [comment]
There are some built in artifacts that must be loaded because they are required for system operations - for example the Generic.Client.Stats and Generic.Client.Info

Maybe we can mark them as such and just not load the others.  Not sure about hiding those in the GUI because users are supposed to change those.

This feature also touches on the wider topic of user acls - Currently users are either read only or full access . We did think about how to restrict this a bit and maybe one way is to provide an approved set of artifacts for some users to be able to view?

So a super admin user might be able to view all artifacts while a lower access user will only see a list of approved ones (and also not be able to add/edit existing ones obviously). 

In that usage scenario default artifacts should still be loaded (because admin users might want to customize then or bless them for general use).

**Comment by predictiple** [comment]
Good point regarding the operational artifacts. They must be loaded and I don't think those need to be hidden at all. I'm reluctant to use the term "hide" because I don't think anything should be loaded and not displayed. What I'm meaning is that most of the artifacts can be seen as examples. Once a specific set of examples are customised and tested ("blessed" as you put it) then it would be nice to be able to load _only those_ (and their dependencies too obviously) without the visual "noise" of all the other built-ins.

I'm not in favour of RBAC and restricting access to features because it goes against VR's philosophy of simplicity. What I'm proposing with this feature request is to achieve more simplicity by uncluttering the GUI of unneeded artifacts.

There seems to be a need for some labelling of artifacts as "system" (the ones required for VR ops) vs. "standard" (the ones that are optional). Perhaps as an additional field in the artifact's parameters key? Perhaps also an "enabled" attribute within the artifact could cause VR to ignore it when set to "false"? Again - to keep things simple - I don't think that VR needs to do any enforcement or sanity checks based on these values: if an artifact such as Generic.Client.Info is labelled as "type: system" with "enabled:true" and I stupidly set it to "enabled:false" or remove it entirely then I don't expect VR to catch my mistake. To be clear "enabled:false" would mean that VR should discard the yaml because it would have to read it first to determine that setting. If an artifact with the same path/name is read from a --definitions location and that file specifies "enabled:true" then that should take precendence.

**Comment by scudette** [comment]
So maybe we are only talking about a GUI feature here - by default only have some artifact labeled as "blessed" and hide the rest but they will still be loaded. It is hard to not load all the artifacts because as you point out, there are dependencies - for example the Windows.KapeFiles.Targets artifact is supposed to be the public facing artifact but it uses two other artifacts under the hood to work. So we have to load them all.

Maybe we have a detailed and standard view in the artifact collector GUI? 

We will probably also need a UI to assign it to be unhidden. Users could always view any artifact if they tick the "view all artifacts" checkbox (which will be off by default). Then they can check an attribute of the artifact to add it to the unhidden group somehow. 

This gives users the ability to choose themselves if they want to see those by default or not. 

As for the ACL idea we may be able to leverage this by simply removing the ability to view all artifacts and edit their hidden/unhidden status. This essentially prevents these lower privilege users from launching these artifacts.

**Comment by predictiple** [comment]
Yes, this does seem like a GUI feature - at least not display artifacts that have an "enabled:false" or "visible:false" parameter within the artifact itself.

The idea of making the visibility editable via the GUI and tying that to RBAC seems like a major feature while I'm hoping for something much less daunting. 

Having a "GUI visibility" parameter in each artifact might also be beneficial in that the full set of artifacts are then still available via the API and for internal use / dependencies.

**Comment by scudette** [comment]
Im not sure visibility makes sense to be controlled from within the artifact itself - what one user might consider useful to show might not agree with another user. If we control visibility inside the artifact it will be hard to change.

**Comment by predictiple** [comment]
Ok, so let's leave it as something to mull over. It would be cool if there was an easy way to make the artifact choices in the GUI less overwhelming, but not if it comes at the cost of some expensive GUI-based artifact management feature or that necessitates the development of RBAC.

Perhaps a blacklist/whitelist of artifact names / paths in the config?

**Comment by scudette** [comment]
This is now possible with 0.4.6 - simply specify a regex to only show certain artifacts in the GUI.

https://github.com/Velocidex/velociraptor/blob/1edf062844cdac1988409d9bb191d7ed86fe93ff/config/proto/config.proto#L316
