### ISSUE TITLE
Velociraptor.exe process keeps binding to more and more ports

### ISSUE THREAD

**Issue by Socengineer** [Velocidex/velociraptor#1383]
Environment: 
Windows Server 2016 Datacenter 
Version 1607
OS Build 14393.4350

Velociraptor process starts bind itself over time increasingly to more and more ports for outgoing TCP connections, without ever releasing any of them, causing the amount of available higher ports to run out, which causes the application server to crash.

![image](https://user-images.githubusercontent.com/94682062/142610090-8ba73c57-3e76-43df-9acf-8250343fe906.png)

Please advise whatever telemetry or logs you require to investigate.

Thanks

**Comment by scudette** [comment]
Thanks for reporting - can you please attach the full output of `netstat -n -b -o`

Can you also please collect client profile information using Generic.Client.Profile then export to zip file and attach to this issue (or email to support@velocidex.com). This will tell us what queries are currently running and we can see the connection logs and metrics etc.

Finally can you please also indicate the version of velociraptor with `velociraptor.exe version`

![image](https://user-images.githubusercontent.com/3856546/142621722-2259bdca-4659-4009-87b7-28aaee1833d2.png)

**Comment by scudette** [comment]
Looking at this in more details, the client under normal operations definitely reuses the same TCP connections. 

What could happen however, is if the connection errors out for some reason, such as maybe the server returning a 500 or a captive portal the client is unable to reuse the connections and will reconnect again each time - although technically it is supposed to sleep a couple minutes between connection attempts.

Collecting the logs as above will indicate if there is a connection issue with the server and that the client is properly enrolled.

**Comment by cpavel** [comment]
We are having the same issue in our environment as well - we will collect and send the data

**Comment by scudette** [comment]
Thank you all for reporting this issue, this was a hard bug to track down. Luckily a number of users were able to capture logs which really helped.  One of the goroutine logs show many goroutines stuck on a select

```
goroutine 278 [select, 4475 minutes]:
net/http.(*persistConn).writeLoop(0xc000f33320)
        /home/mic/go/src/net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
        /home/mic/go/src/net/http/transport.go:1748 +0x1e65
```

The time (in this case 4475 min) indicates how long the code is blocked on that statement. Looking through the times it does not appear that the code is connecting rapidly at all - it looks to be connecting at the correct frequency (every 1-2 min at most)

Looking at the code in the traceback the writeLoop() function is waiting for the close() to be called. This indicates that the code is not closing the socket properly.  Closer inspection the Post function here 

https://github.com/Velocidex/velociraptor/blob/5b5dc69ee76b0c603d3ff0d83d640e477ba17358/http_comms/comms.go#L238 

Shows that there is one code path where the socket is not closed - namely when the error status is not 200. So if the server returns a 500 the client will leak a socket for each connection. The server returns 500 as part of load shedding or for other reasons (for example if there is nginx in front and it is having problems).

Usually the code does close the socket properly, because on a 200 connection the response is passed to the caller (which closes it) but on the rare occasions where a 500 is received there is a leak. 

This is why it was hard to find this bug because by the time got to inspect the client logs and collect traces typically the connection is restored and we did not observe anything out of the ordinary. 

The fix is simple but this was a difficult bug to find - thanks everyone for contributing the traces :-)

I will publish the fix shortly on master and rebuild new client binaries for 0.6.1 and 0.6.2.
