### ISSUE TITLE
execve: Multiple commands?

### ISSUE THREAD

**Issue by xme** [Velocidex/velociraptor#1418]
Hello *,

I'm trying to execute some commands via execve(). I need to execute 2 separate commands.
I tried this:
`cmd1 && cmd2`
But it does not work properly.
How would you recommend executing the two commands? Is there a way to perform multiple sequential calls to execve() ?
Tx!

(Sorry for the noise here but I did not find anything relevant in the documentation)

**Comment by mgreen27** [comment]
The below worked for me on MacOS notebook 
![image](https://user-images.githubusercontent.com/13081800/145298779-1585f3fc-c690-46b1-9660-552e4fba12b4.png)


You can also copy paste some of the execution based artifacts we have for inspiration:
Windows.System.PowerShell
Windows.System.CmdShell
Linux.Sys.BashShell
Windows.System.VBScript

**Comment by scudette** [comment]
Try not to do that though :-) The execve plugin does not use the shell to launch the new process deliberately.

Using the shell introduces a whole can of worms in the form of shell escape vulnerabilities so execve is very careful to not allow free form command line. That is also the reason why we really do not recommend to call execve with `argv= split(string="command line with spaces", sep=" ")` because this is fragile and leads to vulns.

If you want to run multiple execve just run multiple queries in a chain:
```sql
SELECT * FROM chain(
a={
  SELECT * FROM execve(argv=["first", "commmand", "with", "args"])
}, b={
  SELECT * FROM execve(argv=["Second", "commmand", "with", "args"])
})
```

If you have lots of commands to run you can just create big array:
```sql
LET script = (
 ("ls", "-l", "/"),
 ("ls", "-l", "/boot"),
)

SELECT * FROM foreach(row=script,
query={
   SELECT * FROM execve(argv=_value)
})
```

**Comment by scudette** [comment]
btw these `Windows.System.PowerShell` `Windows.System.CmdShell` `Linux.Sys.BashShell` `Windows.System.VBScript` are really supposed to be breakglass type artifacts with very little control over execution (they require admin rights and are inherently unsafe to run). They actually are the thing behind the shell feature in the GUI which should be used with great care and rarely under normal circumstances.

Please do not use them as a basis for new artifacts.

**Comment by scudette** [comment]
This seems resolved.
