### ISSUE TITLE
Best way to download/update a file from the server?

### ISSUE THREAD

**Issue by xme** [Velocidex/velociraptor#1439]
Hi *,
I'm facing a strange issue. I've a file with indicators downloaded at regular interval by clients (csv file). When the newly downloaded file is **smaller** than the previous one (less indicators), the file on the client is corrupted because it seems to be overwritten but not replaced...
Here is the code I'm using to download the file:
```
LET Data = SELECT Content FROM http_client(url="http://velociraptor/public/indicators",
    tempfile_extension=".csv")
LET SaveIndicators = SELECT upload_directory(
    accessor='file', 
    file=Data.Content, 
    name=IndicatorsFile,
    output=IndicatorsPath) 
    AS IntelUploadDetails 
    FROM scope()
```
Ex: the file is 5Mb large. Then a new one is generate and is 4Mb large, the new file is downloaded, 4Mb are dumped but the remaining 1Mb is still present at the end of the file!? (and makes it broken)

What's the best method to download and update a file from the server and dump it at regular interval?

**Comment by weslambert** [comment]
In this case, you'd probably want to do something like:

```
LET SaveIndicators = SELECT copy(accessor="file", filename=Content, dest=$YourDestFile) AS FullPath 
                        FROM http_client(url="http://velociraptor/public/indicators", tempfile_extension=".csv")
```

**Comment by scudette** [comment]
This looks to be a bug in the FileBasedUploader here

https://github.com/Velocidex/velociraptor/blob/ac4429e0fa0681f304f21c5ee379d7bd55ec1d32/uploads/file_based.go#L110

The uploader creates the file but does not truncate it so if the file is re-used the file becomes corrupt in the way you mentioned. Usually the file based uploader is used for collecting on the command line (using velociraptor artifacts collect --dumpdir ... ) so it kind of expects a new directory each time. This explains why we never hit the bug before because we usually use `upload_directory()` on a fresh directory each time.

Anyway thanks for reporting this - we will fix for the next release. The workaround here is to either:

1. Use a new directory each time (e.g. a tempdir will cleanup after each collection by itself)
2. Use the copy() function as indicated by @weslambert 
3. Remove the file before writing it using the rm() function

**Comment by xme** [comment]
Tx to Wes for the code update (I'll probably borrow you again ;-) and happy of my first bug report!
