### ISSUE TITLE
Windows.Forensics.Prefetch - Incorrect run count for windows 10 hosts

### ISSUE THREAD

**Issue by angry-bender** [Velocidex/velociraptor#1533]
**Describe the bug**
Velociraptor reporting incorrect run counts for windows 10 20H2 prefetch files.

**To Reproduce**
1. Install windows 10 20H2
2. Run notepad and calc once (Win 7 and Win10 prefetch files used are available from [here](https://github.com/angry-bender/forensics-files/tree/main/Prefetch%20files) )
3. Run local VR server
4. Create local notebook with the following VQL

```
SELECT * from Artifact.Windows.Forensics.Prefetch()
WHERE Executable =~"notepad" OR Executable =~ "calc"	
```
5. Run PECMD or WinPrefetch view to validate
6. Double checked Win7 artefact still correct.

**Expected behavior**
Expect run count to show 1. However it is showing 7 for calculator, 3 for notepad.

**Screenshots**

***VR output***
![image](https://user-images.githubusercontent.com/18164137/151899779-888e19f0-5d2d-4991-823c-87dc3f70a21a.png)

***pecmd output***
![image](https://user-images.githubusercontent.com/18164137/151900662-ecd8cbb9-2017-4ea6-8045-488b3744d0ce.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 (build 19042.631)
 - VR: velociraptor-v0.6.3-windows-amd64
 - Affected artefacts: `windows.forensics.prefetch` `windows.timeline.pretch`

**Additional context**
Windows 10 uses a different compression algorithm to Windows 7 prefetch [a first look at windows 10 prefetch](https://blog.digital-forensics.it/2015/06/a-first-look-at-windows-10-prefetch.html).

The artefact may not be reading the correct feild or offset in the RAW files for VR, and im not 100% sure how to look at the raw data VR pulls to see where the issue lies. It could be worth importing Eric Zimmermans PECmd onto the VR server to parse prefetch files as they are pulled from clients to save reverse engineering efforts.

**Comment by scudette** [comment]
As you can see there are a couple places where this field could come from

https://github.com/Velocidex/go-prefetch/blob/37e4751dd5ca1e02ba9adbdaf8300591c0a70a9c/prefetch.go#L91

Can you attach the sample prefetch files to this issue? Probably we need to adapt the struct parsing a bit

**Comment by angry-bender** [comment]
> As you can see there are a couple places where this field could come from
> 
> https://github.com/Velocidex/go-prefetch/blob/37e4751dd5ca1e02ba9adbdaf8300591c0a70a9c/prefetch.go#L91
> 
> Can you attach the sample prefetch files to this issue? Probably we need to adapt the struct parsing a bit

Sure thing, I have uploaded the files here https://github.com/angry-bender/forensics-files/tree/main/Prefetch%20files

**Comment by scudette** [comment]
Thanks! 

Looking at the format docs here https://github.com/libyal/libscca/blob/main/documentation/Windows%20Prefetch%20File%20(PF)%20format.asciidoc#424-file-information---version-30 it looks like this is a version 30 struct which is slightly different from a version 26. The run count offset is at 116 instead of 124

**Comment by angry-bender** [comment]
> Thanks!
> 
> Looking at the format docs here https://github.com/libyal/libscca/blob/main/documentation/Windows%20Prefetch%20File%20(PF)%20format.asciidoc#424-file-information---version-30 it looks like this is a version 30 struct which is slightly different from a version 26. The run count offset is at 116 instead of 124

Hmm, is that a case of adding another offset in the switchcase of [https://github.com/Velocidex/go-prefetch/blob/37e4751dd5ca1e02ba9adbdaf8300591c0a70a9c/prefetch.go#L91 ](https://github.com/Velocidex/go-prefetch/blob/37e4751dd5ca1e02ba9adbdaf8300591c0a70a9c/prefetch.go#L91 ) ? It looks like windows might have changed it, i can see if i can test with an earlier version of Win10 if it helps?

**Comment by scudette** [comment]
Yeah basically need to add another struct layout and switch based on the version here https://github.com/Velocidex/go-prefetch/blob/37e4751dd5ca1e02ba9adbdaf8300591c0a70a9c/prefetch.go#L55

Unfortunately this parser is written in Go which means a new client needs to be deployed once the fix is in. We dont tend to use parsers in Go much any more as we have a more powerful parser now in VQL - this gives us the ability to update parsers on the fly. But in this case we need the lz compressor to get at the binary data.

I will open an issue against the relevant repo and will get that fixed asap! thanks for reporting!

**Comment by scudette** [comment]
This is now in head with #1585 supporting all the documented variants of prefetch. We also have volume information parsing now (which we didnt before).
