### ISSUE TITLE
failed to parse PEM block containing the key (in PKCS#8 format)

### ISSUE THREAD

**Issue by dmach** [Velocidex/velociraptor#1556]
Velociraptor doesn't seem to be able to handle some types of keys.

Keys generated with this command do not work:
```
# PKCS#8 format
openssl genpkey -algorithm RSA -out <key> -pkeyopt rsa_keygen_bits:2048
```
While keys generated with this command do:
```
# PKCS#1 format
openssl genrsa -out <key> 2048
```

When I used the keys generated with `openssl genpkey`, the first run displayed an error and exited:
```
...
[DEBUG] 2022-02-10T08:12:01Z Flushed index in 176.101µs. 
[INFO] 2022-02-10T08:12:01Z Exiting Launcher Service 
[INFO] 2022-02-10T08:12:01Z Exiting notification service! 
velociraptor-v0.6.3-linux-amd64: error: frontend: starting frontend: failed to parse PEM block containing the key
```

The second run hang and I had to kill the process:
```
...
[DEBUG] 2022-02-10T08:14:15Z Flushed index in 222.125µs. 
[INFO] 2022-02-10T08:14:15Z Exiting notification service! 
```

**Comment by scudette** [comment]
When you say " I used the keys generated with openssl genpkey" how are you using the keys and for what? Velociraptor normally generates its own keys - you do not need to manually generate anything. 

What are you trying to achieve?

**Comment by dmach** [comment]
I wanted to use my own CA to sign the certs.
Self-signed certs are no-go and I don't want to use Lets Encrypt instead of my own CA.

I can generate keys in the PKCS#1 format, that's not a problem.
I just wanted to let you know that Velociraptor doesn't support some of the key formats openssl does.

**Comment by scudette** [comment]
You can use your own CA around TLS by specifying your cert files here:
https://github.com/Velocidex/velociraptor/blob/8266688b2b10ca11de4e7b8738f027cf2a8a08a9/config/proto/config.proto#L531

and you can embed your CA's certificate in the client's configuration here
https://github.com/Velocidex/velociraptor/blob/8266688b2b10ca11de4e7b8738f027cf2a8a08a9/config/proto/config.proto#L207

This way the clients will connect to your server using your own CA to secure the TLS

It is possible to create the whole CA/certificate chains in openssl as described here https://gist.github.com/mpilking/bb8dd1d48e036880f551f9672e5e9e30 

But this is not for the faint of heart :-). I think it is not super user friendly to start messing with openssl

Maybe we need to better understand the use case - is it just that you want your ca to be used on the TLS side? or do you want it used internally as well? Note that using an external CA for Velociraptor's internal PKI will make Velociraptor less secure because if the external CA is compromised then it can be used to sign API keys as well. If you have the API port exposed, this will lead to complete compromise of Velociraptor.

**Comment by scudette** [comment]
I dont think there is anything more to do here? Closing.
