### ISSUE TITLE
Embedded Agent: reinstall leave configuration files behind

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#16]
I just reinstalled on a windows 10 machine with an embedded configuration.
The install was over the top of a current install without embedded configuration. I noticed the configuration file was not removed. I was unable to have my client communicate back to the server until I removed the configuration file (the config file had incorrect configuration).

If possible please make an embedded install check for and remove any configuration files in its installation directory.

Matt

**Comment by scudette** [comment]
There are 3 places where we grab the configuration:

1. Embedded inside the binary.
2. In the config file location
3. In environment variables.

We work our way in the above order - it allows a config file to override an embedded configuration, and environment variables to override everything. We deliberately allow the embedded config to be overriden by the config file because we can push config files via GPO (or even via Velociraptor) if we need to update something. In practice though we never really need to do it - so maybe this whole point is moot.

I think in practice you should not use the embedded config option because embedding will destroy the authenticode signature (unless you re-sign it). The only reason this option is there is because GRR has something like that so it is mostly historic and might go away at some point.

The proper way to install is to build an MSI - this takes care of removing the config file when you uninstall or upgrade properly - which you can not do with the simple built in installer. You can find out how to do it easily here https://github.com/Velocidex/velociraptor/tree/master/docs/wix

You can still use the simple installer but provide it a config file:
```
velociraptor --config client.conf.yaml service install
```

Should copy the file to its location - overwriting the existing one.

**Comment by mgreen27** [comment]
Closing issue as question answered
