### ISSUE TITLE
GLIBC_2.28 Not Found In Newest Release 0.3.6

### ISSUE THREAD

**Issue by backcountryinfosec** [Velocidex/velociraptor#166]
Running the Linux binary in the newest release 0.3.6 gives the below error. I'm attempting to run on a stock Ubuntu 18.04 server OS. The version of this binary initially uploaded a few days ago when 0.3.6 was released was working correctly. I downloaded a copy again tonight and it's now throwing the error:

./velociraptor-v0.3.6-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./velociraptor-v0.3.6-linux-amd64)_

Md5 of velociraptor-v0.3.6-linux-amd64:  b54ea48eb9ada15aee9ff623f1704554

Nothing on my OS has changed however it appears the binary may have been recompiled with a change since it's initial upload? Please correct me if I'm wrong.

**Comment by scudette** [comment]
Hey yeah - I rebuilt all binaries on the 13th to add the signed windows binaries and MSI. 

It is possible that I had not used the docker build for the linux binaries (make release vs. make build_release). We need to build the Linux binary with the docker builder for compatibility with older linux hosts.

You can get a binary at every commit (described in the README file). I am pretty sure that Linux binary works on 18.04. 

Because we distribute signed windows binaries and the signing system is offline, sadly the release process is pretty manual at this stage :-(. I will automate it more for the next release...

**Comment by backcountryinfosec** [comment]
Thinks Mike, I pulled the binary from AppVeyor and it works great. Also thanks for all the continued effort into this, quite amazing!
