### ISSUE TITLE
Export host list from "All hosts" page

### ISSUE THREAD

**Issue by cr-AustinBollinger** [Velocidex/velociraptor#1667]
This is a convenience request, and would be intuitive.
When navigating to <velociraptor_fqdn>:8889/app/index.html?#/search/all one sees a list of maximum 50 hosts at a time, then they can next into infinity.

At the top-right, having a nice csv export icon would be most ideal.

**Comment by scudette** [comment]
You can get a full dump of all hosts using:

1. Notebook: `SELECT * FROM clients()` then export as CSV
2. Run the server artifact `Server.Information.Clients` and export either the result table or the whole collection.

Those options show a lot more information than the search screen (which shows a very small summary of client info because it has to fit in the GUI table). You can also get the full result of a search like this (this is exactly equivalent to the search bar results):

```sql
SELECT * FROM clients(search='label:MyLabel')
```
