### ISSUE TITLE
Use RECmd Batch files to search for registry artifacts

### ISSUE THREAD

**Issue by svch0stz** [Velocidex/velociraptor#1791]
The RECmd repo contains several ".reb" files which include lists of important registry keys and values. Ideally, we can have an artifact to and input these files to tell velociraptor to fetch these keys and values.
EG: 
https://github.com/EricZimmerman/RECmd/blob/master/BatchExamples/Kroll_Batch.reb

Currently the parse_yaml function has trouble reading them: 
![image](https://user-images.githubusercontent.com/8684257/167971312-f9e8c053-4cd9-4c6c-a732-da54d1974c65.png)

**Comment by svch0stz** [comment]
@mgreen27 :)

**Comment by scudette** [comment]
It might make more sense to parse these files into an intermediate Json or yaml format and autogenerate an artifact like the kapefiles one

**Comment by scudette** [comment]
Looking more closely at it - the batch files do not actually contain much logic in them - they primarily call plugins written in C#. We will need to implement these manually since they are written in C# and can potentially contain arbitrary logic - although the logic may not be very complex and can be easily done in VQL this will require manual intervention. 

I think this issue is much larger than simply converting some yaml files. We will push it to the next release

**Comment by scudette** [comment]
This is now implemented within the registry hunter project https://registry-hunter.velocidex.com/
