### ISSUE TITLE
Unable to load config file: No Frontend.certificate config

### ISSUE THREAD

**Issue by moksharthab** [Velocidex/velociraptor#1797]
Hi Team,

We are looking to deploy velociraptor in our enterprise. We have noticed that our laptops was not communicating to server because of our Palo Alto Firewall issue.

We were notified by our Network security team that it is related to certificates issue. The firewall is receiving the client certificate and is sending its certificate to client instead of the server one and as a result of which communication isnt happening.

We were requested to add the client certs to the Firewall CA store and also add Firewalls root cert to the client config file.

https://docs.velociraptor.app/knowledge_base/tips/ssl/

 
We came across this article which found to be very useful. We still are not using our own certificates, instead we are trying to fix the issue with the certificates and keys from the default self-signed deployment, but using the recommended settings mentioned in the above article.

When i make all the changes and try to setup the new server,

 

velociraptor-v0.6.3-windows-amd64.exe --config server.config.yaml frontend

 

i get an error like below:

 

Unable to load config file: No Frontend.certificate config

 

 

I have placed the velociraptor.key and velociraptor.pem in the Temp folder which are referenced and used in the Frontend section.

 

Please help us with this issue. I am also attaching the client and server config files.

**Comment by scudette** [comment]
It is failing to start because you removed the certificate part from the Frontend config. Velociraptor always uses its internal PKI to secure communications. In **addition** it also uses TLS to secure network comms. This is where `tls_certificate_filename` comes in - it affects the TLS layer only (which is what the firewall/mitm proxy can see) so we present the correct certs for it based on the config but the actual data transmitted is still always encrypted using Velociraptors internal PKI **as well**.

So as the reference you point to is saying: `Locate the frontend section and add the tls_certificate_filename and tls_private_key_filename parameters.` but do not remove the other parameters :-).

BTW please regenerate your key material and be careful sharing the server config since it contains the key materials that  can allow server takeover.

**Comment by moksharthab** [comment]
Thank you very much :)
