### ISSUE TITLE
EventData function does not exist!

### ISSUE THREAD

**Issue by minirobot22** [Velocidex/velociraptor#1818]
when trying to use the CLIENT EVENT watch_etw() with EventData like below for ex.

`SELECT EventData.QueryName AS Query FROM watch_etw(guid="{1C95126E-7EEA-49A9-A3FE-A378B03DDB4D}") WHERE System.ID=3008
`
the EventData does not seem to exist as well as System.ID, and the returned results are empty

![image](https://user-images.githubusercontent.com/49622579/170890335-00cfc005-e997-4eeb-95ba-83a4d0450a13.png)

also, another issue when using the plugin watch_etw() in a notebook, I get the following error

**Plugin watch_etw not found. Current Scope is: [NULL], [$cache, $device_manager, config, $acl, $uploader, Artifact, $root], [NotebookId], [$Query]
Plugin watch_etw not found. Did you mean watch_auditd watch_csv watch_evtx watch_monitoring watch_syslog watch_usn?**

**Comment by scudette** [comment]
When you run a query in a notebook it is running on the server. If you have a Linux server there is no ETW plugin implemented and you get that error message.

We recommend you use `velociraptor.exe gui` on a windows machine to run the demo server on windows and then, the notebook queries will be evaluated on Windows and watch_etw() will be available.

I also recommend at the initial part of exploring the queries you use `SELECT * FROM ...` because that will show you all available columns. In ETW, EventData has a different structure for each event type. So many events may not have the member you are referencing (VQL will return NULL in that case).

Specifically for ETW take a look at this two presentations https://docs.velociraptor.app/presentations/2022_auscert/ 

Running your query in the notebook (on a Windows Machine) shows it works well. Note how I added the * to the query just to double check the available data (but it looks like event 3008 does have a QueryName field).

![Windows_11_Test_VM_2022_2](https://user-images.githubusercontent.com/3856546/170918462-7e26eb3d-21cf-45e7-9dc0-d660a466772f.png)

**Comment by minirobot22** [comment]
Thanks, that explains why I am not able to execute watch_etw().
For EventData part,  it appears that I was checking an old records resulting from an incorrect queries that I have first made for testing, but I was not seeing the new current one which I have posted in the first comment due to the limitation in client events tab (reports, raw data), I noticed it only shows a max of 10 pages, it does not show records more than that, does it? I have to export it as CSV to see all the records.
Is there a way to expand that in the client events tab, as well as to remove the old table/records because I don't see that option as well.

**Comment by scudette** [comment]
The way the UI works is that the table shows the next events found to the right of the cursor. The cursor is pointing to a time of interest, then the table shows the next 10 events after that. If you want to see later events, just move the cursor more to the right to point at a later time.
![Windows_11_Test_VM_2022_2](https://user-images.githubusercontent.com/3856546/170997912-ab2756fd-a0f2-4bad-9dec-2e8e45558796.png)

**Comment by minirobot22** [comment]
Thanks for the clarification.
