### ISSUE TITLE
Registry Provider Issue

### ISSUE THREAD

**Issue by minirobot22** [Velocidex/velociraptor#1834]
When running the following general query 

`SELECT * FROM watch_etw(guid="{70EB4F03-C1DE-4F73-A051-33D13D5413BD}")`

where the specified GUID value is related to the registry provider (Microsoft-Windows-Kernel-Registry)
the KeyName field in the EventData is always empty or NULL, regardless of the system ID specified (setKeyValue, QueryKey,..etc) as below examples

![querykey](https://user-images.githubusercontent.com/49622579/171503089-e22beaf8-cdb7-4fbb-b314-4b76a74451cb.JPG)

![setkey](https://user-images.githubusercontent.com/49622579/171503215-6849c661-c5cf-44c5-8b1f-5b10285e01d5.JPG)

Any fix for this?

**Comment by scudette** [comment]
Thanks for discussing this provider - it is a very promising ETW provider but unfortunately it is a bit of a pain to work with it. I don't know why bother adding a KeyName field if they are not going to populate it :-).

The schema for this provider is described here
 https://github.com/repnz/etw-providers-docs/blob/master/Manifests-Win10-10240/Microsoft-Windows-Kernel-Registry.xml

You can see for example the events you show above - 4 means QueryKey and id 5 means SetValueKey but they dont tell you the actual key name - instead they tell you the key object's kernel memory address. You have to track the kernel object to key name from the OpenKey event (ID 2)

![Windows_11_Test_VM_2022_2](https://user-images.githubusercontent.com/3856546/171544464-50950768-4468-4ddd-abf2-be33f29d95a6.png)

So the way it works - when the userspace opens a key with OpenKey, the ETW event registers the key's name and the Kernel Object memory address. Then for all other operations on that kernel object, the ETW event just refers to the kernel's address.

The following query will keep track of the mapping between kernel address and relative name:
```sql
LET Cache <= dict()

SELECT *, get(item=Cache, field=EventData.KeyObject) AS RelativeName
FROM watch_etw(guid="{70EB4F03-C1DE-4F73-A051-33D13D5413BD}")
WHERE if(
  condition=System.ID = 2, 
  then=set(item=Cache, field=EventData.KeyObject, value=EventData.RelativeName),
  else=TRUE)
```

![Windows_11_Test_VM_2022_2](https://user-images.githubusercontent.com/3856546/171546010-644fe5ec-b5be-420c-a26c-658cbc452f20.png)

It is not ideal because the Cache dict has no mechanism to clear after a while so probably we need a proper LRU object here but this approach will work for a while (probably will have a slow memory leak).

**Comment by minirobot22** [comment]
Thanks for clarifying this, yes I`ve been referencing that schema you mentioned to understand the structure of that provider.
Again thanks for the great work as I see a lot of potential in the solution and particularly The idea of Client Monitoring with ETW is very powerful, we are actually trying to customize more useful events like (Registry, File modifications, image load .. etc) in order to deploy the solution to our customer on a lot of endpoints after we test everything first, and monitor/collect all data for 3 to 4 weeks, hopefully will be able to achieve that with your support.

**Comment by scudette** [comment]
Thanks for raising these issues for discussion! I now added an lru() function which will be in 0.6.5 and I think we might be able to add this artifact to the release as well.

**Comment by scudette** [comment]
Added a sample artifact in #1843
