### ISSUE TITLE
client_example.py not working with custom artifact?

### ISSUE THREAD

**Issue by Idriel** [Velocidex/velociraptor#19]
Hi, 

I am testing: https://github.com/Velocidex/velociraptor/blob/master/bindings/python/client_example.py with my custom Artifact where I monitor one Sysmon events. 

```
name: Windows.Events.Sysmon.ProcessCreate
description: |
  Monitor Sysmon Events - Process Create

  This event monitor extracts the process creation events from the
  sysmon event log and records them on the server.
type: EVENT

parameters:
  - name: sysmonLogFile
    default: >-
      C:/Windows/System32/Winevt/Logs/Microsoft-Windows-Sysmon%4Operational.evtx

sources:
 - precondition:
     SELECT OS from info() where OS = "windows"

   queries:
      - |
        SELECT System.TimeCreated.SystemTime as Timestamp,
               System.EventID.Value as EventID,
               EventData.CommandLine as CommandLine,
               EventData.OriginalFileName as FileName,
               EventData.Hashes as Hashes,
               EventData.Image as Image,
               EventData.Description as Description,
               EventData.User as UserID,
               EventData.UtcTime as UtcTime,
               EventData as _EventData
        FROM watch_evtx(filename=sysmonLogFile) WHERE EventID = 1
```

Challange is:
- this is not working: python test.py api_client.yaml "SELECT * FROM watch_monitoring(artifact='Windows.Events.Sysmon.ProcessCreate')"
>>> events are in .csv file and I can see them in webUI

but if I run something like (build in):
- python test.py api_client.yaml "SELECT * FROM watch_monitoring(artifact='Windows.Events.ProcessCreation')"
>>> this will work, and I'll get response in terminal. 

and fast question, is it better to configure Sysmon or use Velociraptor build-in functions for process, network, dns... monitoring?

**Comment by scudette** [comment]
The EVENT type artifacts are for monitoring client events and streaming them on the server. You need to make sure the clients are actually monitoring these by installing these artifacts into the client event monitoring table.

If you are using the new GUI from head you would go to "Client Events" in the navigation menu and then select "Update Client Monitoring Table" and make sure your custom artifact is added. You need to wait a couple of minutes to have such events streamed from the client to the server. You should verify that you can see these events by selecting the artifact in "Select Artifact" pull down.

The API is just watching these logs (thats what watch_monitoring does). So you need to make sure events are being recorded in the first place.  In the end the event logs are just CSV files so you can easily debug step by step as you go.

The reason the second example works is that we collect Windows.Events.ProcessCreation by default already hence by default it will be in the monitoring table so you can listen to it on the API as well.

Regarding your question about sysmon - yes it is better to use sysmon at this stage since Velociraptor does not have a kernel module to capture processes execution logs. We rely on WMI event tracing which is not providing us with a enough information (like full command line). What we do is essentially do a process listing for each process creation event but we might miss the process if it is very short lived. Sysmon can capture more information through its kernel module. We are unfortunately unable to distribute sysmon due to its licensing but it would be nice to have a bunch of artifacts and documentation for people who want to install it on their own.

**Comment by Idriel** [comment]
Hi,

Currently I have only one client, so I dont see in GUI "Client Events". I am using: velociraptor-v0.3.0-linux-amd64 as Frontend

I added artifact into: "Update Client Monitoring Table"

If I go to my Client > VFS > monitoring > here I can see:  Windows.Events.Sysmon.ProcessCreate > if I click on: 2019-07-01.csv I can see events. 

In frontend log there is an event: [INFO] 2019-07-01T08:50:47Z Query API call {"arg":{"Query":[{"Name":"Test","VQL":"SELECT * FROM watch_monitoring(artifact='Windows.Events.Sysmon.ProcessCreate')"}],"max_wait":1},"user":"api"}

but nothing is returned to Script.

**Comment by Idriel** [comment]
I manage to get response when I put with lowercase * from

python3.6 test.py api_client.yaml "SELECT * from watch_monitoring(artifact='Windows.Events.Sysmon.ProcessCreate')"
