### ISSUE TITLE
Artifacts collection stalling for long hours time

### ISSUE THREAD

**Issue by moksharthab** [Velocidex/velociraptor#1914]
We are doing a great deal of testing with Velociraptor.

Whenever our Threat hunting team does some hunts, they are working without any hassle.

Our Forensics team, when they run artifacts like - Windows.KapeFiles.Targets etc, it runs for a while and it stalls completely.

When we go to Log, below is the last message we get.

vql: Creating 30 workers for foreach plugin

Can you help ua get around this problem on what is happening ?

We also see the Timeout is 600 seconds (10 minutes), but the job is still showing as running 4 hours later...

**Comment by scudette** [comment]
Can you please attach more information according to the kb item https://docs.velociraptor.app/knowledge_base/tips/debugging_clients/

You can mail to support@velocidex.com or dm on discord.

**Comment by moksharthab** [comment]
I ran the Generic.Client.Profile artifact

Its almost 20 minutes and I ran it via Hunt Manager.

I still the state as RUNNING. Duration - 0, TotalRows - 0 and TotalBytes - 0.

I definitely see the  client as Connected in the hosts  console.

**Comment by scudette** [comment]
Did you say you were running `Windows.KapeFiles.Target` as a hunt? This is not a great idea as that artifact will typically upload a lot of data. What targets are you collecting? How many machines are in the hunt?

What normally happens in a hunt is that all the clients will receive the collection request and continue to upload the data to the server all at the same time. The server limits the total number of clients it receives at the same time (called client concurrency). So as the data is uploaded it blocks the other clients from getting through until it is their turn. We do this to limit server memory use - you can tweak these settings in the config file to get better throughput  (see https://github.com/Velocidex/velociraptor/blob/96c58345abfebc69764a59a1905cdf95e0ade65a/config/proto/config.proto#L443 )

The clients maintain two connections to the server a send and receive connection - So the send connection is blocked (from client to the server) while loaded but the receive connection is fine and connected (this means you can task the client immediately) which is why it is showing as connected.

This sounds like a typical behavior of a very loaded server (saturated uploads). 

You can confirm by collecting profiles on the server itself - the server artifact `Server.Monitor.Profile` with metrics selected with the following metrics that are useful:

1. frontend_concurrency_wait_latency  - how long clients are waiting to be served by the server
2. frontend_maximum_concurrency - total number of clients we are serving right now (this will cap at 20 by default)
3. frontend_received_bytes - how many bytes in total the frontend received

There are lots of nice numbers there to see (usually we run graphana or data dog metrics for these).

**Comment by moksharthab** [comment]
I ran the server artifact as suggested.

Please find the attached.

**Comment by scudette** [comment]
Looks like the attachment was stripped - can you please paste into the issue on github?

**Comment by moksharthab** [comment]
[server-F.CAUPD1QCPBSV0.zip](https://github.com/Velocidex/velociraptor/files/9020122/server-F.CAUPD1QCPBSV0.zip)

**Comment by moksharthab** [comment]
Yes we are running it on a Windows server. This is a temporary VM, so the
configuration is not so high end.

Server is separate and we have about 10 clients reporting to the server.

**Comment by moksharthab** [comment]
But we are running the collection on only 1 client.

Other artifacts like Generic.Forensics.Timeline and
Windows.Applications.Chrome.History, which we believe to be less strain
than Kape Targets.

Why are even these failing ?

**Comment by scudette** [comment]
From the goroutine dump it looks like you are currently running a heavy server artifact? You can try to collect the profile with the following options enabled:

QueryLog: This will show currently executing queries on the server
Metrics: Gives information on what is happening on the server

Are you saying you can not even collect simpler artifacts from a single client any more?

**Comment by scudette** [comment]
you should try this with 0.6.8 which has a new client/server protocol and also the possibility to collect traces
