### ISSUE TITLE
Implement process GUID for tracker.

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#1924]
Currently I enrich my monitoring artefacts with tracker and obtain process chain with a pid reference.

e.g:`process_tracker_callchain(id=ProcessInfo.ProcessId).Data as ProcessChain`
This works fine most of the time, but we have potenital pid collisions (more frequent than you would think).

An easy solution is to implement a process GUID for tracker similar to sysmon - https://github.com/Sysinternals/SysmonCommon/blob/73ae2ac398dcba2ae01c2e40664f662c9fc270c8/eventsCommon.cpp#L415

**Comment by scudette** [comment]
The tracker id can be any string. Sysmon uses a combination of process start time and pid which is fairly reasonable.

**Comment by scudette** [comment]
On further thought this is actually more difficult to implement. The issue is that we need to address processes by pid because that is all we have from many enrichment sources (e.g. in event logs). So we dont know the process start time to be able to form a unique tracker ID.

We do know though that if PID is reused then the previous process *must have* exited already so maybe we can change the IDs when we detect PID reuse - PID reuse can only affect exited processes.

When detecting a clash we can rename old processes which must have exited and adjust references

**Comment by mgreen27** [comment]
First time I have used this feature in anger ran into this issue and it becomes almost worthless. I think we need to add a guid, even if its our own. Our own may be easier to implement?

**Comment by scudette** [comment]
The issue is not the guid. The issue is that we need to refer to a process by something unique and all we have is a pid which is not unique.

So we need somehow to go from a pid to a unique identifier. The assumption has to be that a pid is a unique identifier for the life of the process. After the process exits the pid is no longer a unique identifier. So we need to actually change it and all references to it safely.

**Comment by mgreen27** [comment]
I think a guid field as a replacement for pid is a much better solution. What is the issue in us generating the same method as Sysmon? Process Start time?

**Comment by scudette** [comment]
Yes exactly, if you are trying to enrich a process from another event log that just tells you the pid a guid is useless. You can search by pid but that might give several hits so that doesn't help either

**Comment by mgreen27** [comment]
I dont see why cant we build guid on event entry into the tracker even for events we dont have telemetry. I think the value of having working process telemetry far outweighs integration with other artifacts.

**Comment by scudette** [comment]
Because we don't get a guid from a process listing. We can't use guids to actually match anything and guids are generally not useful to correlate with any api

**Comment by scudette** [comment]
This issue should be solved now that the process tracker supports pid reuse cases?
