### ISSUE TITLE
Add Authenticode to Windows.Sys.Drivers/RunningDrivers

### ISSUE THREAD

**Issue by ecapuano** [Velocidex/velociraptor#1925]
A very useful datapoint for running drivers is signing status. Consider adding Authenticode metadata for the binary in `PathName` in the results of `Windows.Sys.Drivers/RunningDrivers`

**Comment by scudette** [comment]
Thanks for this suggestion - I initially didn't bother to include authenticode on running drivers because of course they are signed anyway. I missed the insight that seeing the actual signers give to be able to spot vulnerable signed drivers which are a quick win for kernel persistence. 

I added this obvious post processing query as a suggestion to the notebook

![image](https://user-images.githubusercontent.com/3856546/184565212-27a5b9f2-5136-450a-818b-960cb9097b73.png)

**Comment by scudette** [comment]
Fixed by #1991
