### ISSUE TITLE
Setting up a secure server deployment

### ISSUE THREAD

**Issue by prolsen** [Velocidex/velociraptor#2]
Do you have any plans to write a blog post (or youtube video) on how to setup a secure server deployment for Velociraptor? Ex. https on the frontend. I would more than happy to build and share a terraform config around a secure GCP, Azure, AWS deployment if I had the specifics.

**Comment by scudette** [comment]
There is a video demo here https://docs.velociraptor.velocidex.com/blog/html/2018/09/03/velociraptor_walk_through_and_demo.html and a lot of documentation in the workshop https://docs.velociraptor.velocidex.com/blog/html/2018/11/13/velociraptor_training_at_nzitf.html and generally on the docs site.

Velociraptor has its own end to end encryption (Its the same one as used by GRR) so generally it is easier to setup over http. If you want to enable TLS you need to get certs using lets encrypt and this requires a domain name. 

Currently there is no specific support for lets encrypt or TLS but I think we should add it. This package looks very promising https://godoc.org/golang.org/x/crypto/acme/autocert as it will allow Velociraptor to renew its lets encrypt certs by itself.

As for terraform file - deployment is very simple since it is a single executable. We could publish a dockerfile but it would literally be copy the binary from the release site and run it with the provided config.  Since we do not have any runtime dependencies we could use scratch as the base docker image https://xebia.com/blog/create-the-smallest-possible-docker-container/ which should make the container about the same size as the binary (around 20-30mb).

**Comment by scudette** [comment]
https://docs.velociraptor.velocidex.com/blog/html/2018/12/22/configuring_velociraptor_for_ssl.html

It is now also possible to configure Google OAuth SSO for more secure user ID. I will write a post about this next.
