### ISSUE TITLE
Issue in velociraptor-0.3.1.rc1.exe

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#20]
Hi Michael,

I was using velociraptor-0.3.1.rc1.exe and noticed that there appears to be an issue in this version globbing registry keys.

You can replicate the issue Running Windows.Registry.Sysinternals.Eulacheck. This fails to return results in0.3.1RC1 but returns in 0.3.0.

Matt

**Comment by scudette** [comment]
Hi Matt, yeah there was a bug in the default value of the read_reg_key
plugin. It is supposed to be "reg" but it's set to "file" by accident. You
can change the artifact to explicitly set accessor="reg" which will fix the
artifact.


This is fixed in a recent commit and will make it to the next release.

 Thanks for reporting.
Mike
