### ISSUE TITLE
Consider the use of Patternfly or the like to improve the web UI

### ISSUE THREAD

**Issue by q2dg** [Velocidex/velociraptor#2017]
Hello.
It's fair to say that current Velociraptor's web UI is very aesthetically improvable.
Consider the help of https://www.patternfly.org/v4 (like https://cockpit-project.org does) or a similar solution to improve this aspect.
Thanks a lot

**Comment by scudette** [comment]
Can you give a more actionable suggestion? What exactly is the issue? How can we improve it?

It is unlikely that we will rewrite the GUI from scratch in a different framework (although we are always open to a contribution or poc) so we need to think about what parts of the GUI can be improved incrementally.

I am not very familiar with the frameworks you mentioned are they compatible with react? Are they more about layouts css and styles?

**Comment by q2dg** [comment]
Yes, it is compatible with React: https://www.patternfly.org/v4/get-started/develop ... but it just was a simple suggestion...
What I mean is that I see buttons and comboboxes like if they were very "2000's", aesthetically speaking. It seems (for me, at least) that web UI components are vintage. But surely I'm talking nonsense...feel free to close this issue if you consider.
Thanks a lot

**Comment by scudette** [comment]
Reading more about patternfly it seems to be a modern extension to bootstrap. We currently use react-bootstrap everywhere and it seems to be possible to migrate to patternfly without too much trouble (see this https://github.com/theforeman/foreman/pull/6394/files for example).

It is still not trivial since all the themes need to also be ported over and maintain look and feel. 

If we just want a better look and feel and styling maybe we can just create a new theme and add css to emulate the components? 

The default theme is the standard bootstrap theme (as you say looks 2000's) but the other themes are pretty modern looking actually. (I like the velociraptor light) 

Can we maybe just introduce a new theme to emulate the look and feel?

**Comment by scudette** [comment]
I actually quite like their modal components https://www.patternfly.org/v4/components/modal and especially the wizard component is quite nice looking.

it seems to be possible to mix and match between react-bootstrap and patternfly-react so we can just incrementally upgrade components - this is good. Definitely worth a try i think :-) 

Thanks for suggesting.

**Comment by scudette** [comment]
This is probably not a priority now - feel free to send a PR if you think it will improve the UI
