### ISSUE TITLE
Unable to upload zip file from offline collector

### ISSUE THREAD

**Issue by OldToys** [Velocidex/velociraptor#2035]
Hello,

I am new to Velociraptor. I ran an instant instance on my Windows machine, created a collector and ran it on a Windows machine. I got a ~190 MB password protected zip file that I am trying to upload to the "View Artifacts" section, but I keep getting the error below:
![image](https://user-images.githubusercontent.com/25939712/187557271-6029a2af-f126-4698-87e7-86e1166cdf39.png)
I even extracted the zip file, and tried to upload data.zip, but I keep getting the same error.
Any recommendations. I looked up the documentation but could not find anything related to this specific error.

**Comment by scudette** [comment]
Also you normally need to unzip the password protected file with 7z for example then you have to place the data.zip file on the server somewhere eg with scp.

Then you need to give the location of the file to the Server.Utils.ImportCollection artifact see here https://docs.velociraptor.app/artifact_references/pages/server.utils.importcollection/

The GUI does not support uploading the zip file because it is normally huge and needs to be transferred via a more reliable method.

**Comment by OldToys** [comment]
Understood. I am exploring the option to use Server.Utils.ImportCollection. I will let you know if I run into any issues. And thanks a lot for the quick reply.

**Comment by scudette** [comment]
This should be solved now. Please reopen you still need help...
