### ISSUE TITLE
Initial server artifacts for new orgs are created in the root org

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#2050]
When creating a new org the `default_client_monitoring_artifacts` and `default_server_monitoring_artifacts` are "cloned" as expected in the new org. However the `initial_server_artifacts` are re-run in the root org and not in the new org.

**Comment by scudette** [comment]
This is a good observation but I'm not sure of the use case. Normally the initial artifacts are run when the server is installed to reload new artifact definitions etc

But when creating a new org is just as easy to just run whatever artifacts inside the new org as part of the preparation step. We don't need to load custom artifacts because orgs can see all the artifacts in the root org anyway.

It's just as quick to just write some vql to create the org then run whatever inside it.

**Comment by predictiple** [comment]
I get your point and agree that such artifacts can be run manually in each org if needed. So the issue is perhaps that the initial server artifacts _shouldn't_ re-run when new orgs are added. I have 1 such artifact and the copies that are created along with new orgs also don't complete - no logs are generated for these new flows. So something weird is going on.

**Comment by predictiple** [comment]
Stranger too is that these additional server flows don't time out even though the limit is 600 seconds.

**Comment by scudette** [comment]
Fixed in #2052

**Comment by predictiple** [comment]
Thanks very much! I've retested and the fix resolves this issue.
