### ISSUE TITLE
Feature Request: Format Option for Local Collection

### ISSUE THREAD

**Issue by prolsen** [Velocidex/velociraptor#210]
When performing a local collection/s3 and/or a gcp upload is it possible to _not_ have both the csv and json files uploaded by default?

For data transfer/size purposes, having something where we can specify only a single output format to be collected/uploaded would be great.

autoexec:
    argv: ["artifacts", "collect", "-v", "--format=jsonl", "UploadToS3"]
    artifact_definitions:
      - name: UploadToS3
      <snip>

Then _only_ have the .jsonl formatted files uploaded where as now you get the json and csv files uploaded.

Another option:

autoexec:
    argv: ["artifacts", "collect", "-v", "--format=jsonl,csv,json", "UploadToS3"]
    artifact_definitions:
      - name: UploadToS3
      <snip>

Then have the .jsonl, csv, and json files collected/uploaded.

**Comment by scudette** [comment]
Are you talking about the JSON files **inside** the produced ZIP file or the output emitted by the **artifacts collect** CLI command?

The ZIP file is produced by this code:
https://github.com/Velocidex/velociraptor/blob/cc8ea95efeba26f1534b83577c44bb4841aa3a45/reporting/container.go#L79

And it always outputs both JSON (not jsonl) and CSV.

This is actually less than ideal because in order to produce both files it has to queue up **all** the rows in memory. In the case of a large query like dumping the MFT this could be a lot!

Ideally we would only write one format at a time. We would also need to pass the desired format to the collect() VQL function here:
https://github.com/Velocidex/velociraptor/blob/cc8ea95efeba26f1534b83577c44bb4841aa3a45/vql/tools/collector.go#L15

Also BTW there is a new command to just stream CSV files from within a zip file in any format you like (including jsonl):
```
velociraptor unzip --csv H.XXXXX.zip "All Some Artifact.csv" --format jsonl
```

So we dont really need to write multiple formats for the same output anyway since it is easy to convert from one to the other.

**Comment by prolsen** [comment]
Was talking about this situation where it would upload both the csv and json of the process listing so it would be nice to have a --format=json (or whatever the format of choice) and that's the only file uploaded inside the data.zip

Hopefully this is more clear.

```
autoexec:
    // Current
    argv: ["artifacts", "collect", "-v", "UploadToS3"]
    // Proposed
    argv: ["artifacts", "collect", "-v", "--format=<format_of_choice (json, csv, or jsonl)>", "UploadToS3"]
    artifact_definitions:
      - name: UploadToS3
        parameters:
           <snip>

        sources:
           - queries:
                - LET hostname <= SELECT Fqdn from info()
                - SELECT upload_s3(
                     file=Container,
                     bucket=S3bucket,
                     region=S3region,
                     name=format(format='%s-%s.zip', args=[hostname.Fqdn[0], timestamp(epoch=now())]),
                     credentialskey=S3Key,
                     credentialssecret=S3Secret) AS Uploaded
                     FROM collect(
                      artifacts=[
                        "Custom.Windows.Sys.ProcessListing"
                        ],
                     password="mehmeh",
                     output=tempfile(extension=".zip"))

**Comment by scudette** [comment]
Yes that makes sense. Try out the CI build to see if it does what you want

**Comment by scudette** [comment]
Just to clarify you will need to provide the desired format to the collect() vql plugin. If you dont it will use the default (which is jsonl)
```
- SELECT upload_s3(
                     file=Container,
                     bucket=S3bucket,
                     region=S3region,
                     name=format(format='%s-%s.zip', args=[hostname.Fqdn[0], timestamp(epoch=now())]),
                     credentialskey=S3Key,
                     credentialssecret=S3Secret) AS Uploaded
                     FROM collect(
                      artifacts=[
                        "Custom.Windows.Sys.ProcessListing"
                        ],
                     password="mehmeh", format='json',
                     output=tempfile(extension=".zip"))
```

**Comment by prolsen** [comment]
Tested and appears to be working. Thanks!

**Comment by prolsen** [comment]
Tested and works. Thank you!
