### ISSUE TITLE
Feature Request: Add Autoruns artifact for Mac

### ISSUE THREAD

**Issue by mpilking** [Velocidex/velociraptor#219]
Generally speaking, it would be great to have some triage artifacts dedicated to macOS.  I've been looking at several projects with IR scripts for Mac and I believe "AutoMacTC" from CrowdStrike would be a nice one to emulate in Velociraptor--or perhaps even deploy it as-is to run via VR, especially since all its output is CSV (or JSON).  

Here's a blog article on the project: https://www.crowdstrike.com/blog/automating-mac-forensic-triage/ and here's the Github repo:  https://github.com/CrowdStrike/automactc.

If you were to pick just one script to emulate as an artifact, I would suggest Autoruns (https://github.com/CrowdStrike/automactc/blob/master/modules/mod_autoruns_v102.py).  It nicely lists autostart processes, along with timestamps, autostart mechanism, code signatures, and hashes.

**Comment by scudette** [comment]
This is now implemented as #223 You can test by downloading the darwin binary from #225 

https://github.com/Velocidex/velociraptor/suites/409748101/artifacts/1224264

**Comment by mpilking** [comment]
Wow, that's awesome Mike! Thank you! 

This is a great start, but I tested it on a Catalina Mac OS system and I noticed a few useful features included in the AutoMacTC output that were not in the VR artifact output.  Specifically, the artifact results do not have all the timestamps from the binary (only the Mtime), the binary hash value is blank, the command line arguments are not included, and there is no check of the digital signatures.  These would all be pretty useful additions.  Is it feasible to add them? 

I've included a zip with the VR autoruns collection and a gzip of the AutoMacTC autoruns collection on the same test machine for comparison.  Specifically I was comparing the LaunchAgentDaemons.csv artifact file (the others have even less information collected).

[automactc-output,mac1.tar.gz](https://github.com/Velocidex/velociraptor/files/4089200/automactc-output.mac1.tar.gz)
[F.BOJ23H4KS0QDO.zip](https://github.com/Velocidex/velociraptor/files/4089201/F.BOJ23H4KS0QDO.zip)

Thanks,
Mike

**Comment by scudette** [comment]
Which binary hash are you referring to? For example here is a line from your output (from the LaunchAgentsDaemons.csv) - you can see all the information is in there (quite a bit more info):

```
/System/Library/LaunchAgents/com.apple.mdworker.mail.plist,2019-11-13T04:59:50Z,"{
 ""CFBundleIdentifier"": ""com.apple.Spotlight"",
 ""EnablePressuredExit"": true,
 ""EnableTransactions"": true,
 ""EnvironmentVariables"": {
  ""MallocCorruptionAbort"": ""1""
 },
 ""Label"": ""com.apple.mdworker.mail"",
 ""LimitLoadToSessionType"": ""Background"",
 ""LowPriorityBackgroundIO"": false,
 ""MachServices"": {
  ""com.apple.mdworker.mail"": {
   ""ResetAtClose"": true
  }
 },
 ""MultipleInstances"": true,
 ""POSIXSpawnType"": ""Interactive"",
 ""ProgramArguments"": [
  ""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker_shared"",
  ""-s"",
  ""mdworker-mail"",
  ""-c"",
  ""MDSImporterWorker"",
  ""-m"",
  ""com.apple.mdworker.mail""
 ],
 ""ThrottleInterval"": 1
}",/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker_shared,"{
 ""MD5"": ""fde22e27ddb7b8a5e6a7b18437fc3f47"",
 ""SHA1"": ""0008b89a3c0e85885eacf2f614a28e36444de733"",
 ""SHA256"": ""e0564827c442fc3f2f7161acd8b5adf8ec5d04345813c39a88caf5c4e2023007""
}",
```

You can see both the command line is given (as a list of argv) as well as the hashes of the binary. 

A major difference is that Velociraptor also captures the actual files/binaries in the zip file (including the plist files so you can parse them offline). You can use the --output parameter to store everything in a zip file. Also if you emit the output in json format (--format jsonl) you can use something like jq to see the output a bit better.

For us to verify the signatures on the binaries we need to write some OSX specific code (i.e. use the API) so a simple VQL is not enough for that. Since we get a copy of the binary this is probably more trustworthy anyway (not sure if MacOS can add a malicious root cert). 

There seems to be also some trouble parsing the "Alias" field of the launchd config which seems like its an encoded binary field (I had a quick look at osquery uses the API to parse it).

The artifact is a starting point - you can add other fields very easily by changing the VQL (e.g. add ctime etc).

**Comment by mpilking** [comment]
Thank you for the clarification. I was using an external viewer that did not show the full contents of the fields.  My mistake.

Regarding the signatures, my preference would be to have the option to calculate them on the endpoints to avoid bringing them all back to a central server, at least for an initial pass at the analysis.  But I also understand the point about not necessarily trusting the certificate store of the remote hosts.  

Thanks for implementing this so quickly.  Very nice!

**Comment by scudette** [comment]
I think we can close this one for now. Lets open another issue if we have something more specific to implement.
