### ISSUE TITLE
Yara 3 pe.number_of_signatures invalid field

### ISSUE THREAD

**Issue by ag-michael** [Velocidex/velociraptor#2276]
Hi Velocidex team,

I am having trouble with a rule set that includes Yara3 fields, the error has to do with `pe.number_of_signatures`:

```
Failed to initialize YARA compiler: invalid field name "number_of_signatures" 
```
Does this have to do with lack of Yara3 support or is there something more to it? Can you help find a solution to this?

**Comment by scudette** [comment]
We currently only support yara 3.11. It might be that this is a feature in yara 4. 

The reason why it is hard to go to yara 4 is because of the large number of extra dependencies it introduces including openssl and other features. We update the yara engine to get it to build statically with minimal dependencies:

https://github.com/Velocidex/go-yara/blob/master/update.sh

You can get all the pe functionality in VQL anyway so it is not super critical to have yara 4.

**Comment by ag-michael** [comment]
@scudette  Thanks for the fast response. 

When dealing with a large set of rules that update automatically from a 3rd party, it becomes difficult to figure out which ones work and which ones don't. I will try to  parse/compile my rules with yara 3.11 and expose to Velociraptor only the ones that don't have errors.

However, is it difficult for Velociraptor to process rules it can and skip the error generating rules instead of an all-or-nothing failure? It is especially difficult when using a URL because you have to put a lot of rules in one "file".

**Comment by scudette** [comment]
I have this quick script that parses the yara rule and breaks it into parts 

https://github.com/Velocidex/yara-tools

We could change it such that it can rejects rules that dont compile automatically. Currently it is not trying to compile the rule, just remove all the extra unnecessary things from it but we can easily call the yara library to try to compile each rule

**Comment by ag-michael** [comment]
@scudette Thank you, I'll close this issue and try that. My effort to parse+compile in python and only let Velociraptor deal with good rules have failed (`Unknown module 'hash'` is the error now even though yara-python==3.11.0 compiles it fine).

**Comment by scudette** [comment]
Yes I think we disable the hash module in yara 3.11 even because it brings in the entire openssl dependcy. I will modify the other script to parse the rules that are compatible. Since that is in go and will use the exact library that velociraptor uses then it will be accurate in rejecting the rules that don't work.

**Comment by ag-michael** [comment]
@scudette  Thanks very much, I appreciate your work.

**Comment by scudette** [comment]
Just circling back on this issue. I have now pushed the update to yara 4.2.3 in Velociraptor.

Even in this latest version, the pe.number_of_signatures field is only included with the openssl dependency which we do not include due to size and security reasons. Therefore in Velociraptor that field is not present in yara pe module and can not be used in a signature. 

I have added the --verify flag to the yara-tools repository https://github.com/Velocidex/yara-tools so it is easy to remove the incompatible rules automatically from the ruleset.

**Comment by ag-michael** [comment]
Thanks a lot @scudette , I will test this today.

**Comment by milkfridge** [comment]
> [@scudette](https://github.com/scudette) Thanks for the fast response.
> 
> When dealing with a large set of rules that update automatically from a 3rd party, it becomes difficult to figure out which ones work and which ones don't. I will try to parse/compile my rules with yara 3.11 and expose to Velociraptor only the ones that don't have errors.
> 
> However, is it difficult for Velociraptor to process rules it can and skip the error generating rules instead of an all-or-nothing failure? It is especially difficult when using a URL because you have to put a lot of rules in one "file".

Yeah, this is an issue for me as I also get rules routinely from 3rd parties that include many of these pe features. Is there a workaround or anything?  It sounds like the only solution is to just to remove the problem rules.  Any newer conversations or plans to re-visit this situation?  Thanks so much!

**Comment by scudette** [comment]
You can now use the yara_lint() function to remove those rules automatically.

**Comment by scudette** [comment]
One possibility is that we add the pe.number_of_signatures field  and just return 0 

This might be a valid solution because the rule will parse ok and actually work but any condition in the rule that relies on this attribute wont work. This is fine because relying on this attribute is kind of pointless and leads to a very fragile rule (attackers can easily remove signatures )

**Comment by milkfridge** [comment]
> Just circling back on this issue. I have now pushed the update to yara 4.2.3 in Velociraptor.
> 
> Even in this latest version, the pe.number_of_signatures field is only included with the openssl dependency which we do not include due to size and security reasons. Therefore in Velociraptor that field is not present in yara pe module and can not be used in a signature.
> 
> I have added the --verify flag to the yara-tools repository https://github.com/Velocidex/yara-tools so it is easy to remove the incompatible rules automatically from the ruleset.

I think I found a bug... The `yara_tool clean` (with or without `--verify`) is breaking on base64 strings like this:

`$s4 = "taco.cat" base64`

This is the error:

`yara_tool: error: Parser result: "1" grammar: lexical error @22: "syntax error: unexpected _IDENTIFIER_, expecting _CONDITION_"`

**Comment by scudette** [comment]
That project is no longer supported - its functionality was replaced with yara_lint() 
https://docs.velociraptor.app/vql_reference/parsers/yara_lint/

**Comment by scudette** [comment]
This behaviour is now in 0.75.1-rc1
