### ISSUE TITLE
Velociraptor endpoint agent doesn't use Trusted Root Certification Authorities in Windows

### ISSUE THREAD

**Issue by oppressed-artist** [Velocidex/velociraptor#2330]
During a recent deployment, my team encountered a scenario involving a MITM proxy performing SSL deep inspection, which is enforced by the organization's policy. Disabling inspection for our Velociraptor server for every new case can be a challenge in terms of the internal processes and would introduce delays, but it can be easily avoided if Velociraptor's client were using local system certificates. Unfortunately, that's not the case. We've successfully tested a workaround: Client.use_self_signed_ssl=false and Client.Crypto.root_certs set to the proxy root certificate solves the "X.509 Certificate Signed by Unknown Authority" error that we get otherwise. Still, it's highly impractical to ask for such with every new environment. And since the certificate is installed and available on the local system, how about making Velociraptor aware of local certs? Could you implement that, please, as it would solve a lot of headaches down the road?

**Comment by scudette** [comment]
This is a deliberate design choice to avoid having velociraptor vulnerable to a compromised root cert store and also because some machines have an out dated cert stored too so we are guaranteed of working on those machines in deployment.

For mitm proxy support you can add the root cert into the client config file here

https://docs.velociraptor.app/docs/deployment/references/#Client.Crypto.root_certs

**Comment by oppressed-artist** [comment]
Could you please explain how it helps? If attackers have control of the endpoint and can compromise the root certificate store, they can probably accomplish whatever they want. Stopping the Velociraptor agent that has to use a proxy to expose the machine for remote investigation steps will not improve the situation in any way. Wouldn't it be best to have a client configuration option that enables the certificate store to be used deliberately for all those scenarios when it could save the day?

**Comment by scudette** [comment]
Possibly. One of the reasons we switched to embedded certs was actually when the let's encrypt root cert expired. Then all the older machines did not contain the be cert and they all broke. It's better to ship with a known set of certs and allow people to add new ones then to depend on system configuration which might be broken.

Are you not able to add root certs at the deployment stage?

We could add an option to allow the client to also delegate to the root cert store in addition to the embedded certs.

**Comment by predictiple** [comment]
One potential pitfall with this idea is that it's proposing Windows-specific functionality which would mean cross-platform inconsistency. Or else the functionality would have to be approximately implemented for each target platform, or at least for the major ones... which leads to more inconsistency because then you'd have add caveats such as "works on most Linux distributions but not all". And then what about FreeBSD? What about X, Y or Z?

This is the reason that web browsers ship their own trusted CA stores - so that they can be platform independent. And that's what Velociraptor is currently doing too.

**Comment by oppressed-artist** [comment]
It doesn't seem to be a contradiction between the certs shipped in configuration and those installed locally - how about a new switch, like "use_local_cert_stores", that would trigger stores search if embedded certs won't cut it?

> Are you not able to add root certs at the deployment stage?

It would force us to acquire the proxy certificate first, which involves additional communication and delay to request a certificate already installed on all the devices on the network where the MITM proxy is used and otherwise could be accessed immediately by the deployed agent.

> Or else the functionality would have to be approximately implemented for each target platform, or at least for the major ones...

How about the code used before switching to embedded certs? It would speed things up if reused in a new context.

> This is the reason that web browsers ship their own trusted CA stores - so that they can be platform independent. And that's what Velociraptor is currently doing too.

That piece would require additional code, but the idea behind "use_local_cert_stores" is precisely that - to query OS cert store AND web browser stores - as far as I see, it could be possible and would also help if the proxy cert would be installed only in a browser.

Yet, I wouldn't implement the feature so extensively at first, and just reusing the old code (if possible) for OS stores would make an undeniable positive impact.

**Comment by scudette** [comment]
Fixed by #2423
