### ISSUE TITLE
MSI v0.6.7-4 has a new Config Path

### ISSUE THREAD

**Issue by joshlemon** [Velocidex/velociraptor#2357]
It looks like the new MSI [velociraptor-v0.6.7-4-windows-amd64.msi](https://github.com/Velocidex/velociraptor/releases/download/v0.6.7-4/velociraptor-v0.6.7-4-windows-amd64.msi) has a different config path set when you install it. The service that's updated when you run this MSI over the top of a previous install updates the path with a different config path:

`"C:\Program Files\Velociraptor\Velociraptor.exe"  --config "C:\Program Files\Velociraptor\/client.config.yaml" service run`

This means the previous file `C:\Program Files\Velociraptor\Velociraptor.config.yaml` no longer works.

**Comment by scudette** [comment]
in 0.6.7-4 we introduced a new way to repack the config file directly in the MSI without needing to rebuild with WIX as before. You can repack the config file directly like this (Even from linux).

```
velociraptor-v0.6.7-4-linux-amd64 config repack --msi velociraptor-v0.6.7-4-windows-amd64.msi client.config.yaml output.msi
```

As such the MSI has changed to be more consistent because we encourage people to repack the MSI at all times with their latest config file (rather than just inherit whatever was there before). 

The MSI we distribute now is actually prepared from the custom.xml wix file here https://github.com/Velocidex/velociraptor/blob/master/docs/wix/custom.xml instead of the previous one here https://github.com/Velocidex/velociraptor/blob/master/docs/wix/velociraptor.xml  so it might be a bit different.

If you repack the client config into the new MSI it should upgrade the old package and install the config file in the correct location.

**Comment by joshlemon** [comment]
It doesn't look like that command is packaging up the config file into the MIS correctly, it's still installing with the default config file.

**Comment by joshlemon** [comment]
It also looks like the command in the default config needs to be updated, as it produces an error if you follow it exactly.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/19796681/210060907-acc4f020-f9c1-46ec-b6c0-7b15a2640c34.png">

Error Produced:
`velociraptor-v0.6.7-4-linux-amd64: error: required argument 'output' not provided, try --help`

**Comment by scudette** [comment]
![image](https://user-images.githubusercontent.com/3856546/210061369-839dfe55-9be9-417f-b37e-43af109cb2dc.png)

**Comment by joshlemon** [comment]
OK, I got that to work on a clean endpoint. But that process doesn't work on an endpoint with Velociraptor already working.
I was trying to update an existing deployment. For reference with anyone else trying to do the same thing, you need to duplicate the existing config so it has the name `client.config.yaml` before you install the new client MSI.

OR

You have to uninstall the existing client before you install the repacked MSI client.

I think the overall update process for endpoints needs a bit of work, it's a little clunky to have to push a new MSI and install over the top of an existing MSI. This really should be part of the admin console so you can just push an update to the clients and it includes any settings changes/updates.

**Comment by scudette** [comment]
This is how MSI works - you need to push a new MSI to upgrade existing MSI. 

What do you mean when you say "you need to duplicate the existing config so it has the name client.config.yaml before you install the new client MSI." Are you saying that during upgrade the new config file is not placed in the correct location?

**Comment by scudette** [comment]
Just replicated an upgrade situation
![image](https://user-images.githubusercontent.com/3856546/210063933-d8192741-fa74-463e-8ec5-6a791c77d0e6.png)

As you can see the old velociraptor.config.yaml is not removed by the MSI because it is technically not part of the MSI at all but it should still be using the client.config.yaml that is installed now and ignoring the old left over config file

**Comment by joshlemon** [comment]
Previous windows deployments needed `C:\Program Files\Velociraptor\Velociraptor.config.yaml`. 
If you only had the config file in the `C:\Program Files\Velociraptor\` location when you do the [velociraptor-v0.6.7-4-windows-amd64.msi](https://github.com/Velocidex/velociraptor/releases/download/v0.6.7-4/velociraptor-v0.6.7-4-windows-amd64.msi) update it stops all clients talking to the Admin server because the new MSI requires `C:\Program Files\Velociraptor\client.config.yaml` to hold the config. 

So if you simply update the MSI via the `Admin.Client.Upgrade` plugin, you lose access to all your endpoints.

**Comment by scudette** [comment]
Just trying to get to the bottom of this issue. 

The old msi creates a service with the commandline
```
 "C:\Program Files\Velociraptor\Velociraptor.exe" service run 
```

Which by default waits until a config file appears with the same name as the binary (but different extension).

The new MSI installs a config file and explicitly directs the service to use it.

On upgrade the MSI recreates the service with the new parameters.

In the below the old service uses the velociraptor.config.yaml file but the new MSI recreates the service with a new command line as well as actually providing the config file. So it should just restart and use the new config file.

![image](https://user-images.githubusercontent.com/3856546/210065587-eaa84fb7-a451-4c89-bc3e-b1fa4ecec801.png)

**Comment by scudette** [comment]
> So if you simply update the (unpackaged) MSI via the Admin.Client.Upgrade plugin, you lose access to all your endpoints.

So this is the issue - If you push the un-repacked MSI as distributed then it will break the currently installed clients because it will wait for a new config file to be dropped overwriting the one that comes with it (which is delibeately invalid to force the client from starting).

I think I see the issue here. A user might be confused following previous procedures here.

I think we need better upgrade documentation for this version specifically.

**Comment by joshlemon** [comment]
Correct. 

I think instead of having a general MSI updater plugin you should create a specific client update plugin that also deals with any other changes from a previous client install (like renaming the config file), along with pushing out the MSI. This could also be helpful in the future if you want to add new changes to the setup of the client.
