### ISSUE TITLE
Common issues (not sure if there is a possible solution to these)

### ISSUE THREAD

**Issue by fixclown** [Velocidex/velociraptor#2371]
Ability to set an expiry/self-destruct time for Velociraptor clients to automatically self-uninstall.

This will ensure that any clients remaining after an engagement ends will have the client service automatically uninstall itself after a set period, so it doesn’t keep “phoning home” to our server.

 

Ability to set/change a “Deployment ID” and only have the server respond to “authorised” IDs.

This would eliminate the issue above of “rouge” clients still being out there, but also would prevent anyone who wants to use the existing MSI package(s) we sent to clients, from being able to contaminate data for a new client (unlikely, but still possible). It would be also nice if each deployment ID could be used to tag/label a client automatically within the WebGUI.

Any help or possible fixes for these issues would greatly be appreciated

**Comment by scudette** [comment]
You can create a client monitoring artifact  that will just schedule an uninstall after a certain time. Since client monitoring artifacts run autonomously (without needing to connect to the server) this will happen regardless of if the server is up or not (assuming the client synced once the client monitoring table).

> Ability to set/change a “Deployment ID” and only have the server respond to “authorised” IDs.

The second use case sounds like you are looking for multi org deployment. Normally the client will only ever talk to clients with a valid client nonce (which corresponds with the org id for this client). Removing the org will stop all communication with those clients.

**Comment by fixclown** [comment]
Thank you so much!
