### ISSUE TITLE
Unable to access systemd files with a C-style escaped file name

### ISSUE THREAD

**Issue by 4ltern4te** [Velocidex/velociraptor#2441]
Ran in to this issue when Velociraptor was trying to upload systemd files.

From the Log tab in the Flow Details window (https://github.com/Velocidex/velociraptor/blob/master/vql/networking/upload.go#L84)
`upload:  Unable to open  /run/user/1000/systemd/generator.late/"""app-geoclue\x2ddemo\x2dagent@autostart.service""":  lstat  /run/user/1000/systemd/generator.late/"app-geoclue\x2ddemo\x2dagent@autostart.service":  no such file or directory
`

File on the FS
```
$ ls -l /run/user/1000/systemd/generator.late/app-geoclue\\x2ddemo\\x2dagent@autostart.service 
-rw-r--r--. 1 user user 474 Jan 24 20:45 '/run/user/1000/systemd/generator.late/app-geoclue\x2ddemo\x2dagent@autostart.service'
$
```

Have been using delve debugger to poke at the issue a little and the relevant path component arrives to the function with additional quoting from somewhere else in the code base I can't find where presently (or I this would be a pull request and not a issue ;) ) which appears to be what is confusing lstat()
```
(dlv) break ./vql/networking/upload.go:84
(dlv) config max-string-len 200
(dlv) p arg.File.Components[5]
"\"app-geoclue\\x2ddemo\\x2dagent@autostart.service\""

# This gets it working
(dlv) call arg.File.Components[5]="app-geoclue\\x2ddemo\\x2dagent@autostart.service" 
```

To hopefully aid in recreation:
OS: Fedora Linux 37 (Thirty Seven)
```
name: Test.Linux.Systemd 
author: alternate
description: |
  Created to hunt a bug with SystemD file names and Velociraptor

reference:
  - https://example.com

precondition: SELECT OS FROM info() WHERE OS = 'linux'

parameters:
- name: LinuxSystemdServices
  default: |
    ["/etc/systemd/system.control/*.service","/etc/systemd/systemd.attached/*.service",
     "/etc/systemd/system/*.service","/etc/systemd/user/*.service",
     "/lib/systemd/system/*.service","/lib/systemd/user/*.service",
     "/run/systemd/generator.early/*.service","/run/systemd/generator.late/*.service",
     "/run/systemd/generator/*.service","/run/systemd/system.control/*.service",
     "/run/systemd/systemd.attached/*.service","/run/systemd/system/*.service",
     "/run/systemd/transient/*.service","/run/systemd/user/*.service",
     "/run/user/*/systemd/generator.early/*.service","/run/user/*/systemd/generator.late/*.service",
     "/run/user/*/systemd/generator/*.service","/run/user/*/systemd/transient/*.service",
     "/run/user/*/systemd/user.control/*.service","/run/user/*/systemd/user/*.service",
     "/usr/lib/systemd/system/*.service","/usr/lib/systemd/user/*.service",
     "/{root,home/*}/.config/systemd/user.control/*.service","/{root,home/*}/.config/systemd/user/*.service",
     "/{root,home/*}/.local/share/systemd/user/*.service"]

- name: LinuxSystemdTimers
  default: |
    ["/etc/systemd/system.control/*.timer","/etc/systemd/systemd.attached/*.timer",
     "/etc/systemd/system/*.timer","/etc/systemd/user/*.timer","/lib/systemd/system/*.timer",
     "/lib/systemd/user/*.timer","/run/systemd/generator.early/*.timer",
     "/run/systemd/generator.late/*.timer","/run/systemd/generator/*.timer",
     "/run/systemd/system.control/*.timer","/run/systemd/systemd.attached/*.timer",
     "/run/systemd/system/*.timer,/run/systemd/transient/*.timer","/run/systemd/user/*.timer",
     "/run/user/*/systemd/generator.early/*.timer","/run/user/*/systemd/generator.late/*.timer",
     "/run/user/*/systemd/generator/*.timer","/run/user/*/systemd/transient/*.timer",
     "/run/user/*/systemd/user.control/*.timer","/run/user/*/systemd/user/*.timer",
     "/usr/lib/systemd/system/*.timer","/usr/lib/systemd/user/*.timer",
     "/{root,home/*}/.config/systemd/user.control/*.timer",
     "/{root,home/*}/.config/systemd/user/*.timer",
     "/{root,home/*}/.local/share/systemd/user/*.timer"]

sources:
- name: uploadLinuxSystemdServices
  query: |
    SELECT FullPath,
           Mtime,
           upload(file=FullPath) AS Upload
    FROM glob(globs=parse_json_array(data=LinuxSystemdServices))

- name: uploadLinuxSystemdTimers
  query: |
    SELECT FullPath,
           Mtime,
           upload(file=FullPath) AS Upload
    FROM glob(globs=parse_json_array(data=LinuxSystemdTimers))
```

**Comment by scudette** [comment]
Thanks for the detailed reproduction steps 👍🏽 

You are seeing this behavior because your artifact uses the old FullPath column which is deprecated. Recent Velociraptor versions use OSPath which is a well structured path object (instead of a simple string). We use OSPath specifically in order to avoid converting to string and back in a fragile way (and worrying about escapes etc).

I just replaced all FullPath in your example with OSPath and it works as expected

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/218298692-290b58a2-d3de-480d-b73c-9b2a5ca96570.png)

```sql
sources:
- name: uploadLinuxSystemdServices
  query: |
    SELECT OSPath,
           Mtime,
           upload(file=OSPath) AS Upload
    FROM glob(globs=parse_json_array(data=LinuxSystemdServices))

- name: uploadLinuxSystemdTimers
  query: |
    SELECT OSPath,
           Mtime,
           upload(file=OSPath) AS Upload
    FROM glob(globs=parse_json_array(data=LinuxSystemdTimers))

```

**Comment by scudette** [comment]
Just to further explain how this works - Velociraptor internally treats all paths as a list of string components. There are no restrictions on the types of characters in each component. When serializing to string we need to ensure that what we serialize can be parsed again into a list of components. Velociraptor uses a kind of encoding scheme which guarantees serialization is reversible - it does this by appending quotes around components that should be escaped so it can parse out the whole thing and preserve the component. 

Here is an example of a valid path with separators in it (note the last component is a registry value and has forward slashes in it ...)
https://github.com/Velocidex/velociraptor/blob/a6353f81d2ff5e8e5d808265488ff6fd02e3a530/utils/path_test.go#L31

If we blindly split this path on "/" we would split the last component into multiple directories (or registry keys) which is wrong! so Velociraptor represents this path with quotes around the last component to mark it as a single component.

There are many cases where path separators are valid inside a filename - which if we didn't properly protect it we would parse the string incorrectly again. This is why we try very hard not to get into this situation in the first place, and just pass the full list of components around. You can see this effect here

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/218299067-fb044eca-6ae6-41af-8479-cc9044a9c32e.png)

This is why you see the additional escaping when converting the pure OSPath (the list of components) into a string.  The FullPath column is a backwards compatible string representation of the path.

But if you pass the FullPath back into a function that needs a path then it will need to parse the string back into a list of path components. But it does not really know who actually serialized it? it is a special Velociraptor serialization or a normal linux path with quotes around it? There is really no way to tell....

This is why must always pass the OSPath into functions:

1. Avoid ambiguous serialization and parsing of paths
2. Much faster because we don't need to constantly split and join the paths - OSPaths are just passed by pointer to each function and this is very cheap.

**Comment by 4ltern4te** [comment]
Crikey such a quick response. Thanks for much for the explanation and the help, very much appreciated!
