### ISSUE TITLE
Feature Request: External Tool download support via local network options (e.g SMB/NFS)

### ISSUE THREAD

**Issue by nsanity2097** [Velocidex/velociraptor#2458]
When using external tools, some environments may have restrictive proxies or outbound web access blocked during an incident - a method to reduce wan traffic which may be on an alternative connection.

VR already supports the option to repoint client aquisition of external tools via direct links OR pulled from the VR server - but this is currently limited to HTTP. Is it possible to add support for SMB/NFS (depending on native client OS - altho most linux distro's come with smbclient at this point).

Mike has suggested that having VR interact with SMB on some level may provide other peripheral benefits for other functions.

**Comment by bpmorris22** [comment]
In a similar vein I would like to see the VR agent be capable of obtaining download content from peer agents, yes like SCCM... It would be great if the agent or nominated agents spin up a python web server to share tools that have already been downloaded to that client's cache. If security is a concern that have the webserver auth the VR cert. From that point clients can just ask for a list of clients that have previously been targeted by the same hunt, ordered by uptime, online status and agents in the same subnet.

**Comment by scudette** [comment]
Peer to peer communication opens up a whole slew of issues around opening listening ports, firewall allow listing etc. Maybe an option for an additional means of communication but it needs careful consideration.  Considering that third party tools are not really considered a primary use case but more of a workaround limitations in VQL I am not sure how much effort we want to give tool download?

We do have local tool caching so that download speed may not be an issue in practice.

**Comment by scudette** [comment]
Fixed by #2635 to allow everywhere that can take a URL to use SMB as well. 

The URL form should be e.g. `smb://username:password@192.168.1.1/Share/Filename.exe`

We only support shares with passwords so you will need to create the share as per https://docs.velociraptor.app/docs/offline_triage/remote_uploads/#smb-share and set the user to be read only.

Due to limitations in the URL format the password can not be too complicated with special characters, just make it as long as needed.
