### ISSUE TITLE
Custom exclusions

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#2495]
One of the challenges i the current Qarantine content is custom exlcuions or a custom configuration is a manual process to apply as we cant configure the default ipsec configuration centrally.

I would like to have a way to apply custom qarentine policy with a single server configuration.

Use cases may be: IP/subnet and or port exclusion, Removing DNS etc etc.

**Comment by scudette** [comment]
This may incidentally have been fixed with #2494 does it solve your need?

**Comment by scudette** [comment]
One of the main limitations though is knowing when the data is changed - the server metadata is considered when the artifact is compiled - so for Windows.Remediation.Quarantine this happens when it is collected but for the event one it happens only when it is inserted into the event table so we might need to rebuild the event tables when server metadata is updated (probably does not happen too often so its fine).

**Comment by mgreen27** [comment]
I think so. 
I think we would also need a monitor on the quarantine config metadata so on a change it would also rebuild the event table.

**Comment by scudette** [comment]
Should be fixed in 0.6.8-2 - now the event table is recomputed when server metadata is updated as well
