### ISSUE TITLE
Unable to load config file: yaml: invalid trailing UTF-8 octet

### ISSUE THREAD

**Issue by cyb3n3tic** [Velocidex/velociraptor#2507]
Hi,

I am trying to repack the msi with the config file I had created on an Ubuntu server but getting the error as below, any suggestions? I have examined the config and can't see any obvious issue but I'm fairly stupid so....

error: config repack: Unable to load config file: yaml: invalid trailing UTF-8 octet

Thanks in advance.

**Comment by scudette** [comment]
Can you make sure that the configuration file does not have incorrect utf8 encoding?

**Comment by scudette** [comment]
Actually there was a discussion like this on discord

https://discord.com/channels/624244632552734750/624244632552734752/1073025088275894272

I think the issue was that the version was earlier than 0.6.7-4

https://cdn.discordapp.com/attachments/624244632552734752/1073041597568135238/Win_Server_2019.png

**Comment by cyb3n3tic** [comment]
Thanks, version mismatch seemed to be the cause indeed
