### ISSUE TITLE
Numbers in artifact names

### ISSUE THREAD

**Issue by mdenzel** [Velocidex/velociraptor#2518]
Hello,

I found an issue with the naming of artifacts.

It seems like numbers are allowed at the beginning but cannot be called.

E.g. consider the following artifact:
```
name: Custom.01_Recon.Test
description: |
   None

type: CLIENT

sources:
  - name:  Test
    precondition:
      SELECT OS From info() where OS = 'windows' OR OS = 'linux' OR OS = 'darwin'

    query: |
      SELECT * FROM info()
      LIMIT 10
```

I can create it, but if I call it, I get the error message "Error: 2:21: unexpected token ".01"":

```
SELECT *
FROM Artifact.Custom.01_Recon.Test()
```

This can be mitigated by calling:
```
SELECT *
FROM Artifact.Custom.`01_Recon`.Test()
```

I also had problems with calling sources directly. The following did not work in version 0.6.7. but now seems to work:
```
SELECT *
FROM Artifact.Custom.`01_Recon`.Test(source="Test")
```

Is this intended behaviour? Or is there a parsing error?

**Comment by scudette** [comment]
It's not a parsing error I don't think. Identifiers can not start with numbers.

Maybe the GUI should prevent that kind of name to be used?

It's actually quite ok to use back ticks to refer to identifiers that are named in a difficult way (eg have a . In them etc). But I think we do try to sanitize the artifact name somehow.

So I think we to catch this case in the name check and reject it just for the sake of making it easier

**Comment by mdenzel** [comment]
Numbers are useful for ordering. E.g. when using the cyber-killchain or mitre for artifacts, one does not want lexicographical ordering (Killchain: `Actions on Objective` would be first instead of `Recon`).

I recommend allowing them. Worst case with escaping/backticks.

Is there a reason why identifiers cannot start with numbers?

**Comment by scudette** [comment]
This is the regex that defines the identifier https://github.com/Velocidex/vfilter/blob/master/vfilter.go#L173

It does not allow a number at the first position which is basically the same as any language I know. The reason why is that it's makes it impossible to distinguish between a number and an identifier otherwise. For example, 0x10 or 1e10might be a variable name. If we allow numbers at the first position (as well as other positions) then 123 can represent a variable name too. This just makes it impossible to parse anything properly so traditionally identifiers can not start with a number. Of course in vql and SQL you can always wrap them in backticks so then they can be anything.

**Comment by scudette** [comment]
In 0.6.8 rc2 which is just out it will refuse to accept an artifact name starting with a number. 

It just makes it easier to just not allow such names than expect people to back tick them all the time. People can always add a letter to the front of the artifact name (eg v for version or whatever)
