### ISSUE TITLE
Security event logs upload to elastic using all available artifacts not working

### ISSUE THREAD

**Issue by Aboalfadl** [Velocidex/velociraptor#2526]
Hello, dears,

I have got an issue with the flow upload, especially when it comes to security.evtx file.
Whatever I'm using:

> - Windows.EventLogs.Evtx
> - Windows.EventLogs.EvtxHunter

The channel of security or all the records in the security event logs doesn't appear and doesn't upload to elastic. However, the artifact collect already the records, and the records can be downloaded as JSON or CSV, but it didn't get uploaded to elastic.

When I tried to upload it manually to the elastic engine, elastic gave an error as an invalid data structure. so please, if there any fix or recommendation to do with the elastic or maybe something else I'm missing, taking into consideration that I used this technique before without modifying anything with the elastic engine, and the records did upload correctly, indexed, and appeared in the kibana dashboard without issues.

Attached also is the flow details logs screenshot as it appeared that "LookupSID: The security ID structure is invalid." using the Windows.EventLogs.EvtxHunter

![SID Structure is invalid](https://user-images.githubusercontent.com/23270623/224578122-8cde1118-0035-4dc2-a128-d08ced6d3028.png)

So please advise.

**Comment by scudette** [comment]
can you show the output of the server event? including logs?
the LookupSID message is not an error - it just comes from the artifact trying to resolve the sid field with the windows api but it is probably null

**Comment by Aboalfadl** [comment]
Do you mean from the server events tab - flow uploads results?

**Comment by Aboalfadl** [comment]
asdasd

**Comment by Aboalfadl** [comment]
I think you are searching about this issue. Please check the attached screenshot for a main reason of faliure:

![failed1](https://user-images.githubusercontent.com/23270623/224580225-a2c4489b-adeb-49e7-9647-3732329eba4b.png)

**Comment by weslambert** [comment]
> I think you are searching about this issue. Please check the attached screenshot for a main reason of faliure:
> 
> ![failed1](https://user-images.githubusercontent.com/23270623/224580225-a2c4489b-adeb-49e7-9647-3732329eba4b.png)

The reason you are receiving the above message is because you are exceeding the default number of fields allowed for an index (`index.mapping.total_fields.limit`).

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-settings-limit.html#mapping-settings-limit

**Comment by scudette** [comment]
it probably doesnt make a lot of sense to blindly upload all artifacts to elastic - you should probably massage the data a bit with custom VQL to upload only the fields you need. Also elastic needs flat data as must as possible so you should also flatten it a bit more.

You can try to comply with ECS this is a good start for elastic.

**Comment by scudette** [comment]
Just for additional information, EvtxHunter just dumps all event logs that match so if your filters are too loose you will dump very many different types of events, which with their own set of unique fields. As elastic by default creates mappings based on the data it sees it will just keep adding more and more mappings and hit the limit you see.

Additionally it is a bad idea to let elastic create mappings automatically unless your filters on evtxhunter are very tight - this is because different events often reuse the same field names in different ways so the first event that elastic sees will create the mapping and the next event that uses the same field will cause an insert error.

**Comment by Aboalfadl** [comment]
> index.mapping.total_fields.limit

Thanks for helping, I just figured out when I searched for the error, and I figured that it's the elastic issue. thanks for helping and advising.

**Comment by Aboalfadl** [comment]
> Just for additional information, EvtxHunter just dumps all event logs that match so if your filters are too loose you will dump very many different types of events, each with their own set of unique fields. As elastic by default creates mappings based on the data it sees it will just keep adding more and more mappings and hit the limit you see.
> 
> Additionally it is a bad idea to let elastic create mappings automatically unless your filters on evtxhunter are very tight - this is because different events often reuse the same field names in different ways so the first event that elastic sees will create the mapping and the next event that uses the same field will cause an insert error.
> 
> This problem is mitigated with the splunk uploader because splunk does not allow automatic index creation so import has to be more deliberate.
> 
> The automatic flow upload to elastric works best for uploading collections with fixed column schema (which are most artifacts actually ). Try to avoid those artifacts with free form output like evtxhunter.

Thanks a lot mike for helping.

**Comment by weslambert** [comment]
> 

Yes, you can increase the limit without re-indexing, however, as Mike suggested, depending on the particular artifact, you may need to modify the artifact data or schema before it comes into the Elasticsearch pipeline to achieve greater alignment and reduce the number of fields necessary so that you avoid field explosion and can act on and review the data in a more unified fashion after ingestion. 

You can massage the data on the Elastic or Velociraptor side. I typically recommend to filter and parse data at the source where possible. With Velociraptor, this may mean just renaming some fields before the data is sent to Elastic, or moving data around with custom artifacts.

**Comment by Aboalfadl** [comment]
I was using this technique for more than 3 years ago, I'm not uploading everything, but at some times, you may find that you investigating in an active directory with +2GB security event logs, and you need just to get the success and failed event ids which will be a very huge number of records.
previously It was working fine without editing the mapping maybe after elastic upgrades, they limit the mapping for each index for performance perspectives.

Here i just edited the settings for each index I need to modify, and it worked fine without issues without re-indexing or cleaning anything.
