### ISSUE TITLE
0.3.9 Missing OSX client

### ISSUE THREAD

**Issue by CR-OmerYampel** [Velocidex/velociraptor#254]
Hey,

The darwin client is missing from the 0.3.9 tagged release https://github.com/Velocidex/velociraptor/releases/tag/v0.3.9 

There are only 6 assets instead of the usual 7

**Comment by scudette** [comment]
Thanks for reminding me - I did not have access to my mac to build it due to traveling :-). 

Just FYI we have macos clients built at head on every commit - simply go to the latest pull request, click the checks tab and download the Artifacts tab on the right - there should be a Binaries.zip which includes all 3 platforms.

The difference between the binaries built at head and the release ones is that the head macos binaries do not include anything which requires C compilers - currently only the yara() plugin I think. (The other architectures are the same as the release).  I think it is possible to get github to build full macos binaries on macos - maybe we need to investigate this option.

e.g. https://github.com/Velocidex/velociraptor/pull/252
