### ISSUE TITLE
Text / Tooltips on left side gutter icons

### ISSUE THREAD

**Issue by Firstyear** [Velocidex/velociraptor#2563]
Currently in the left hand "gutter" there is no tooltips or text to describe each icon. This makes it harder to discover what each item is (and why they may be disabled such as the per-hosh event viewer).

**Comment by scudette** [comment]
There is probably no need to add tooltips when the full name is visible when the hamburger menu is expanded.

**Comment by SBattaglia-R7** [comment]
+1 this request.  Since the menu defaults to the closed state and needs to stay closed so that it doesn't overlap main UI, this would be a helpful way to remember what the icons lead to while getting to know the UI.

**Comment by scudette** [comment]
This is actually quite complex to achieve because the element the tooltip is on is the sidebar which is collapsed. This leads to the usual tooltip we use being clipped. It is probably not worth worrying about it too much because the sidebar already has the description once it is open.

We can certainly add a tooltip to the hamburger icon though.
