### ISSUE TITLE
Auto labeling creation 

### ISSUE THREAD

**Issue by mgdevsoft** [Velocidex/velociraptor#2608]
Hi,
I think that the on the server side a new label should be assigned to each client based on the OS.
So if the client runs Windows a Windows label should be created for that client. If it runs Linux than a Linux label should be created for that client etc.
I know that in most of the plugins there is a check for which type of OS to run on.
But, as the community grows, the risk for mistake will grow with it.
That can simplify and use as a double measure to reduce the problem.

Kind regards,
Gal Miller

**Comment by scudette** [comment]
What do you mean by "I know that in most of the plugins there is a check for which type of OS to run on." ?

Artifacts are collected on the client and the client has no access to labels.

It is true that hunts can target either an OS condition or a label so the OS condition is a bit redundant. So it does make sense to add a label based on OS because then we can simplify the hunt targeting code. It might even make it a little more convenient to combine OS conditions with labels (currently we cant do that).

It is possible to add OS specific labels right now by simply packaging the label in the config file:
https://docs.velociraptor.app/docs/deployment/references/#Client.labels

Alternatively we can just update client labels with a quick VQL query
```sql
SELECT os_info.system AS System, client_id, label(client_id=client_id, op="set", labels="Windows")
FROM clients()
WHERE System =~ "windows"
```

**Comment by mgdevsoft** [comment]
Thanks,
That will work for me.
