### ISSUE TITLE
Shell is not working

### ISSUE THREAD

**Issue by sjosz** [Velocidex/velociraptor#269]
After upgrading from 0.3.9 to 0.4.0 I tried the shell, I know some changes were done but unfortunately the Shell function still does not work on my test-setup:

![image](https://user-images.githubusercontent.com/11965973/76253925-db53e880-624b-11ea-9b58-fd67bd40f8dc.png)

Is there a way to fix this? This feature can sometimes be very helpful!

**Comment by scudette** [comment]
The shell is an execve shell so you need to execute a command (it does not actually attach to the shell or terminal by itself). Every invocation is unique as well so you can not really use variables from one to the next.

![image](https://user-images.githubusercontent.com/3856546/76254742-b8035a80-6298-11ea-9261-3088523f8687.png)

**Comment by sjosz** [comment]
Hmm, strange, I'm still not getting the result from the command when using your command. I verified that the client is online, and even removed the data directory on the server. Is there another troubleshoot step that I can do?

**Comment by scudette** [comment]
are both client and server 0.4.0?

you should be able to see the shell events saved to the journal at /$filestore_path/journals/Server.Internal.Shell/2020-03-09.csv

**Comment by sjosz** [comment]
I don't see those log files unfortunately.

**Comment by scudette** [comment]
Can you access the client otherwise? Can you run the client in debug mode? You should be able to see the request going to it

![image](https://user-images.githubusercontent.com/3856546/76256715-25fd5100-629c-11ea-9410-2a4a368dea16.png)

First you see the query - the session id should be F.Monitoring. Then you see the command ran then you should see it send the results.

**Comment by sjosz** [comment]
On the client it receives the something since the following log event shows up when sending a command.

![image](https://user-images.githubusercontent.com/11965973/76257228-9df25980-6251-11ea-889d-1e21358b16cd.png)

**Comment by scudette** [comment]
No the client reconnects periodically to the receiver so that's the message. Can you collect other things from it. Are you sure you are using the same client's id

**Comment by sjosz** [comment]
I've deployed a new server (Ubuntu 18) and still have the same problem unfortunately. I also deployed a new agent. On the client I don't see the received request and the external command.

And yes I verified that I'm using the same client ID :)

What data can I look at for troubleshooting this?

**Comment by scudette** [comment]
Since Velociraptor just uses files it is very easy to follow how things work and check that things are working step by step.

1. First make sure the client is off and start the shell and send some command.
![image](https://user-images.githubusercontent.com/3856546/76356572-e436de00-6361-11ea-875b-6c7287bf20c2.png)

2. Now check that a message is sent to the client
![image](https://user-images.githubusercontent.com/3856546/76357229-08df8580-6363-11ea-8803-6a177be7c058.png)

3. Now turn the client on and you should see the task is received
![image](https://user-images.githubusercontent.com/3856546/76356791-4394ee00-6362-11ea-8eb0-cb1cce2bd3f5.png)

You should also see the task disappear from the client's task queue

![image](https://user-images.githubusercontent.com/3856546/76356844-56a7be00-6362-11ea-83b9-a1eeee1f1526.png)

4. Now check that the result is sent to the server and written to the journal
![image](https://user-images.githubusercontent.com/3856546/76357036-a4bcc180-6362-11ea-876e-fd6b9d5b42ca.png)

So somewhere along the line yours is failing. If you can talk with the client normally then it should be able to retrieve the task at least. But according to your screenshot it is not getting any tasks?

**Comment by siftuser** [comment]
I'm running 0.3.9.0. I see it working until step 3 ... but there is no folder "Server.Internal.Shell" u/ journals. Attaching the folders under journals

![v-journals](https://user-images.githubusercontent.com/8371690/76440873-79d17c80-63f9-11ea-9432-67df00372dea.png)

**Comment by sjosz** [comment]
Ah, I discovered what I did wrong. I was launching the commands with sudo permissions and I was not running it in the context of the Linux user that was running the Velociraptor server. It works now :)

**Comment by scudette** [comment]
Since we changed the service to run as a non privileged user it causes us
no end of trouble. If you run it a root it will create files that are not
readable by the service and might break the install completely.

In 0.4.0 I tried to make it harder to make that mistake. Velociraptor will
refuse to run as root when installed from the Deb.

**Comment by kerbalette** [comment]
This works for me using cmd.exe /s "dir " running as the account velociraptor is running under

**Comment by siftuser** [comment]
I'm running server as normal user. And clients with root (*nix) / admin (win) privileges. Are you suggesting to run clients also as normal user ? If so, will it allow to collect all artifacts including those require higher privileges such as memory or procdump etc ? thanks

**Comment by scudette** [comment]
No clients have to run as root or system. But the server Deb creates a
local non root user for the server.

**Comment by siftuser** [comment]
Thanks! This is how I'm doing ... appreciate suggestion. 

**Server console**

```
./velociraptor3.9 --config server.config.yaml shell C.***
C.*** (ubuntu.test) >ls
Running ls on C.***
C.*** (ubuntu.test) >

```
**ubuntu CLIENT console**

```
[INFO] 2020-03-12T01:44:12Z Received request: session_id:"/clients/C.***/flows/F.Monitoring" request_id:1 source:"VelociraptorServer" auth_state:AUTHENTICATED task_id:1583977452775050 VQLClientAction:<env:<key:"Argv" value:"{\"Argv\":[\"ls\"]}" > Query:<Name:"$b05e787a182c0849f4fb3937899165f7" VQL:"SELECT now AS Timestamp, Argv, Stdout, Stderr, ReturnCode FROM execve(argv=parse_json(data=Argv).Argv)" > > name:"VQLClientAction" args:"\022\213\001\nfSELECT now AS Timestamp, Argv, Stdout, Stderr, ReturnCode FROM execve(argv=parse_json(data=Argv).Argv)\022!$b05e787a182c0849f4fb3937899165f7\032\027\n\004Argv\022\017{\"Argv\":[\"ls\"]}" args_rdf_name:"VQLCollectorArgs"
[INFO] 2020-03-12T01:44:12Z vql: scope.go:328: Starting query execution.
[INFO] 2020-03-12T01:44:12Z File Ring Buffer: Enqueue {"header":{"ReadPointer":50,"WritePointer":179,"MaxSize":1073741874,"AvailableBytes":121,"LeasedBytes":0},"leased_pointer":50}
[INFO] 2020-03-12T01:44:12Z vql: scope.go:328: shell: Running external command [ls]
[INFO] 2020-03-12T01:44:12Z File Ring Buffer: Enqueue {"header":{"ReadPointer":50,"WritePointer":322,"MaxSize":1073741874,"AvailableBytes":256,"LeasedBytes":0},"leased_pointer":50}
[INFO] 2020-03-12T01:44:12Z File Ring Buffer: Enqueue {"header":{"ReadPointer":50,"WritePointer":491,"MaxSize":1073741874,"AvailableBytes":417,"LeasedBytes":0},"leased_pointer":50}
[INFO] 2020-03-12T01:44:12Z File Ring Buffer: Enqueue {"header":{"ReadPointer":50,"WritePointer":1703,"MaxSize":1073741874,"AvailableBytes":1621,"LeasedBytes":0},"leased_pointer":50}
[INFO] 2020-03-12T01:44:12Z File Ring Buffer: Enqueue {"header":{"ReadPointer":50,"WritePointer":1777,"MaxSize":1073741874,"AvailableBytes":1687,"LeasedBytes":0},"leased_pointer":50}
[INFO] 2020-03-12T01:44:13Z Sender: Connected to https://server:8000/control
[INFO] 2020-03-12T01:44:13Z Sender: sent 1555 bytes, response with status: 200 OK

```

**Server console**

```
./velociraptor3.9 --config server.config.yaml shell C.***
C.*** (windows.test) >cmd.exe /c dir
Running cmd.exe /c dir on C.***
C.*** (windows.test) >

```


**Windows CLIENT console**

```
[INFO] 2020-03-12T01:52:05Z Received request: session_id:"/clients/C.***/flows/F.Monitoring" request_id:1 source:"VelociraptorServer" auth_state:AUTHENTICATED task_id:1583977925439028 VQLClientAction:<env:<key:"Argv" value:"{\"Argv\":[\"cmd.exe\",\"/c\",\"dir\"]}" > Query:<Name:"$b05e787a182c0849f4fb3937899165f7" VQL:"SELECT now AS Timestamp, Argv, Stdout, Stderr, ReturnCode FROM execve(argv=parse_json(data=Argv).Argv)" > > name:"VQLClientAction" args:"\022\213\001\nfSELECT now AS Timestamp, Argv, Stdout, Stderr, ReturnCode FROM execve(argv=parse_json(data=Argv).Argv)\022!$b***\032'\n\004Argv\022\037{\"Argv\":[\"cmd.exe\",\"/c\",\"dir\"]}" args_rdf_name:"VQLCollectorArgs"
[INFO] 2020-03-12T01:52:05Z vql: scope.go:328: Starting query execution.
[INFO] 2020-03-12T01:52:05Z Ring Buffer: Enqueue {"item_len":121,"total_length":121}
[INFO] 2020-03-12T01:52:05Z vql: scope.go:328: shell: Running external command [cmd.exe /c dir]
[INFO] 2020-03-12T01:52:05Z Ring Buffer: Enqueue {"item_len":147,"total_length":268}
[INFO] 2020-03-12T01:52:05Z Ring Buffer: Enqueue {"item_len":161,"total_length":429}
[INFO] 2020-03-12T01:52:05Z Ring Buffer: Enqueue {"item_len":994,"total_length":1423}
[INFO] 2020-03-12T01:52:05Z Ring Buffer: Enqueue {"item_len":66,"total_length":1489}
[INFO] 2020-03-12T01:52:05Z Sender: Connected to https://server:8000/control
[INFO] 2020-03-12T01:52:05Z Sender: sent 1427 bytes, response with status: 200 OK
[INFO] 2020-03-12T01:52:05Z Ring Buffer: Commit {"leased_length":1489,"total_length":1489}
[INFO] 2020-03-12T01:52:05Z Ring Buffer: Truncate {"total_length":0}
```

**Comment by scudette** [comment]
You just have to run it as the velociraptor user if you installed from the
Deb. The easiest way is just

$ sudo -u velociraptor bash

Then run whatever you need as that

**Comment by siftuser** [comment]
Thank you again. I have not installed it ... but running directly as a default user (ubuntu) ... do you recommend create deb & install instead ?

**Comment by scudette** [comment]
Will it's fine if you run it manually too. You will have the same problems
if you ever try to run a root and your Ubuntu user can't read those files.

Installing the Deb also adds the service files so it can start on reboot.
In 0.4.0 I changed the /usr/local/bin/velociraptor to be a script that adds
the config file to the environment so you don't have to keep specifying the
config flag. It will also refuse to run if the user does not have access to
the config file.

So it's a bit easier to use but if you are happy to run manually than
that's cool too :-)

**Comment by siftuser** [comment]
- created deb for server v 0.3.9.
- Both server & client are connecting & can run artifacts from the server gui
- netstat shows
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 server:8889         0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:8001          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:8003          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8000          0.0.0.0:*               LISTEN      -
```
- velociraptor@server:~$ velociraptor shell C.***
```
panic: Unable to connect to gRPC server: 127.0.0.1:8001: grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials)

goroutine 1 [running]:
www.velocidex.com/golang/velociraptor/grpc_client.GetChannel(0xc0005363c0, 0x2ad4a20)
	/home/mic/projects/velociraptor/grpc_client/grpc.go:96 +0x1ef
main.getClientInfo(0xc0005363c0, 0x1bcbae0, 0xc0002161c0, 0x0, 0x0, 0x0)
	/home/mic/projects/velociraptor/bin/shell.go:202 +0x57
main.doShell()
	/home/mic/projects/velociraptor/bin/shell.go:220 +0xe7
main.init.18.func1(0x18515f0, 0x5, 0x0)
	/home/mic/projects/velociraptor/bin/shell.go:241 +0x4c
main.main()
	/home/mic/projects/velociraptor/bin/main.go:189 +0x205


```

**Comment by scudette** [comment]
Yeah if you use 0.3.9 you do have to specify the config flag. As I mentioned, 0.4.0 replaced that with a script that preloads the config file in the environment.

**Comment by kerbalette** [comment]
Is this activity logged anywhere? I could not see it in VelociraptorAudit_info.log

**Comment by scudette** [comment]
The current implementation for the interactive shell injects client messages to the client's task queue and redirects the responses to the `Server.Internal.Shell` artifact. You should be able to see what commands any clients ran by monitoring this artifact on the server side.

Since direct injection of messages to the client task queue is not available through the API for obvious reasons, it is not possible to run the `velociraptor shell` command unless you are physically logged into the server machine, and running as the velociraptor user (so you can physically write the tasks into the client's queue).  This necessarily means that we don't actually know who ran the command - the server's ssh logs are probably the best source of information for this. Therefore it is not really possible to audit it in the same way that other server events happen through the audit log (we need to operate through the API to receive the principal's username).

We probably can change the way the `velociraptor shell` command works by exposing something through the API that we can log, but I did not want to do this earlier before we have a sensible ACL model. I dare say this will change soon as the ACL model becomes more mature. The way it works currently we rely on physical SSH access as the ultimate form of access control for doing very sensitive things like the shell.

**Comment by scudette** [comment]
The Shell command has been rewritten to use the new ACL model. Therefore it can only run using the API which mean you *have* to have a valid API client config file. The API config has to have a valid user name and the name must have the "administrator" role. This ensured that only administrators can run arbitrary shell commands on endpoints. (Please note that someone with the "artifact_writer" role as well as the "investigator" role can also run shell commands by simply writing them into an artifact and then collecting those artifacts).

I would highly recommend you protect your private key when generating the API config with a password:

![image](https://user-images.githubusercontent.com/3856546/77710090-d8614200-7018-11ea-8ba3-8ea328c11814.png)

**Comment by siftuser** [comment]
FYI - The above command works for windows client. But does not work for a mac, which used to work for earlier build (without API config). Thanks

**WORKING**
```
version:
  name: velociraptor
  version: 0.4.0
  commit: 865ee47
  build_time: "2020-03-10T22:46:20+10:00"
```
```
MAC) >hostname
Running hostname on C.****

test-MAC
```
**NOT-WORKING**
```
version:
  name: velociraptor
  version: 0.4.0
  commit: 7b7464b
  build_time: "2020-03-25T06:31:44Z"
```
```
MAC) >hostname
Running hostname on C.****

STDERR:
exec: "cmd.exe": executable file not found in $PATH
```

**Comment by scudette** [comment]
Latest release add a bash artifact as well - on Linux simply specify `--type bash`
