### ISSUE TITLE
Windows fuse client broken - (Was help with VFS (fuse))

### ISSUE THREAD

**Issue by siftuser** [Velocidex/velociraptor#274]
any clue - why the api_client from analyst machine is trying to connect on 127.0.0.1:8001 ? while the api_client on the VR server is bound to it's IP (192.168.0.4:8001). And the api_client.yaml also points to 192.168.0.4:8001

```
[WARNING] 2020-03-16T14:01:26Z VFSRefreshDirectoryRequest /: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8001: connectex: No connection could be made because the target machine actively refused it."
[ERROR] 2020-03-16T14:01:26Z Getattr /: -2
```

**Comment by scudette** [comment]
How are you launching the binary? Which flags are you using? 

To use the fuse client you only need to specify `--api_config`

**Comment by siftuser** [comment]
Velociraptor.exe --api_config api_client.yaml -v fuse q: Client_ID

**Comment by scudette** [comment]
You are right - this seems to be a bug. Velociraptor is not honoring the api config's connection string.  Additionally fuse at least on Windows seems not functional currently.

**Comment by siftuser** [comment]
Is there a work around or can the client vfs be mounted on other OS's ? Thank you.

**Comment by scudette** [comment]
The fuse functionality is more of a POC for the API - it is not really that useful in practice. The reason is that it is difficult to control exactly which files will be downloaded from the client and unless you are running on a local network it is not that fast. For example if you view a directory with windows explorer, it will download all files pretty much as it is trying to access them to read their icons! This will start hundreds of collections against the client and refresh all the server data for many files un-necessarily

You can mount the client's VFS in the filestore which will allow you to see what has already been downloaded but not fetch new files. You can do this using standard remote filesystems like webdav or just https. 

Perhaps we need a flag to the fuse filesystem to make sure it does not try to collect new data if we dont want to?

**Comment by siftuser** [comment]
Are you suggesting to use filestore/web gui to collect data than use fuse/api for collection ? Thanks

**Comment by scudette** [comment]
Yes - the fuse program actually tries to refresh directories and download files from the client when they are accessed on the fuse mount and not present on the server. It is a nice toy but in reality you dont really want to download files indiscriminately like that.

You should just collect files using artifacts from the endpoint and then either prepare a download zip to your workstation or mount the entire filestore to browse files individually.

**Comment by siftuser** [comment]
Thank you

**Comment by scudette** [comment]
Sorry - it is still broken :-). I will fix it this week so reopening :-)

**Comment by scudette** [comment]
Fuse have been disabled now as it is deprecated. If you need something like that it is easy to build using the python API.
