### ISSUE TITLE
High CPU usage on Mac OS

### ISSUE THREAD

**Issue by brettfullam** [Velocidex/velociraptor#2808]
I am consistently seeing Velociraptor  0.6.7-4 clients on Mac OS with high CPU usage (99%) when no hunts are running. Any ideas on what the root cause could be?

**Comment by scudette** [comment]
You can collect a profile as described here https://docs.velociraptor.app/knowledge_base/tips/debugging_clients/

**Comment by scudette** [comment]
Please collect profiles as described here https://docs.velociraptor.app/knowledge_base/tips/debugging_clients/

To debug CPU load please also collect CPU profile and queries. Usually high CPU load is the result of collecting heavy queries so it is likely due to suboptimal targeting. 

You can also run a trace now during collections https://docs.velociraptor.app/blog/2023/2023-02-13-release-notes-0.6.8/#tracing-capability-on-client-collections  

That does the same thing as a profile but periodically and automatically.

Another point to look at is the client monitoring queries that may be configured .

You can share this here or send to support@velocidex.com

**Comment by brettfullam** [comment]
I'll need to rerun the sample to make sure the updated data collected is accurate, re-collect profiles with the additional fields for CPU profiles and queries for 6 devices and submit them to the email provided.

Appreciate your help digging into this.

**Comment by scudette** [comment]
This should not be fixed - the Issue was that on macos the gopsutil library was shelling out to external programs - this became particularly bad when cpu limiting a collection because we were shelling out to ps many times a second to measure our process load. 

This should now be fixed on macos where we do not have a good way to measure cpu load - therefore cpu limiting on macos is also disabled.
