### ISSUE TITLE
Enable numeric sorting of columns

### ISSUE THREAD

**Issue by toryc** [Velocidex/velociraptor#2828]
Hi Mike,

Currently column sorting on results tables is lexicographic only. When results include inode, uid, pid/ppid, etc, it would be helpful to have this change to numeric sorting.

![column-sort-markup](https://github.com/Velocidex/velociraptor/assets/6812744/3a4b038f-e744-4a8c-8726-bb947688aabf)

**Comment by scudette** [comment]
The table does sort on numeric values when the column is a number you can easily see it using the following query

```sql
SELECT _value AS X 
FROM range(end=15)
```

![image](https://github.com/Velocidex/velociraptor/assets/3856546/d97f21e9-eb7e-4458-abb0-1dc3a90fe40f)


It looks like you are sorting the Pid column of a PSTree output - this column is a string column actually and not numeric. The reason is that the process tracker needs to indicate that the pid is reused (Windows reuses pid aggressively).

You can read all about it here https://docs.velociraptor.app/blog/2022/2022-08-17-process-tracker/#process-id-reuse

**Comment by toryc** [comment]
This makes sense! Thanks for the explanation.
