### ISSUE TITLE
`flatten` doesn't seem to work with data produced by `parse_binary`

### ISSUE THREAD

**Issue by hillu** [Velocidex/velociraptor#2896]
Consider the following bit of VQL, derived from my (otherwise successful) attempts to analyze /proc/PID/pagemap on Linux systems:

```
-- just a few bytes for parse_binary to chew through
LET data = "AAAAAAAAaaaaaaaaBBBBBBBBbbbbbbbb"

LET t1 =
SELECT
    parse_binary(
        accessor="data",
        filename=data,
        offset=0,
        profile='''
        [
            ["array", 0, [
                ["ints", 0, Array, { 
                    type: "uint64",
                    count: 4,
                }],
        ]]]
        ''',
        struct="array"
    ) AS array
FROM scope()

-- turn array: { ints: [ … ] }
-- into ints: [ … ]
let t2 = SELECT array.ints as ints FROM t1

SELECT * FROM flatten(query={SELECT * FROM t2})
```
Unsurprisingly, `t1` turns out as:
``` json
[
  {
    "array": {
      "ints": [
          4702111234474983745,
          7016996765293437281,
          4774451407313060418,
          7089336938131513954

      ]
    }
  }
]
```
Also, unsurprisingly, `t2` turns out as:
``` json
[
  {
    "ints": [
        4702111234474983745,
        7016996765293437281,
        4774451407313060418,
        7089336938131513954
    ]
  }
]
```
As I understand it, `t2` would be rendered as a table with one heading "ints" and one row which contains the array of four numbers. 

| ints |
|:---:|
| [ 4702111234474983745, 7016996765293437281, 4774451407313060418, 7089336938131513954 ] |

I'd **expect** that `flatten` turns `t2` into a table with four rows, one for each number, like so:

```json
[
  {
    "ints": 4702111234474983745
  },
  {
    "ints": 7016996765293437281
  },
  {
    "ints": 4774451407313060418
  },
  {
    "ints": 7089336938131513954
  }
]
```

| ints |
|:---:|
| 4702111234474983745 |
| 7016996765293437281 |
| 4774451407313060418 |
| 7089336938131513954 |

Unfortunately, this is not the case. The `flatten` plugin does not change `t2` at all.

I am pretty confident that this is a bug because when I do the parsing on a client using `Generic.Client.VQL` and evaluate
```
SELECT * FROM flatten(query={SELECT * FROM source(artifact="Generic.Client.VQL")})
```
in the corresponding notebook, I get the expected result.

**Comment by scudette** [comment]
The binary parser produces objects that look like regular Json when encoded about are actually separate objects with specific behaviour. This is done for performance reasons. For example if we have a large array but we index it then we never parse any of the other members.

Due to that, the flatten plugin might be confused about what to do with this object type ( it's not an array).

You can try to convert it to an array first explicitly with array() or a sub query.

We can look at adding enough array like behaviour to the binary parser so flatten can do something with it too. Or maybe even special case it in flatten.

Tbh I rarely use flatten() because it tends to lose structure of data. So it's only useful at the end for presentation.

The reason flatten works on the source () plugin is because at that point the data is just straight Json arrays and dicts. The source() plugin just reads collected data which is always Json encoded.

**Comment by hillu** [comment]
Thanks for the explanation, on a technical level this makes perfect sense!

Unfortunately, I haven't found a way to make your suggestion using the `array` function work. Replacing the `LET t2 …` line above with
```
LET t2 = SELECT array(a={SELECT array.ints FROM scope()}) as ints FROM t1
```
does not produce anything that `flatten` will handle.

From my point of view as a user of the system, there are a few things that might be easy improvements without breaking anything that isn't broken already:
1. From the documentation and the UI presentation, I had no way of knowing that `parse_binary` (and other functions and plugins?) produces something that superficially looks like structs and arrays but has aspects of lazy behavior.
2. If `flatten` (and possibly other functions) can't deal with the object, they should at least give me an error message instead of silently doing nothing.

Reading your explanation as to why passing the data through the `source()` plugin works, I thought that it might make sense if materialized `LET <= …` expressions had the same effect. The user is already expected to know that `LET <=` trades increased memory usage for reduced execution time, so there should be no surprises there. (It might also be more consistent when `parse_plugin` operates on data that changes between read operations.)

**Comment by scudette** [comment]
Usually we dont really need flatten() instead we use foreach  -for example if you want an int per row:

```sql
-- just a few bytes for parse_binary to chew through
LET data = "AAAAAAAAaaaaaaaaBBBBBBBBbbbbbbbb"

LET t1 =
    parse_binary(
        accessor="data",
        filename=data,
        offset=0,
        profile='''
        [
            ["array", 0, [
                ["ints", 0, Array, { 
                    type: "uint64",
                    count: 4,
                }],
        ]]]
        ''',
        struct="array"
    ).ints
    
SELECT _value AS Int 
FROM foreach(row=t1)
```

**Comment by scudette** [comment]
Probably the issue is that here https://github.com/Velocidex/vfilter/blob/4610600570e49763bbde8c82325ffb40f5cc0dda/plugins/flatten.go#L83

We check for a slice explicitly instead of apply the iterable protocol on the member. The iterable protocol is defined for many array like objects which are not actually slices.

**Comment by hillu** [comment]
Uh, the `items` plugin seems to have the same issue as `flatten`:
```
SELECT * FROM items(item=t1)
```
gives me an empty list.

**Comment by scudette** [comment]
This now works as expected
![image](https://github.com/Velocidex/velociraptor/assets/3856546/94ca31f6-668d-4129-8388-cd7bb22d5e90)
