### ISSUE TITLE
File upload doesn't work with certain special characters in path

### ISSUE THREAD

**Issue by nullifysecurity** [Velocidex/velociraptor#2906]
**Server Version:** 0.6.9

## Details

Hey all,

I was trying to download a file from the Microsoft Edge cache and noticed that Velociraptor wouldn't upload the file. I suspect this is because the path contained certain special characters; to confirm, uploading other files with standard names worked as expected. This was attempted through the GUI using VFS and also the Windows.Search.FileFinder artifact with the file upload boolean checked.

The file path in question is: `C:\Users\REDACTED\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\AC\#!001\MicrosoftEdge\Cache\VFNHZ162\app.26f7a9ee859d588ba37d.bundle[1].js`

When using the Windows.Search.FileFinder artifact, the file is only found after the "#!001" and the "[1]" are removed, e.g. `C:/Users/REDACTED/AppData/Local/Packages/Microsoft.MicrosoftEdge_8wekyb3d8bbwe/AC/*/MicrosoftEdge/Cache/VFNHZ162/app.26f7a9ee859d588ba37d.bundle*.js` which yields one match for the file however still fails to upload.

I also tested this on a local machine with a shorter path such as `C:\Users\Analyst\Documents\#!001\app.bundle[1].js` with the same result.

Unsure if this is an issue with the Velociraptor VFS file parsing, or a limitation of Windows itself when handling file paths with special characters, however just wanted to raise it just in case.

**Comment by scudette** [comment]
Thanks for reporting this. This is an unfortunate remenant of backwards compatibility code. In the distant past we used to use url encoding to encode recursive pathspecs but this is problematic because of issues like this - url encoding is just not reliable enough. We have since moved to an OSPath object that properly encodes paths as JSON objects but there is still some backwards compatibility code in there that tries to detect a URL style path by looking for # (the fragment component of the url).

This is probably a good time to remove this compatibility code because we dont use urls for probably about 4-5 releases now.
