### ISSUE TITLE
SSL error When using Azure SSo

### ISSUE THREAD

**Issue by DM15-3T3RNAL** [Velocidex/velociraptor#2938]
Hi
I am attempting to setup velociraptor using Azure SSO so it can integrate seamlessly with our environment.
I followed the instruction using https://docs.velociraptor.app/blog/2020/2020-08-17-velociraptor-sso-authentication-6dd68d46dccf/

After the setup, i browsed to https://<private_ip>/ (and yes i changed the GUI interface to 0.0.0.0 in the config file)
but i get the "ERR_SSL_PROTOCOL_ERROR" error.
After reading some issues (like https://github.com/Velocidex/velociraptor/issues/2443) , i assume that its because of the reason that i am using an ip address rather then a domain name.
Is there a work  around to make it work with just the ip address?

**Comment by scudette** [comment]
You can not establish a secure connection to an IP address because you can not mint an SSL cert to an IP address. Let's encrypt will not issue a cert for an IP address because it has to prove you own the domain.

It is not supported but possible to use SSO with self signed certs - the configuration wizard does not offer this configuration though - If you choose SSO it will assume you want to use lets encrypt. You can manually set it back to self signed or you can start with a self signed configuration and just add the SSO authenticator instead of the basic one to the GUI section .

**Comment by DM15-3T3RNAL** [comment]
Thanks for the reply
so i guess i will deploy the server again with SSO configuration. Once deployed i will add the "use_self_signed_ssl: true" line under the GUI???

Is that all it?
Sorry if the question is stupid

**Comment by scudette** [comment]
No problem :-)

Just follow the steps for the self signed deployment here https://docs.velociraptor.app/docs/deployment/self-signed/

This will produce a server with self signed certs and basic authentication. Then you just add an authenticator section to that config to replace the basic authenticator. Basically replace this

```yaml
GUI:
  authenticator:
    type: basic
```

With
```yaml
  authenticator:
    type: Azure
    oauth_client_id: XXXXX
    oauth_client_secret: YYYYY
```

With those values of client id and secrets you got from the first example.

You will still get a browser warning because the ssl is not properly secure but you should be able to click through it and still authenticate.

**Comment by DM15-3T3RNAL** [comment]
Thanks again for the reply
much appreciated
at least i made some progress
now i am getting the error of application not configured for multi tenant,...

but this error is probably caused by our IT guys making a mistake while configuring the application(may be wrong redirect url)
gonna contact them and get it sorted :)

![image](https://github.com/Velocidex/velociraptor/assets/58237490/d5b6dc9d-b0e5-44f4-acf8-1cd6f11ca30f)

**Comment by DM15-3T3RNAL** [comment]
Hi
So I have made some progress...
I changed the redirect URI from https://private_ip to https://private_ip:8889/
Now the redirect happens properly
i get the prompt to login using AZURE AD/ OFFICE365

After providing username and password, i get code on my authenticator app
Once i provide the correct code, i get redirected to login again using azureAd/OFFICE365
basically it keeps asking me to login (and do the whole process again) and nothing happens

![image](https://github.com/Velocidex/velociraptor/assets/58237490/9da89a00-3c5f-49b5-baa0-21cbb89691b9)


any suggestions?

**Comment by DM15-3T3RNAL** [comment]
I did add the user using  "velociraptor user add name@companyname.com --role=administrator"

but still same issue

**Comment by DM15-3T3RNAL** [comment]
Hi
Thanks for the reply
I don't really see username in the logs

i see below error thought
 
<img width="950" alt="Screenshot 2023-08-28 154238" src="https://github.com/Velocidex/velociraptor/assets/58237490/11521a50-bdbf-40f5-8d60-6f82b60473cd">

https://login.microsoftonline.com/error?code=900144

**Comment by scudette** [comment]
Try to use a generic OIDC setup instead - it looks like it is failing to get the user data (like avatar etc) - OIDC is more generic so it can support more different types of authenticators.

For OIDC you need 

```
   - type: oidc
      oidc_issuer: This is the url endpoint url without the /.well-known/openid-configuration part
      oidc_name: OIDC
      avatar: https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Openid.svg/1200px-Openid.svg.png
      oauth_client_id: XXXXX
      oauth_client_secret: YYYYY
```

**Comment by DM15-3T3RNAL** [comment]
Seems to be working fine 
you are life saver
I changed the redirect URI in the azure app to https://<ip>/auth/oidc/OIDC/callback

One thing i noticed is that the first letter of the name should be capital.
for instance, if my AD user is as scot.adam@comapanyname.com. 

But in velociraptor you have to add the user as Scot.Adam@comanyname.com. Just something i noticed

Thank you soo much for the help

**Comment by scudette** [comment]
We treat usernames as case sensitive so it has to be exactly the way the auth provider is telling us. It is actually the auth provider that is returning the username and we look for the ACL record based on that. You can see the username in the audit log exactly and should create the same casing username.
