### ISSUE TITLE
HTML-tag like strings are removed from artifact parameter descriptions

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3070]
Previously, strings like "<fjas>" were removed from regexs in the artifact queries in the artifact viewer. This was fixed. However, such strings are still stripped from other strings in the YAML, like parameter description.

**Comment by misje** [comment]
I realise that they are probably removed because these fields go through a Markdown parser.

**Comment by scudette** [comment]
There are actually a couple of things going on here - the first is that as you say the descriptions are markdown but that is fine because markdown does allow HTML tags to be used inside the markdown.

The main issue is that only certain tags and values are allowed in user provided content. The list of tags that are allowed are here https://github.com/Velocidex/velociraptor/blob/21243ad0498e268f76caef9cbc6f966c0fe05a61/reporting/gui.go#L635

Which specifies the policy. This means you can put standard HTML tags like `<h1>`, `<b>` etc but other tags will get stripped out. This is needed to avoid XSS attacks.
