### ISSUE TITLE
[Windows, Yara] Several errors running remote yara rules on Windows client

### ISSUE THREAD

**Issue by mattbrun** [Velocidex/velociraptor#308]
Hello everyone,
I'm new with this project, so first of all thanks for your hard work.
I'm trying to do a memory scan with several yara rules under Windows, but none of my tests pass.
I'm using the `Windows.Detection.RemoteYara.Process` artifact, loading rules from the Internet.
Probably each error should have its own issue, but for now I'm putting everything together.
Here some errors:
1) if I don't specify any process pid, I receive several `vql: scope.go:357: Failed: could not attach to process` and `vql: scope.go:357: Failed: too many scan threads` errors
![image](https://user-images.githubusercontent.com/1902043/79143517-a6dcca80-7dbd-11ea-854a-2353c972db19.png)
![image](https://user-images.githubusercontent.com/1902043/79143570-c116a880-7dbd-11ea-9a24-b648f76d77bd.png)
![image](https://user-images.githubusercontent.com/1902043/79143659-e9060c00-7dbd-11ea-9d20-93168f4303be.png)

2) specifying a process pid (`Notepad.exe`), and loading the complete list of rules from https://github.com/Yara-Rules/rules (a copy of the file [here ](https://gist.github.com/mattbrun/1b575de2b1c82e12606dcad3e3ce0d6a)) I get `vql: scope.go:357: Failed to initialize YARA compiler: syntax error, unexpected ']'`
![image](https://user-images.githubusercontent.com/1902043/79142099-451b6100-7dbb-11ea-833d-9a80e15ffa13.png)
![image](https://user-images.githubusercontent.com/1902043/79142166-5d8b7b80-7dbb-11ea-9b8d-5e13476d0e30.png)
![image](https://user-images.githubusercontent.com/1902043/79142190-67ad7a00-7dbb-11ea-8153-cf9645cf9f1f.png)

3) specifying a process pid (`Notepad.exe`), and getting the yara rule [directly](https://raw.githubusercontent.com/Yara-Rules/rules/b496aadd3099c9d0955685d450b9fd2c871b1ce8/utils/domain.yar) from one of the rules with "]" character, the artifact seems to load the rule correctly, but then it times out even before the given timeout (6000 instead of the default 600)
![image](https://user-images.githubusercontent.com/1902043/79142951-9f68f180-7dbc-11ea-8998-1e22cb5a2fcf.png)
![image](https://user-images.githubusercontent.com/1902043/79143012-bd365680-7dbc-11ea-9afc-92c03dfb0380.png)
![image](https://user-images.githubusercontent.com/1902043/79143046-ccb59f80-7dbc-11ea-8d9c-45b0999760f3.png)
![image](https://user-images.githubusercontent.com/1902043/79143201-18684900-7dbd-11ea-95fa-4728774913d9.png)

Am I missing something?
Is it possible to enable some kind of debug in order to know which rule creates the error in my first case?

Thanks,
M

**Comment by scudette** [comment]
Hi Matteo,
   With issue 1 the query took more than 10 min and Velociraptor timed it out. (you can see the message "Query timed out").

When scanning process memory we currently just call into yara itself to scan process memory so I guess the error messages returned are actually from yara. The could not attach to process error messages are typical for windows when someone (in this case yara but Velociraptor also gets these errors) tried to open a process with SeDebugPrivilege which is not available on all processes - even if you are system level access! (I think idle, system and csrss processes can not be opened from user mode). 

See this https://docs.microsoft.com/en-us/windows/win32/toolhelp/taking-a-snapshot-and-viewing-processes  

>For example, OpenProcess fails for the Idle and CSRSS processes because their access 
 restrictions prevent user-level code from opening them.

With issue 2 you can see that the RemoteYara artifact is limited to 1mb yara files:
https://github.com/Velocidex/velociraptor/blob/master/artifacts/definitions/Windows/Detection/RemoteYara/RemoteYaraProcess.yaml#L79

you can increase that if you want or probably better to just clean up the yara file to remove unnecessary fields like the meta and comments. You should also test the yara file with yarac for syntax errors (the file you posted does not pass due to many other errors).

**Comment by scudette** [comment]
There does not seem to be anything here for us to do.
