### ISSUE TITLE
Encoding and collection output (directory structure)

### ISSUE THREAD

**Issue by reynas** [Velocidex/velociraptor#3166]
Hi

I've been searching for similar issues, but couldn't find one, so I hope I'm not replicating an issue.
When trying to automate the analysis of forensic collections (collected with KAPE), the output structure that KAPE maintains is a big benefit. We wanted to switch to Velociraptor offline collector but we have our worries with the way the output looks and how it can impact analysis.

- Characters are URL encoded so instead of "C\Users\\.NET v4.5" it looks like "C%3A\Users\\%2ENET v4.5"
- the MFT is dumped in a separate directory (NTFS) and not where it is originally located (C:\$MFT)

Is there an option that can be set that can modify this behavior or is this something underlying that is required (that differs from how KAPE handles the output)?

**Comment by scudette** [comment]
Velociraptor represents paths in a very precise way that is guaranteed to be both safe and reversible. To learn more about how paths are represented you can read here https://docs.velociraptor.app/blog/2022/2022-03-21-paths/ 

This means that when we save files into the zip file we need to encode them in a way that is both safe and reversible. Windows cannot encode certain characters in a filename so we must escape them. These characters include slashes, backslashes and leading and trailing . characters

We create the zip path based on the accessor which retrieved the file. Since the ntfs accessor is required to read the $MFT the mft is found under the "ntfs" path and then the device we read from (`\\.\c:` in encoded form, or if this was a VSS the VSS device in encoded form).

The files are kept separated by accessor and device because otherwise we can not include the same file read from multiple devices (e.g. in VSS analysis) or multiple accessors (e.g. file and ntfs accessors).

We treat the files inside the zip collector as a simply bulk data and do not assign any special meaning to metadata, e.g. we do not typically set the zip timestamps based on the timestamps of the original files. All the metadata is found in the json file that comes out of the query.

**Comment by reynas** [comment]
Thanks for the quick and detailed reply!
