### ISSUE TITLE
Better way to manage secrets 

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#3274]
Currently we use server metadata to manage secrets so they don't have to be embedded in artifacts.

The problem is that it's still easy to extract the secrets. in a notebook so it's not really a security boundary.

We need to have a better way to manage secrets in a way that is not easy to extract in a notebook.

**Comment by predictiple** [comment]
It might be best to offload to an open source purpose-built solution such as [HashiCorp Vault](https://github.com/hashicorp/vault). Architecturally this might be a good option because the Vault server can be shared by multiple Veloci servers and located in a more secure environment. They have done all the legwork around managing secrets - obviously scrutinized by a community of security/crypto experts - and their documentation seems really good. Best to not reinvent the wheel.

We could include their client lib and expose it through a VQL function for it like we have for Azure, S3, Splunk, etc.

To avoid a circular problem with storing creds for the Vault we might need to make those settable via the server config rather than VQL parameters.

The existing approach of using server metadata could be retained, but then for high-security deployments we recommend using Vault. For deployments with less stringent security needs the Vault server could run on the Veloci server - they have their guidance for securing it.

**Comment by scudette** [comment]
This is a good suggestion for the actual storing and management of secrets for sure but this issue is not really about that

What we need to achieve here is a dedicated service that answers the question: a user X wants to access secret Y 

The question is actually posed by the vql plugin internally so the secret is never exposed into the vql environment


Currently the secrets are passed as args to plugins, say the upload S3 plugin needs creds so we pass it as an arg.

Before it can be passed to a vql plugin, the secret value is in the vql environment and so for example we can pass it to eg log function to log it or something like that.

So the new proposal is about managing that more tightly.

There will be a central service that controls ACLs to access secrets like user X is allowed to access secret named Y

Then when the user calls the upload S3 plugin they specify the name of the secret which is public say name Y. Then the plugin itself calls into the service with the name of the calling user to asking for the actual secret

The ACL can be controlled with the browser and once added can never be read in the clear again by the user because only plugins are able to call into the service to get the secret.

As an extension we may offer a remote secret management API to retrieve the actual secret as you suggest but that does not change the work we have to do here in Velociraptor. In that case once the vql plugin makes a call into the secrets service, that can be translated to a remote API call to the external service to manage the actual secret.

**Comment by predictiple** [comment]
Thanks for clarifying. Per-secret ACLs would be excellent but it seems like it could be overly complex to manage. A simpler idea would be to just have "secrets access" as a new user permission.

But what you've described above suggests you've thought it through and are probably 1/2-way through implementing it already 
:smiley:

**Comment by scudette** [comment]
Fixed by #3286
