### ISSUE TITLE
Total Client Count is Capped at 10k

### ISSUE THREAD

**Issue by SBattaglia-R7** [Velocidex/velociraptor#3308]
When viewing the Client Search page, I want the Total clients count above the client table to show the full number of clients in my org so that I can validate the expected number of endpoints checking in against the actual number.

The Client table in the UI doesn’t page past 10k entries.  That is a reasonable performance tradeoff with the assumption that most users are not going to browse through that many entires instead of just searching.  But the total number displayed at the top of the table should be the count of all clients registered with Velociraptor.  It's the easiest place to check the total connected client count, especially when the users doesn't have access to the Server Status page.

**Comment by scudette** [comment]
I dont  think this is the case since about 0.7.0 - are you using a current version? 

As you can see here https://docs.velociraptor.app/blog/2023/2023-07-27-release-notes-0.7.0/#enhanced-client-search the search box has no limit now and shows more than 10k clients easily and the table can be paged forward and backwards infinitely (all the way to the end).

**Comment by SBattaglia-R7** [comment]
I'll close this -- We thought this was an issue in the base open source version as well as our hosted version
