### ISSUE TITLE
CPU Limit Percent setting does not work with Sigma artifact

### ISSUE THREAD

**Issue by fukusuket** [Velocidex/velociraptor#3333]
Hello, I found a CPU Limit related issue, so I' ll report it :)

**Describe the issue**
CPU Limit Percent does not work with Sigma artifact.
(I have not confirmed whether this issue is reproduced with other artifacts)

**Step to Reproduce**
1. Place a large evtx file : `C:/tmp/all-evtx/win2022-0-20348-azure` 
     1. (e.g https://github.com/NextronSystems/evtx-baseline/releases/tag/v0.8) 
2. Import the curated Sigma rules by `Server.Import.CuratedSigma` server artifact
3. Collect artifact `Sigma.Windows.Hayabusa.Rules` with following option
    1.  ROOT: `C:/tmp/all-evtx/win2022-0-20348-azure` 
    2. RuleLevel: `All`
    3. RuleStatus : `All Rules`
    4. CPU Limit Percent: `25` 

**Expected behavior**
CPU usage will be less than 25%

**Actual behavior**
CPU usage will be 100% as follows

**Screenshot**
Collect artifact:
<img width="1000" alt="スクリーンショット 2024-03-10 21 30 01" src="https://github.com/Velocidex/velociraptor/assets/41001169/4bd70418-1e6b-4000-9462-9d3d20c18294">
<img width="1000" alt="スクリーンショット 2024-03-10 21 30 10" src="https://github.com/Velocidex/velociraptor/assets/41001169/9986207d-469a-4b11-9765-1958b436951c">

CPU Usage:
![cpu-limit-1](https://github.com/Velocidex/velociraptor/assets/41001169/8b83ca2c-de19-4134-8a59-701b39141c4f)
![cpu-limit-2](https://github.com/Velocidex/velociraptor/assets/41001169/bb0e7445-cddd-432d-a625-35ca42122302)

**Environment**
- OS(client): Windows 11 
- OS(server): Ubuntu 22.04 LTS
- Velociraptor: 0.7.1

Thank you for your time.

**Comment by scudette** [comment]
Thanks for reporting this - I am trying to replicate but not seeing it - can you please confirm in the query log that it is setting the limit properly 

![image](https://github.com/Velocidex/velociraptor/assets/3856546/98d1b06a-15b5-469b-99d8-ba2fc0288d21)

**Comment by scudette** [comment]
Ok I think I understand what is happening - When I dropped the number of CPU in the VM to 1 then the task manager shows 100% use or 0% use because of the way we throttle the CPU - basically the way throttling works is we look at the long term average utilization (moving average) and if the average goes over the threshold we pause the query then resume it when it goes back below the threshold

This means if there is only one CPU we run it at 100% for a while to ramp up the average then pause the query - so the graph looks very choppy. 

As the below shows we overshoot on the up side and then on the downside until the moving average stabilizes. I think this is most noticable when the number of cores is very small just the way averages work.

![image](https://github.com/Velocidex/velociraptor/assets/3856546/287511a5-dba9-4854-8792-9850702fdb05)

After a while we can see it switching on and off but it is really choppy with 1 cpu and does not track 25% very well 
![image](https://github.com/Velocidex/velociraptor/assets/3856546/5cf5f9ac-b0d8-4e57-beef-d1ccefd161e5)

**Comment by fukusuket** [comment]
Thank you so much for quick investigation! This is a screenshot of the log screen.
My environment has 16 cores, but does the reason why the CPU usage is 100% mean that the moving average is being calculated?

<img width="1440" alt="スクリーンショット 2024-03-11 7 25 25" src="https://github.com/Velocidex/velociraptor/assets/41001169/54cdfac4-5263-4eea-bd52-67935403526d">

**Comment by fukusuket** [comment]
@scudette 
I tried several options!
The shape of the graph is slightly different, but as you said, the graph becomes choppy in the middle.  I think this is probably the expected behavior, but I would appreciate it if you could confirm it.

### RuleLevel: `All` RuleStatus : `All Rules` CPU Limit Percent: `25`
![1](https://github.com/Velocidex/velociraptor/assets/41001169/55bf28b2-aa92-4ca3-9365-747e9fbc8b5f)

### RuleLevel: `Critical and High` RuleStatus : `All Rules` CPU Limit Percent: `25`
![2](https://github.com/Velocidex/velociraptor/assets/41001169/958aab4d-f506-4d96-a0e9-4e90343351cc)

### RuleLevel: `Critical and High` RuleStatus : `Stable and Test` CPU Limit Percent: `25`
![3](https://github.com/Velocidex/velociraptor/assets/41001169/c4aa9343-e41e-4342-8624-21ca49654ec3)

**Comment by scudette** [comment]
It is hard to tell - the way throttling works in by pausing the query. We can only pause the query in certain points (basically by intercepting calls to ChargeOp() - which is called by plugins and the VQL engine)

https://github.com/Velocidex/velociraptor/blob/bb90be3c2eea007e16760605635a57e2a8c384cd/actions/throttler.go#L206

So in order for a query to be throttleable it needs to call ChargeOps() frequently enough. It is possible that this query spends a lot of time in functions that do not call this (e.g. NTFS parsing, evtx parsing etc) or in setting up the sigma engine which explains why the cpu load is uncontrolled initially then when the query gets underway it over compensates.

Your graph definitely look like the cpu is controlled after the initial spike so maybe it would work to add a few more ChargeOps() into the sigma engine and the NTFS parsers.

**Comment by fukusuket** [comment]
Thank you for your detailed explanation :) 
I was able to understand the mechanism well. This behavior appears to be intentional, so I will close this issue.
