### ISSUE TITLE
How to Build a Windows server?

### ISSUE THREAD

**Issue by aoao921** [Velocidex/velociraptor#3351]

**Comment by scudette** [comment]
We dont support running a production server on Windows mainly due to performance considerations. It is possible to install a simple test server on windows by simply running the 

`velociraptor install windows_service` 

command. 

https://github.com/Velocidex/velociraptor/blob/2a46b274f41a571fb83172859294e107afff1ef0/bin/server_service_windows.go#L47

Or else you can change the wix files to build a server MSI https://github.com/Velocidex/velociraptor/blob/2a46b274f41a571fb83172859294e107afff1ef0/docs/wix/velociraptor_amd64.xml#L76
