### ISSUE TITLE
Empty client monitoring table results in GRPC size error

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#3376]
I initially thought this was related to #3375 but now I've tested and reproduced this behaviour with versions 0.7.1-2, 0.72-rc1 and the last 2 builds from the CI pipeline.

To replicate:

1) Start in "gui" mode with a fresh datastore.
2) Go to the client's Client Events screen and edit the client monitoring table.
3) Remove Windows.Remediation.QuarantineMonitor and Generic.Client.Stats from the 2 label groups.
4) Try again to edit the client monitoring table, which results in the following error:

`"grpc: received message larger than max (4317412 vs. 4194304)"`

![Screenshot from 2024-03-27 06-38-11](https://github.com/Velocidex/velociraptor/assets/9843422/21e54a0a-97c7-43fe-b79d-a2bf217df136)

![Screenshot from 2024-03-27 06-37-43](https://github.com/Velocidex/velociraptor/assets/9843422/1902a919-09bf-499c-8fde-e668de7a5a49)

![Screenshot from 2024-03-27 07-11-05](https://github.com/Velocidex/velociraptor/assets/9843422/9b5a6d5d-375d-4e7f-bdc2-df332761772d)

**Comment by scudette** [comment]
It looks like when there are no artifacts selected at all the API is called with GetArtifacts with names: [] - which means get all the artifact definitions. This overflows the API call.

The error doesnt actually stop anything (i.e. nothing is broken - the user can still select the group and add an artifact) because we really mean to get no artifact names at all so we probably just want to not call the API at all when no names are selected.

**Comment by predictiple** [comment]
That's interesting.

Yes it doesn't stop anything and it's also possible to add a dummy artifact which does nothing except prevent the error.

**Comment by predictiple** [comment]
Fixed by #3379 

Thanks Mike!
