### ISSUE TITLE
[Feature Request] Add joins to VQL

### ISSUE THREAD

**Issue by angry-bender** [Velocidex/velociraptor#3377]
Hey there,

I know VQL doesn't currently support joins, in favour of making chains in for each loops.

Noting joins (outter, inner, left etc) are a basic foundation of computer science (as is a for each loop), and can be easier to understand than a for each loop in a chain I'm wondering if VQL can look to implement joins?

This could help to simplify the lines of code required for a join in VQL for artefacts, and make VQL a little easier to understand for those coming from SOC backgrounds in SQL, KQL or the various other query languages out there.

**Comment by scudette** [comment]
We don't have any indexes so all join operations are essentially foreach anyway (essentially they will be row scans).

Can you provide some concrete examples where a join will be easier to understand than a foreach?

I actually don't agree with your premise that a join is easier to understand than a foreach (ask any analyst to tell the difference between inner, outer, left, right join etc doubt they will be able to).

 Regular programming languages (eg python, go etc) don't have joins but do have loops which are foreach().

But this is a good discussion and maybe we can develop a set of documentation around translating the different kinds of join to a foreach construct so it can help someone.

**Comment by angry-bender** [comment]
No problem, I'm working on one at the moment which might give a good example of a full outer join, as I need to compare a list of running services against the server client list (or targets) then, where service is not present I'd like to return false or a count of 0. 

I'll grab a snippet from this VQL and add to the issue in the next few days.

I totally understand where your coming from, I too admit I need to look at the Venn diagrams each time I need to do a join depending on what I need (so as not to loose key data). As you've mentioned it's more about having the option to do so than eliminating a for each entirely.

I'm definitely not strong enough in my VQL to provide an example for each type of join. However I thought I'd start the conversation as I'm starting to focus more on Query languages like SQL, SPL, KQL etc I'm finding it harder to come back to a for each and have to "relearn" each time I need to query the outputs from two artefacts to compare. 

Given the increasing use of SEIM platforms in DFIR cases, I thought I can't be the only one having some memory issues switching back to VQL. Recently I'm finding it quicker in these cases to take the data out of VR and process it with sqlite or similar 😊. 

If you like where I find this as a case I can document the use case and the equivalent VQL to keep the discussion open.

**Comment by predictiple** [comment]
If execve() eventually supports stdin and/or input via the [pipe accessor](https://docs.velociraptor.app/vql_reference/plugin/pipe/) then we should be able to build data processing steps/pipelines where external tools (for example [OctoSQL](https://github.com/cube2222/octosql) or [others](https://github.com/multiprocessio/dsq?tab=readme-ov-file#engine), or just plain vanilla sqlite as you mentioned) provide extra functionality such as joins.

That way you wouldn't have to take the data out of Velociraptor when you have an external tool that can do exactly what you want. 

Discussed briefly here:
https://discord.com/channels/624244632552734750/865024982399320114/1220348469500448768

**Comment by scudette** [comment]
Thanks again for asking this question - It is an excellent opportunity to understand exactly what is needed.

Since join operations in SQL essentially are index operations we can not just do them in VQL:
1. We do not have static tables like SQL - all our data comes from plugins which may produce dynamic data at any instance.
2. We do not have a concept of index because data is not static
3. VQL Does not have a query optimizer because there is no way to know in advance what the data looks like - for example should we join the glob() table to the services ? or should we join the services to the glob() output? Which index is smaller? There is just no way to know that.

This means indexes are built on the fly as they are needed and the user has to make the call about which data will be indexed and how.  This is a bit more complicated than SQL but in reality SQL has a lot of implicit assumptions which on large data sets can be just as complicated so I feel that making the user think about their query structure is better than randomly guessing the best strategy by the optimizer (and getting it wrong much of the time).

I took the liberty of trying out some join examples just to get the feel of what a join looks like. I used the example here https://www.w3schools.com/sql/sql_join.asp as a basic test case (but I only have 3 rows).

The main issue here is that JOINs require an index, so we need to build the index in advance of the query, then run the query on it. In VQL the index is provided by the `memoize()` function. Currently the index is in memory which limits the size of the indexed table but there is no reason we can't switch to disk backing on the fly (like we currently do for sorting and grouping operations).

The trick here is to decide which table to index - usually you would index the smaller table and apply the query on the largest table. This is left for the user to decide in practice because they know the kind of data they are looking at. For example if I am enriching an event log with process information I know there are 100k+ event log rows but only say 100 processes - I am going to index the processes.

```sql
LET ProductTable = SELECT *
  FROM parse_csv(accessor="data", filename='''
ProductId,ProductName,CategoryID,Price
1,	Chais,	1,	18
2,	Chang,	1,	19
3,	"Aniseed, Syrup",	2,	10
4, Fruit, 10, 20
''')

LET CategoryTable = SELECT *
  FROM parse_csv(accessor="data", filename='''
CategoryID,	CategoryName,	Description
1,	Beverages,	Soft drinks, "coffees, teas, beers, and ales"
2,	Condiments,	"Sweet and savory sauces, relishes, spreads, and seasonings"
3,	Confections,	"Desserts, candies, and sweet breads"
''')

-- This builds an index of the Category Table on the CategoryID key
LET CategoryLookup <= memoize(
    key="CategoryID",
    query={
      SELECT *
      FROM CategoryTable
    },
    period=10000)

-- This essentially looks up the category ID in the index as it scans each row in the products table
LET JoinedTable = SELECT ProductId,
       ProductName,
       CategoryID,
       get(item=CategoryLookup, field=CategoryID) AS CategoryRow
FROM ProductTable

-- Left Join - returns all Products (left table) even if they dont have a category
SELECT ProductId, ProductName, CategoryRow.CategoryName AS CategoryName
FROM JoinedTable

-- Inner Join - returns all Products as long as they do have a category
SELECT ProductId, ProductName, CategoryRow.CategoryName AS CategoryName
FROM JoinedTable
WHERE CategoryRow.CategoryID
```

Right join is just a left join with the second table so the other versions are quite similar. I am not sure full outer joins are that useful because they produce a huge number of rows (N x M where N is the number of rows in the first table and M in the second).

I think usually JOINs are needed to essentially lookup a value in a table - in the above we want to scan the products table but enrich with the category id in the category table - so it is a lookup operation. That seem more natural to me to think of (as a lookup) rather than as a JOIN. Most programming languages have a hash map structure for quickly looking up a value and this is really the closest analogy.
