### ISSUE TITLE
Notebook: Export and import feature

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#338]
I use Velociraptor across multiple deployments and I really like the idea of a notebook in the Velociraptor GUI. 

I would like to be able to export and import notebooks across sites.

This would enable me to build a standard investigative playbook and pass it to a colleague with them simply modifying the hunt or flow datapoint relevant to their use.

**Comment by scudette** [comment]
Export is not possible - Export to zip. This will also include the JSON file from any query (which is not limited to the 500rows that the GUI is).

Next step is the import...

**Comment by scudette** [comment]
Import a notebook is now possible by simply writing an notebook section in an artifact. This is much more reliable than just importing an existing notebook into a different environment because the artifact notebook can be written to apply to the artifact it collects in a generic way.

Exporting is still useful though so closing this FR.
