### ISSUE TITLE
Bug: BASIC auth does not work on Windows

### ISSUE THREAD

**Issue by YamatoSecurity** [Velocidex/velociraptor#3389]
I am trying to get the server frontend running on Windows with version 0.72 RC1.

I have created `server.config.yaml` with `config generate -i` with the default settings, creating a test user `admin:admin`. However, when I try to log in with a browser it gives the error message `Unknown username` in the Velociraptor console and I cannot login.

I tried the same thing on Linux and was able to log in without a problem so it seems to be an issue when running the server on Windows.

**Comment by scudette** [comment]
This is not likely to be an issue since we use it all the time. Ways to debug:

1. Can you see the errors in the dev console - you should be able to see the authorization header passed in - verify it is base64 encoded admin:admin
2. Check the user account is created correctly on the filesystem - should be in `<datatore>/users/admin.db`
3. Make sure the case is set correctly (0.72 is still case sensitive).

**Comment by scudette** [comment]
Can not replicate - feel free to open
