### ISSUE TITLE
Offline Collector - Pauses for Prompt even when "Pause for Prompt" is NOT selected during Web GUI Config

### ISSUE THREAD

**Issue by secure-cake** [Velocidex/velociraptor#3426]
Utilizing v0.7.1-1, creating a Windows offline collector via the web gui, regardless of whether or not I select "pause for prompt," the config.yaml argv still shows "--prompt," and execution indeed prompts for "press the enter key to end." Manually removing "--prompt" from the config.yaml and repacking does not change this behavior (collector execution still pauses for prompt upon completion). 

We did not encounter this issue when utilizing v.0.7.0-4 with the same configuration options.

**Comment by scudette** [comment]
Thanks for filing this issue. We dont normally use the option any more because by default we always prompt now when directly launched from explorer.

The reason for the option used to be that when distributing the collector for manual collection from e.g. a human, they would normally launch it from explorer and the console box would close immediately so it was hard to see if the collection was successful. However if the collector was pushed to the endpoint with .e.g. an EDR tool then the prompt would prevent the tool from knowing the collection was done - so this option was added to control this behavior depending on the situation.

In recent Velociraptor releases though we specifically identify the case where the console is opened directly from explorer (e.g. by double clicking it or run as administrator) and pause regardless - this is pretty much always what we want because i cant think of a case we want the console box to suddenly disappear before the user can see it.

As such the usefulness of that option is not really high any more so we dont typically bother to set it .

**Comment by secure-cake** [comment]
Thank you for the prompt and detailed response! That makes perfect sense. We generally test the collector via Explorer before proceeding with other distribution/execution methods, so we misinterpreted this change in behavior from previous versions. Thank you!
