### ISSUE TITLE
Running server artifacts from the commandline

### ISSUE THREAD

**Issue by PeterWagenaarNW** [Velocidex/velociraptor#347]
Hello,

I'm trying to setup our velociraptor machines using ansible, which is coming along nicely, but for some small problems. 

One of the things that I come across is that I can't seem to (properly) run server artifacts from the commandline. More specifically, I'm trying to execute `Windows.Utils.DownloadBinaries` directly on the server, to make sure all the required tools are in place for plugin-assisted acquisitions. However, instead of uploading the tools to `public/`, a local folder called `Windows.Utils.DownloadBinaries` is created and the tools are put in there. 

Does it have to do with the fact that I'm trying to run server artifacts from a client?

**Comment by scudette** [comment]
Server artifacts are just artifacts that are supposed to be collected on the server. You can collect them anyway on the commandline and this will just put the output in the zip file as normal.

What you really need to do for the `Windows.Utils.DownloadBinaries` artifact is have the server collect it so it can save the output in the right place etc. So you need to schedule the server to collect it using for example the VQL:

```
SELECT collect_client(client_id='server', artifacts='Windows.Utils.DownloadBinaries') from scope()
```

You can schedule it using the command line or the pyvelociraptor api (with an api key). You will receive the flow id as the response (which you can watch using `SELECT * FROM watch_monitoring(artifact='System.Flow.Completion')`)

![image](https://user-images.githubusercontent.com/3856546/81240055-b7ddcc00-9049-11ea-9eca-2ec9ba9837c7.png)

This is the docs for the collect_client() function. (It is probably not well named because usually the client_id refers to a client but in this case the special client_id "server" is actually the server).

![image](https://user-images.githubusercontent.com/3856546/81240151-f8d5e080-9049-11ea-8f4e-094b21dc68de.png)

https://www.velocidex.com/docs/vql_reference/server/#collect_client

You should be able to see the new collection in the GUI too.
![image](https://user-images.githubusercontent.com/3856546/81240282-4eaa8880-904a-11ea-8607-dc78953cff03.png)

**Comment by yampelo** [comment]
This didnt work for me using the example client from pyvelociraptor

```
|~/pubdev/jupyraptor/jupyraptor
| => tail -n1 vraptor_api.py
run(config, "SELECT collect(client_id='server', artifacts='Windows.Utils.DownloadBinaries') from scope()")
________________________________________________________________________________
|~/pubdev/jupyraptor/jupyraptor
| => pipenv run python vraptor_api.py
["collect(client_id='server', artifacts='Windows.Utils.DownloadBinaries')"]
[{"collect(client_id='server', artifacts='Windows.Utils.DownloadBinaries')": None}]
```

**Comment by scudette** [comment]
If you are running from the API make sure your API key has administrator permissions. You can give the key the right permission using the `acl grant keynam --role administrator` command.

**Comment by scudette** [comment]
Windows.Utils.DownloadBinaries is now removed and not needed any more.
