### ISSUE TITLE
Windows.NTFS.MFT - persist "Resetting NTFS Cache"

### ISSUE THREAD

**Issue by stephenttt626** [Velocidex/velociraptor#3504]
My velociraptor version is v0.7.1-2

When I build an offline windows collector, it stucks or persist with the message "Resetting NTFS Cache".
As a result, it takes very long time to finish the process, please help to troubleshoot, many thanks.

**Comment by scudette** [comment]
This message means the NTFS cache is reset (by default every 30 seconds) so the client can see new data - otherwise it may not notice new files that are written. Probably for the offline collector this does not make sense so you can increase the time by setting the NTFS_CACHE_TIME variable in VQL

We do that in a few artifacts already

https://github.com/Velocidex/velociraptor/blob/ea44269da32ae62cead108bc7dbcc9b34244a260/artifacts/definitions/Windows/Detection/Usn.yaml#L30-L35

Does it solve your issue if you customize that artifact to set a very large number by default?

**Comment by stephenttt626** [comment]
Thanks @scudette.

My offline collector does not contain the artefacts "Windows.Detection.Usn", so I think it is not relevant.
The message should be generated from the artefacts "Windows.NTFS.MFT" and it takes like 4 hours long and timeout.

![image](https://github.com/Velocidex/velociraptor/assets/104184347/19471f2c-4fed-4cb5-ac54-5f5d552a1efd)

**Comment by scudette** [comment]
That's not what I suggested. I suggested you copy that part from the USN artifact into the MFT artifact to see if it fixes things.

You could also try the latest 0.72.3 release where the default cache time is set to 10 min instead of 1 min.

**Comment by stephenttt626** [comment]
Thank you @scudette 

After using the latest 0.72.3 release, the performance of the offline collector are much better and acceptable now.

**Comment by stephenttt626** [comment]
The issue is fixed with latest version.

**Comment by scudette** [comment]
Thank you so much for testing it and reporting the original issue 😀
