### ISSUE TITLE
Quarantine artifact is broken when using wss for comms

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#3523]
The Windows.Remediation.Quarantine artifact assumes http or https urls and does not figure out the correct server check url to verify server connectivity

We need to update the artifact to work with wss

**Comment by predictiple** [comment]
The issue seems perhaps broader than just that one artifact. The http_client plugin can be used directly in an artifact, like with Windows.Remediation.Quarantine, or indirectly [as with the `upload` parameter type](https://github.com/Velocidex/velociraptor/pull/3509#issuecomment-2125790409) or `inventory_get()`.

#3345 tries to solve the issue for `inventory_get()` by substituting 'wss' with 'https' but maybe this subtitution should happen in http_client itself?

**Comment by scudette** [comment]
http_client() does not support the wss protocol anyway.

**Comment by scudette** [comment]
Fixed by #3741
