### ISSUE TITLE
Feature request: Add "metaprogramming" addition of Artifact name for query

### ISSUE THREAD

**Issue by mlucas300** [Velocidex/velociraptor#359]
We have a requirement to add tags to our VQL queries and it would be nice to be able to have an artifact which adds our tag and we can pass through an Artifact name as a parameter, together with our tag. This would return the results of our query plus our nominated tag.

Mike has suggested that something like this would be fairly straight-forward to implement:

SELECT *, dict(foo=1, bar=2) AS Tag FROM Artifact(name=ArtifactNameParam)

I hope I have translated your example properly.

Thanks!

**Comment by scudette** [comment]
Thinking more about this - do you intend for this to be run on the client or the server?

The problem is that when we collect artifacts on the client, we need to compile the artifact into VQL to send to the client. This is because we dont want to rely on the client's own artifact repository (we ignore it) and we need to send the client any new custom artifacts users define on the server. Clients typically do not even parse and load their embedded artifacts at all (they have them embedded because it is the same binary for the client and server but clients dont use that).

So we actually need know which artifacts we need to actually compile and send to the client. Currently we do a static analysis of the artifact queries to figure out dependencies on the server but with meta-programming this is not possible. 

We can add something that works on the server but it can not work on the client. If you need to annotate client artifact results you are better to do it with a server side event query.

**Comment by mlucas300** [comment]
Yes, we need to annotate client artifact results, so we would have to use the server side query as suggested. Do you mean we would do that using watch_monitoring() on the server to wait for the query results and then apply the annotation there?

**Comment by scudette** [comment]
You would `watch_monitoring()` for `System.Flow.Completions` artifact which will tell you when a flow is complete then you just call `SELECT *, dict(...) AS Tag FROM source()` to pull down all the rows of that collection and add a tag.

You may be able to also insert information into the collection itself - simply provide the extra data as a parameter - Velociraptor just packs all the parameters into the query environment but the query wont really use it anyway. This way you can pull that data off in your query above. (Be aware that parameters are pushed to the endpoint so dont put anything sensitive in there).

**Comment by scudette** [comment]
I think this issue is resolved - we probably do not need to do anything more.
