### ISSUE TITLE
Stopping an invalid notebook cell query erases the VQL

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3607]
I've been caught off guard a number of times now that if my notebook cell has invalid syntax when executing, and I'm impatiently waiting for those handful of seconds necessary seconds for the "Edit cell" button to reappear, clicking the stop button destroys all my work since the last query execution. Can we keep the "unsaved" VQL even if it had a syntax error and the user pressed stopped instead of waiting for the edit button to appear again?

**Comment by predictiple** [comment]
One possible solution is to have separate Save and Run buttons. Save should work even if the VQL is incorrect. Often I have needed to go to another cell to copy a snippet while forgetting that I haven't yet run the current cell (because it was still incomplete/WIP), thus losing my changes.

An autosave of the current cell would be ideal.

Some of the button descriptions are also not intuitive, for example this Undo doesn't actually undo anything. It should be labelled Cancel, consistent with the same button in the notebook toolbar.
![Screenshot from 2024-07-11 12-37-48](https://github.com/Velocidex/velociraptor/assets/9843422/b0eccf3b-00c1-4a06-9339-ef6a8973383e)

**Comment by scudette** [comment]
What version are you running? I cant seem to replicate it because the stop button is disabled until the refresh is done.

Looks like that code was updated a  few months ago but should be in the 0.72 releases

https://github.com/Velocidex/velociraptor/blame/5cc893a3e507a271037f7ff32e095a4025ce8af6/gui/velociraptor/src/components/notebooks/notebook-cell-renderer.jsx#L719

**Comment by misje** [comment]
This is the latest release, 0.72.4/d568709. I cannot find a way to reliably reproduce the issue, but it happens on some occasions.

**Comment by scudette** [comment]
This should be fixed in #3613
