### ISSUE TITLE
API certificate issue with https clients

### ISSUE THREAD

**Issue by cynorsense** [Velocidex/velociraptor#3635]
We are trying to connect to velociraptor over api and have used the certificates that the api.config.yaml file provided in the https post header with ssl certs along with username and password of api user with correct role.

We are seeing error : 
SSL Issue: consider using the 'Ignore SSL issues' option
Hostname/IP does not match certificate's altnames: Host: vel.SERVERDOMAIN.com. is not in the cert's altnames: DNS:VelociraptorServer

VelociraptorServer- is the default name of the server. So, we are wondering if its to do with configuring the certificates under API server config section in server.config.yaml 

API:
  hostname: vel.SERVEDOMAIN.com
  bind_address: 0.0.0.0
  bind_port: 8001
  bind_scheme: tcp
  pinned_gw_name: GRPC_GW

-------------Can we add below to use the certificates that are in the api.client.yaml ?--------
  CertFile: "/path/to/your/client_cert.pem"
  KeyFile: "/path/to/your/client_private_key.pem"
  CACert: "/path/to/your/ca_certificate.pem"
  AllowedOrigin: "*"
--------------

FronEnd GUI is working all good as we are using autocert to configure the certificates and working well. But, not API server.

**Comment by scudette** [comment]
When you use autocert with let's encrypt the certs can only be used for port 443. Therefore the API port always uses self signed certificates. This is normally OK because we typically pin the velociraptor CA and certificates to the api client's TLS configuration.

See this line in the sample code:

https://github.com/Velocidex/pyvelociraptor/blob/a7a3fb8467c8fc6740d96d30d4aca3c1731f82f6/pyvelociraptor/client_example.py#L56

```python
    creds = grpc.ssl_channel_credentials(
        root_certificates=config["ca_certificate"].encode("utf8"),
        private_key=config["client_private_key"].encode("utf8"),
        certificate_chain=config["client_cert"].encode("utf8"))

    # This option is required to connect to the grpc server by IP - we
    # use self signed certs.
    options = (('grpc.ssl_target_name_override', "VelociraptorServer",),)
```

The first part, the Velociraptor CA is added as a trusted root so the caller will trust certs signed by it. In the second line we override the target name to accept `VelociraptorServer`. This allows to connect to the API by IP or an alternate DNS name if needed.

Are you writing your own API client code or are you using the sample Python code?

**Comment by cynorsense** [comment]
We are using n8n to connect to the server api. We are not able to send the same message just as python code. 

We tried to use the pyvelociraptor connecting to server and it works fine. But, when we want to connect to api server using n8n http client node it shows error as shown above. May be we need to find the curl command that uses certs with VelociraptorServer in the header along with username and password all in one line. Then import to n8n http node.

**Comment by Genio40921** [comment]
Dg

**Comment by Genio40921** [comment]
Dg

**Comment by Genio40921** [comment]
New

**Comment by scudette** [comment]
Not sure what n8n is but the velociraptor API uses grpc not http so you will need to use a proper grpc client to connect to it.

**Comment by scudette** [comment]
This is not an actually issue with Velociraptor so closing.
