### ISSUE TITLE
Some links break if org_id value is enclosed in quotes

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3670]
If the org_id URI parameter is enclosed in quotes, everything looks mostly normal. However, links to flows and downloads, for instance, do not work. The username is also not suffixed by the org. name. If the quotes are removed, everything works as expected.

Why quotes? There is no other way to refer to the root org with the org_id parameter (or so I was told), making it hard to build references/links in artifacts for any return value from org() (including the root org., which is an empty string).

I suggest ignoring the quotes in org. IDs in URIs, alternatively handle "org_id=" without redirecting back to the previously visited non-root org. (which appears to be the current behaviour).

**Comment by scudette** [comment]
Thanks for filling this. I'm just trying to understand the use case better. Are you trying to build links within the app to various things like flows, artifacts etc? 

It might be better for us to handle internal links like that better otherwise hand built links would break if the app linking changes.

**Comment by scudette** [comment]
Some use case VQL that should work

Create links for all flows (org id is added automatically for the current org)
```sql
LET ColumnTypes <= dict(`Link`='url')

SELECT format(format="[Flow %s](/#/collected/%s/%s/overview)",
         args=[session_id,ClientId, session_id]) AS Link
FROM flows(client_id=ClientId)
```

**Comment by misje** [comment]
> Are you trying to build links within the app to various things like flows, artifacts etc?

Indeed! There are two main hurdles that I've encountered:

1. Having to specify the hostname when creating links for external use (notifications, e-mails etc.). My workaround is expecting the user to set the server hostname in server metadata, but I believe velociraptor knows this information and could provide it(?).
2. I want to be able to easily create links to other orgs as well, like in the Notebooks.Admin.Flows notebook artifact

**Comment by scudette** [comment]
Do you want the links to be created inside the browser or on the VQL side?

I mean in the above example the browser will render a proper link that works in the GUI because the column type is set to URL but the raw text (and what will appear in say json or csv exports) is still a relative url without an org id (because the org id is added in the GUI)

**Comment by scudette** [comment]
Did you try that with the latest ci build?

**Comment by scudette** [comment]
I found I had to do a hard reload to get the new JS in with the latest build.

**Comment by predictiple** [comment]
Tried that too. No luck. Plus in the dev tools caching is disabled.

I don't need it to work so if it works correctly in your testing I'm happy. Maybe @misje will also test.

**Comment by predictiple** [comment]
Ah yes, with `app/index.html` added it now works. Thanks!

**Comment by scudette** [comment]
added a link_to() function to VQL in #3714  to create links directly. I think this satisfies the underlying requirements for this feature. Please reopen if there are use cases not covered by this
