### ISSUE TITLE
Terminal settings (at least theme) are reset when changing orgs.

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3681]
My terminal theme is reset whenever I change org. in the latest release.

**Comment by scudette** [comment]
What is the output of `velociraptor version` ?

The editor setting is tied to the theme so it will be reset when the theme is changed. I guess I wonder why the theme is being changed when you switch orgs.

**Comment by misje** [comment]
Happens also in the last build (that I downloaded earlier today): 180a2cd

Reproduce by changing your editor theme to anything but the default out of the box, move to a different org., and back. I want my desired theme in all orgs., but it always resets to the default when I change between the orgs.

**Comment by misje** [comment]
Actually, the theme doesn't change.

**Comment by predictiple** [comment]
Yes we chatted about this a while back on Discord: https://discord.com/channels/624244632552734750/624244632552734752/1262805659515097159

The ACE theme resets to the theme's default when you switch orgs, but it only happens when using the User Settings modal. If you change orgs by editing org_id parameter in the URL then the ACE theme doesn't get lost.

As an aside there also seems to be something wrong with these ACE themes, which now don't apply any styling:

- One Dark
- GitHub Dark
- CloudEditor Dark
- CloudEditor (the light one)

**Comment by scudette** [comment]
This happens because editor themes are always reset when the theme changes. The user label dialog updates all fields when it closes, even those which were not changed. So it always updates the theme even when the org is changed. 

We should only update the fields that the user actually changed in the dialog box. This way if they user did not touch the theme the ace config is not changed.

**Comment by predictiple** [comment]
Fixed in #3688
Missing themes fixed too.
