### ISSUE TITLE
Underscores Added to Beginning and End of Files Downloaded From Velociraptor in Firefox 127+

### ISSUE THREAD

**Issue by rob-wilco** [Velocidex/velociraptor#3694]
### Issue Description:

When downloading files via the Velociraptor GUI using Mozilla Firefox, the downloaded files have underscores (_) appended to the beginning and end of the filenames. This requires manual renaming to make the files usable.
This issue is consistently reproducible in Firefox 127 and later versions.
The issue does not occur in Chromium-based browsers, such as Edge or Google Chrome.

### Steps to Reproduce:

Use Firefox 127 or a newer version.
Open the Velociraptor GUI.
Prepare and download a collection.

Sample Response Headers:

>HTTP/2 200 
content-disposition: attachment; filename*=utf-8''""; filename=""
content-type: binary/octet-stream
vary: Cookie
www-authenticate: Basic realm="Restricted"
x-csrf-token: tLdulzOM0kzThH066DWuI2STl9kNfOB8mV1/9jR6xyDqkZ3vUhLQcmpjnLLXQ2q4dvfkQ0P/MsvmYxPjnlY8SQ==
content-length: 100
date: Sun, 18 Aug 2024 02:36:46 GMT
X-Firefox-Spdy: h2

Additional Context:

A thread discussing this issue has been opened with Mozilla in July. You can view the discussion here:
[Mozilla Support Thread](https://support.mozilla.org/en-US/questions/1451495?utm_campaign=questions-reply&utm_source=notification&utm_medium=email#answer-1660342)

**Comment by scudette** [comment]
Thanks for filing this issue - we dont test much with FireFox so this is great feedback. 

Following the reference https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition shows that the `filename*` field must be encoded according to rfc5987 which shows an example:

https://datatracker.ietf.org/doc/html/rfc5987#section-3.2.2

```
   foo: bar; title*=UTF-8''%c2%a3%20and%20%e2%82%ac%20rates
```

So it does not include the quotes before and after. While the `filename` parameter should have the quotes:

```
Content-Disposition: attachment; filename="filename.jpg"
```

Yet from the very same MDN reference we have the following example:

```
Content-Disposition: inline
Content-Disposition: attachment
Content-Disposition: attachment; filename="filename.jpg"
Content-Disposition: attachment; filename*="filename.jpg"
```

Which shows quotes around the `filename*` parameter. 

So it seems that firefox started to be very literal in following the RFC and considers the quotes as part of the filename now which is why they are replaced with _ . However chrome is still flexible in allowing optional quotes around the `filename*` parameter. 

I just tried removing the quotes from `filename*` on FireFox on Windows and this does solve the issue. Probably the MDN documentation should be updated though as well.

**Comment by rob-wilco** [comment]
Compiled today at Thursday, August 22, 2024 4:48 PM UTC time, files downloading normally in Firefox now from the Velociraptor GUI. Thank you!

**Comment by scudette** [comment]
Thanks!
