### ISSUE TITLE
specifying "timezone" in VQL function "timestamp"

### ISSUE THREAD

**Issue by Herbert-Karl** [Velocidex/velociraptor#3715]
While playing around with the VQL function [timestamp](https://docs.velociraptor.app/vql_reference/basic/timestamp/), I noticed that I was unable to affect the output using the parameter "timezone".

compare the results from 
+ `SELECT timestamp(string="Thu Aug 29 2024 21:03") FROM scope()` 
+ `SELECT timestamp(string="Thu Aug 29 2024 21:03",timezone="CEST") FROM scope()` 
+ `SELECT timestamp(string="Thu Aug 29 2024 21:03",timezone="+0200") FROM scope()`
+ _each executed interactivey through the Velo server feature to run VQL queries directly on the client_
+ each run returns the same value: `2024-08-29T21:03:00Z`

technical details:
using Velociraptor agent version 0.7.1, running on freebsd14.1-release-p3, amd64

Im unsure if Im using the parameter wrongly and would like some feedback on this.

My specific usecase is that Im parsing some other data where I get a string representing a timestamp in localtime (e. g. "Thu Aug 29 2024 21:03"). I want to parse that string into a timestamp while at the same time using the right timezone (here currently "CEST" for me), so that the timestamp is not shifted.

**Comment by scudette** [comment]
Thanks for filing this issue - indeed the Timezone parameter is deprecated and doesn't do anything. 

In Velociraptor all times are stored in a Golang time.Time object - which stores both the time **and** the relevant timezone. Therefore internally times are never ambiguous and specifying a timezone is meaningless and does nothing.

The only time a timezone **hint** is needed is when we parse timestamps from a different timezone and it is ambiguous. You can provide this hint using the vql PARSE_TZ variable which is a **hint** for all timestamp parsing operations.

For example consider the following example
```sql
LET PARSE_TZ <= "local"

SELECT timestamp(string="Thu Aug 29 2024 21:03") ,
       timestamp(string="Thu Aug 29 2024 21:03 CEST") FROM scope()
```

![image](https://github.com/user-attachments/assets/03689e4e-f749-4db6-ae93-9ebb185be6b3)


The time `Thu Aug 29 2024 21:03` is ambiguous since it has no timezone, So in this case the PARSE_TZ variable says - if the timezone looks ambiguous then assume it is in local time. 

The second timestamp `Thu Aug 29 2024 21:03 CEST` is not ambiguous and will always be parsed correctly so PARSE_TZ has no effect. 

You can also specify any specific timezone for PARSE_TZ - for example "Europe/Berlin",  although most of the time it will be "local" which uses the local machine timezone (unless you are parsing say an external log file with ambiguous timestamps and you know the timezone).

Of course timestamps can be presented in the GUI in any timezone you want by changing the timezone in the user preferences screen.

When data is serialized to JSON times are always encoded in UTC so if you look at the JSON files on disk all times will be in UTC.

**Comment by predictiple** [comment]
Is there an easy way to check what timezone the client thinks it's in? It doesn't appear to be collected by the info plugin.

**Comment by scudette** [comment]
It normally should not matter what is the local timezone right?

If you really had to you can do this:

![image](https://github.com/user-attachments/assets/913264ba-e711-48dc-bab0-4a834476cb7f)

**Comment by predictiple** [comment]
Normally yes. If the endpoint is has a misconfigured timezone and it wrote the timestamps that we later need to parse using the "local" hint, then the misconfiguration should be a self-correcting. It will be a problem is someone fixes the endpoint's timezone after the data is written.

Should be a very rare situation though since modern OSes tend to set their TZ via geolocation.

**Comment by Herbert-Karl** [comment]
> Thanks for filing this issue - indeed the Timezone parameter is deprecated and doesn't do anything.
> 
> In Velociraptor all times are stored in a Golang time.Time object - which stores both the time **and** the relevant timezone. Therefore internally times are never ambiguous and specifying a timezone is meaningless and does nothing.
> 
> The only time a timezone **hint** is needed is when we parse timestamps from a different timezone and it is ambiguous. You can provide this hint using the vql PARSE_TZ variable which is a **hint** for all timestamp parsing operations.
> 
> For example consider the following example
> 
> ```sql
> LET PARSE_TZ <= "local"
> 
> SELECT timestamp(string="Thu Aug 29 2024 21:03") ,
>        timestamp(string="Thu Aug 29 2024 21:03 CEST") FROM scope()
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/3856546/362960857-03689e4e-f749-4db6-ae93-9ebb185be6b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMjAyNjMsIm5iZiI6MTcyNTAxOTk2MywicGF0aCI6Ii8zODU2NTQ2LzM2Mjk2MDg1Ny0wMzY4OWU0ZS1mNzQ5LTRkYjYtYWU5My05ZWJiMTg1YmU2YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMTIxMjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q1ZGZmYTg4MDQ1NDNjZmZlNDcxMzIzMWM5Y2NkYmVkYzNiMzk0ZTRlNjM2N2VhMzNkMzZlYjZkZGQ4ZmRmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hnRQ_J23cNAgWaooxT4mOyRtRmiY8Yi4nIkxWR8efao)
> 
> The time `Thu Aug 29 2024 21:03` is ambiguous since it has no timezone, So in this case the PARSE_TZ variable says - if the timezone looks ambiguous then assume it is in local time.
> 
> The second timestamp `Thu Aug 29 2024 21:03 CEST` is not ambiguous and will always be parsed correctly so PARSE_TZ has no effect.
> 
> You can also specify any specific timezone for PARSE_TZ - for example "Europe/Berlin", although most of the time it will be "local" which uses the local machine timezone (unless you are parsing say an external log file with ambiguous timestamps and you know the timezone).
> 
> Of course timestamps can be presented in the GUI in any timezone you want by changing the timezone in the user preferences screen.
> 
> When data is serialized to JSON times are always encoded in UTC so if you look at the JSON files on disk all times will be in UTC.

Thanks for the explanation. I tried with `PARSE_TZ` and it works for my use case. :)
Maybe the documentation of the function could mention that local time timestamps can be converted properly by setting the variable `PARSE_TZ`

**Comment by scudette** [comment]
Thanks for raising this issue - docs were updated here https://docs.velociraptor.app/vql_reference/basic/timestamp/
