### ISSUE TITLE
Why is TLS v1.3 enforced in frontend HTTP server?

### ISSUE THREAD

**Issue by CaledoniaProject** [Velocidex/velociraptor#3732]
Hi there, I'm unable to access the frontend server from an older system. It looks like TLS v1.3 is enforced, how can I resolved this issue without modifying the autoCert source code?

To reproduce this, use openssl to test protocol negotiation

```
openssl s_client -tls1_2 -connect IP:PORT
```

And it would result in openssl error, aka

```
40E72243407F0000:error:0A00042E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../ssl/record/rec_layer_s3.c:1584:SSL alert number 70
```

Any suggestions?

**Comment by scudette** [comment]
If you need to use TLS 1.2 you can enable this in your config file

https://docs.velociraptor.app/docs/deployment/references/#Client.Crypto.allow_weak_tls_server

**Comment by scudette** [comment]
This is rarely an issue since the client and server are both compiled with the same TLS library so they can both use TLS 1.3. It only happens when people try to use external scripts (e.g. with the API) or maybe there is a reverse proxy. I think .net is well known for using the insecure TLS 1.2 still.
