### ISSUE TITLE
Feature Request: Implement Execution Detection in Artifact Windows.Registry.AppCompatCache for Windows 10/11

### ISSUE THREAD

**Issue by rob-wilco** [Velocidex/velociraptor#3772]
Eric Zimmerman's **AppCompatCacheParser** identifies whether a third-party application has been executed by checking if the final four bytes of an AppCompatCache entry match `01 00 00 00`. If these bytes are present, it indicates a "Yes" for execution on Windows 10/11 systems.

Could this functionality be added to Velociraptor's Windows.Registry.AppCompatCache artifact?

Mike Peterson of Nullsec.us appears to confirm in the 13Cubed video that this pattern exists from the RTM build of Windows 10 and onwards.

13Cubed Video (timestamped): https://youtu.be/DsqKIVcfA90?t=658
Eric Zimmerman's Code: https://github.com/EricZimmerman/AppCompatCacheParser/blob/master/AppCompatCache/Windows10.cs
Mike Peterson's Blogpost: https://nullsec.us/windows-10-11-appcompatcache-deep-dive/

**Comment by mgreen27-r7** [comment]
TIL - thank you for sharing @rob-wilco

**Comment by mgreen27** [comment]
I just took a look at this and we did have this in the definition:
` ["Execution", "x=>x.PathSize + 14 + 8 + 4 + x.DataSize - 4", "uint32"]`
(Its been a while since I looked at it)

I messed around exposed the field and we can keep it exposed but non Win10+ machines will have a null value here. 
![image](https://github.com/user-attachments/assets/b53948b7-aeeb-4084-9b09-624424a04646)

**Comment by mgreen27-r7** [comment]
Added here: https://github.com/Velocidex/velociraptor/pull/3774

**Comment by rob-wilco** [comment]
Tested on Windows 8.1 VM - N/A is gracefully returned for ExecutionFlag.
Tested on Windows 10 and Windows 11 VMs - ExecutionFlag returning expected data.

Absolutely brilliant, thank you SO much!
