### ISSUE TITLE
The values of StartTime and EndTime in an event artfact notebook are wrong

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3842]
As timelines have got better timezone support, it appears that the timestamps produced in the values StartTime and EndTime in the default notebook are not correctly converted to UTC.

![2024-10-19_15-04](https://github.com/user-attachments/assets/f6d848fd-1096-4801-8382-4d9fb9db7b0e)

![2024-10-19_15-05](https://github.com/user-attachments/assets/aa15ce4e-261b-47ed-86d0-2740d388f7de)

Here the time matches the start time of the view above, except it doesn't contain the +2 hour offset, making it two hours into the future.

The end time I don't understand at all, but it is certainly wrong.

**Comment by scudette** [comment]
The end time is set to the current time. The intention is to create the notebook from the time cursor into the future (maybe instead of the current time we need to make it null or 22nd century or something)

**Comment by scudette** [comment]
Should be fixed in #3843 

This is still not satisfactory because it happens only when the notebook is created the first time - after the creation if the user changes the timeline widget the notebook does not see it at all requiring the user to manually change the times.

In future releases we need to think of better interactivity here
