### ISSUE TITLE
Notebook can't be deleted after it's template has been deleted

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#3921]
version: 0.73.3
commit: 6357f70ab
build_time: "2024-11-26T17:27:39+02:00"
compiler: go1.23.2
system: linux
architecture: amd64

![Screenshot from 2024-11-27 00-22-17](https://github.com/user-attachments/assets/b00dc30c-c20c-452e-830a-35233e3bf63b)

**Comment by scudette** [comment]
There are actually two issues here:
1. The delete notebook does not actually delete the notebook - it makes it hidden. Therefore it is actually an update operation (to set the hidden attribute on).
2. The notebook is tied to the artifact because (especially recently) the parameters that need to be shown in the GUI are taken from the artifact - this means we need to consult the artifact for any modification (because we need to rebuild the VQL code that converts the parameters to typed VQL variables).

So when the notebook artifact is gone, we really cant edit the notebook any more. 

There are a couple of solutions:
1. We could keep a copy of the artifact inside the notebook somewhere to make the notebook self contained. This means the notebook is created once from an artifact but then we always use the local copy of the artifact and never need to consult the artifact repository again - but the flip side is that it is impossible to edit the artifact to e.g. add new parameters.

2. We can degrade a notebook that has a missing artifact with one that uses the default artifact, but this will break parameters. This makes sense because the notebook template was deleted.

I am leaning towards option 1 - taking a local copy of the artifact in the notebook itself.

**Comment by predictiple** [comment]
Yes, 1 sounds like the best option. When I've been testing the new notebook features I didn't think that changes to the artifact would affect the existing notebooks which were based on that artifact. My intuition was to create a new notebook (and delete the old one) after each time I made changes to the artifact. Option 1 is conceptually consistent with how flows work where changing the artifact or deleting it after the flow has run doesn't matter.

**Comment by scudette** [comment]
Fixed by #3929
