### ISSUE TITLE
Feature Request: List artifacts in Hunt launch screen

### ISSUE THREAD

**Issue by knsankar** [Velocidex/velociraptor#404]
Hi,
It will be easy to navigate, if the artifacts are listed and sorted in the Hunt, Collect launch screen instead of search.

**Comment by scudette** [comment]
When you say list and sort the artifacts - they are already sorted anyway and there could be hundreds of artifacts - search is really the best interface here.

If you just want to see all the artifacts then type this into the search box `...` - since the search term is a regex three dots will match all artifacts.

**Comment by scudette** [comment]
You can use ... to list all artifacts in search box.
