### ISSUE TITLE
Feature request: Advanced notebook selection

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#405]
I have been using the notebook feature for hunts pretty effectively recently and really love the add > select hunt cell option which saves a lot of time.

I can also run similar workflow and review a flow for an individual machine as part  of live response but this process of selecting the Flow is manual then copy paste into the VQL.

I think a fairly easy to implement feature would be a similar capability to the select hunt cell but for host and Flow. This would significantly aid live response and bypass the 100 row limitation of the GUI.

I thought there may be two ways to do this:
1. in the Client Collected view have a notebook in the client context.
![image](https://user-images.githubusercontent.com/13081800/83703708-c2b35e80-a5ff-11ea-847d-8f84ebcd2294.png)

2. Enable a select flow cell in the normal notebook and have a search to select client prior.
![image](https://user-images.githubusercontent.com/13081800/83703748-dbbc0f80-a5ff-11ea-9fb3-e9ffbec9d7c8.png)

**Comment by scudette** [comment]
Hah you are the second person to mention this. I was actually going to remove the ad cell from hunt option from the GUI altogether since you can copy the vql from any table to the notebook. I just have the notebook open on another tab and then copy paste the vql from there.

There are actually some issues around adding hunts with multiple artifacts and sources with that GUI option and it doesn't work as expected.

**Comment by scudette** [comment]
now available in 0.4.5
