### ISSUE TITLE
Velcoiraptor need GLIBC_2.1.4 in Red Hat Enterprise Linux Sever release 6.5 (Santiyago)

### ISSUE THREAD

**Issue by Georgeskywang** [Velocidex/velociraptor#424]
Hi team,
so far, we need deploy the velociraptor-v0.4.2-linux-amd64  as a client in this kind of linux as title description. 
this is a application server. And administrator don't agree with upgrade their C lib in linux.
But V-client really need this kind of library.
So do we have any other version can run in this linux without GLIBC
![GLIBC_2 1 4-NOT FOUND](https://user-images.githubusercontent.com/7101007/84351238-88445580-abed-11ea-815b-c2f0069cd1a0.png)
_2.1.4

**Comment by scudette** [comment]
We build the release on ubuntu 18.04 which is already quite old but I think centos 6 is even older. In the past people have has a lot of success with running the CI binaries on the old centos because these binaries are built on windows actually.

You can try to get the latest head build:
https://github.com/Velocidex/velociraptor#getting-the-latest-version

**Comment by scudette** [comment]
I build 0.4.5 on Centos 6 so it should work. Please git it a try.

**Comment by Georgeskywang** [comment]
Hi Scudette,

ELF works and connected with server side normally.

Really thanks you help.

**Comment by Georgeskywang** [comment]
By the way , our engineers give our feedbacks that v-clients process always disappear after running some hours later in Linux side.
Do we have any solution about keeping this process alive?

**Comment by scudette** [comment]
It should not disappear - do you have any information as to why? Maybe a crash dump? clients normally do not have logging enabled but you can configure it by adding it to the config file:

```
Logging:
   output_directory: /var/tmp/logs
```

**Comment by mrezqi** [comment]
Hi @scudette, would this 0.4.5 client still works with velociraptor server that is running version 0.4.2?

The reason I am asking is because we already have velociraptor 0.4.2 running as server, and want to try avoiding replacing it with the newer version just because of some old RHEL machines. I guess this is more of a general question about backward compatibility.

**Comment by scudette** [comment]
Generally in practice it is much easier to upgrade the server than the clients (just replace a binary and restart the service). We do not really support new clients on old servers but we do support old clients on new servers to a few releases to varying degree of working.

Of course new artifacts that use new client features will not work but the basic things should be fine.

**Comment by scudette** [comment]
That said you can give it a try - odds are it should work because the comms protocol has not changed for a while. You can always get a CI build for any release from the last 6 months (I think appveyor keeps builds for 6 months). The linux binaries from appveyor are built on windows and so support all linux systems that I encountered.
