### ISSUE TITLE
GetHuntResults doesn't respect Rows parameter

### ISSUE THREAD

**Issue by CR-OmerYampel** [Velocidex/velociraptor#426]
https://github.com/Velocidex/velociraptor/blob/8135a75f4b931c53b11463c96eff7963ea2228b9/api/api.go#L329

The limit here is hardcoded, i believe it should be using the count field of this proto https://github.com/Velocidex/velociraptor/blob/363b7848e2cde198f8c5c1efe237658e08b7b57c/api/proto/hunts.proto#L158

**Comment by scudette** [comment]
This is actually only used by the GUI to render the hunt results  table and this is limited to 100 rows for performance reasons.

We probably do not want to increase it more than 100 because this particular call builds a result in memory to return to the RPC call. We need to limit it anyway - maybe to 500 instead of 100 (i think the other tables are limited to that). 

If you need all the results simply create a VQL query in the notebook.

**Comment by scudette** [comment]
Probably WAI
