### ISSUE TITLE
npm install deprecated issues

### ISSUE THREAD

**Issue by tombuttler12** [Velocidex/velociraptor#459]
I am following the instructions for build from source.

When I get to  npm install I come across a whole number of issues. Mostly being npm WARN deprecated. 

Everything is updated to the most recent version and I meet all the prerequisites - or at least I thought this was the case. 

Do you know what I might be doing wrong?

**Comment by scudette** [comment]
There a few npm warnings but they seem not important - you can see the build log in the GitHub Actions tab above:
![image](https://user-images.githubusercontent.com/3856546/85809949-da17de80-b79c-11ea-889d-647bf2563877.png)

Which node and npm version are you building with? Node and npm tend to be very fiddly to get right so I would recommend to download the latest node binary release from their web site, unpack it and add the bin directory to your path - do not use the ubuntu or centos distribution because they tend to be older.

If the build process works i wouldn't worry too much about the warnings - node tends to warn a lot but it does not seem to matter too much.

**Comment by scudette** [comment]
I would put this down to an npm issue - try to use the latest node release - it seems to be quieter.
