### ISSUE TITLE
Feature request: CA hard coded name switch to a configuration variable

### ISSUE THREAD

**Issue by Idriel** [Velocidex/velociraptor#49]
Please put CA FRONTEND_NAME and GRPC_GW_CLIENT_NAME to a configuration variable so that you can specify in the config file the pinned common name Velociraptor should accept.

**Comment by scudette** [comment]
This is now possible. Please test to make sure it works for your use case.
Simply set Client.pinned_server_name and API.pinned_gw_name

**Comment by Idriel** [comment]
Hi, 
I put Client.pinned_server_name and API.pinned_gw_name. 
I also put on endpoint new velociraptor.conf with Client.pinned_server_name, there is also use_self_signed: true. 
Now I can see Client as online, but Client does not send monitoring events. 

When I run: .\Velociraptor.exe --config .\Velociraptor.config.yaml client -v
`
[INFO] 2019-10-10T08:07:42Z Starting Crypto for client C.217d559a0cdc9fdb
[INFO] 2019-10-10T08:07:42Z Expecting self signed certificate for server.
[INFO] 2019-10-10T08:07:42Z Ring Buffer: Creation {"filename":"C:\\Users\\Sec\\AppData\\Local\\Temp/Velociraptor_Buffer.bin","max_size":1073741874}
[INFO] 2019-10-10T08:07:42Z Starting event query service.
[INFO] 2019-10-10T08:07:42Z Starting $ac38741cc482308bcf1ec00795fff2e5035f3fc40f47a809ea0c4b17040ae438510fdcd554200198c40d3fd4dcb5ffcfcb146dd3ff0aa67ca41c6bd59167cf2c
[INFO] 2019-10-10T08:07:42Z Starting HTTPCommunicator: HTTP Connector to [https://server-name.domain.local:8000/]
.
.
.
[INFO] 2019-10-10T08:07:42Z vql: scope.go:315: Registering watcher for C:/Windows/System32/Winevt/Logs/Security.evtx
.
.
.
[INFO] 2019-10-10T08:07:43Z File Ring Buffer: Commit / Truncate {"header":{"ReadPointer":50,"WritePointer":50,"MaxSize":1073741874,"AvailableBytes":0},"leased_pointer":50}
[INFO] 2019-10-10T08:08:54Z File Ring Buffer: Enqueue {"header":{"ReadPointer":50,"WritePointer":330,"MaxSize":1073741874,"AvailableBytes":272},"leased_length":50}
[INFO] 2019-10-10T08:08:54Z File Ring Buffer: Enqueue {"header":{"ReadPointer":50,"WritePointer":2697,"MaxSize":1073741874,"AvailableBytes":2631},"leased_length":50}
[INFO] 2019-10-10T08:08:54Z Sender: Connected to https://server-name.domain.local:8000/control
[INFO] 2019-10-10T08:08:54Z Sender: sent 1747 bytes, response with status: 200 OK
[INFO] 2019-10-10T08:08:54Z File Ring Buffer: Commit / Truncate {"header":{"ReadPointer":50,"WritePointer":50,"MaxSize":1073741874,"AvailableBytes":0},"leased_pointer":50}
`

Do you have any hint what can I do to get more info why it does not work?

**Comment by scudette** [comment]
Does it work with regular artifact collections?

**Comment by Idriel** [comment]
If I return to old config. Same version 0.3.5 everything works.

**Comment by scudette** [comment]
From the log messages it looks like the client is connected and is sending messages properly so it is not rejecting the certs at the TLS layer. Does the server show any messages?  you can run it with the -v flag on the console.

What could be happening here is that maybe the cert is not correct still maybe due to the keys not what we need. You can see the type of cert we generate is :

https://github.com/Velocidex/velociraptor/blob/master/crypto/ca.go#L131

You can check your cert with openssl:

```
openssl x509 -in foo.pem -text
```

**Comment by scudette** [comment]
Does it use RSA? This is what a cert looks like:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = Velociraptor CA
        Validity
            Not Before: Apr 24 14:05:30 2019 GMT
            Not After : Apr 23 14:05:30 2020 GMT
        Subject: O = Velociraptor, CN = VelociraptorServer
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
```
I think you need to have rsaEncryption  and sha256WithRSAEncryption 

Are you able to issue new collections for the client? Can you eg browse the vfs? Is there any message in the client log when you send it such a command?

**Comment by Idriel** [comment]
Certificate is rsa

    Data:
        Version: 3 (0x2)
        Serial Number:
            2f:18:95:8c:14:73:24:65:e2:9a:37:14:f1:ce:6b:3a:34:f9:01:a6
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: L=XX, CN=XXXXXXX Issuing CA
        Validity
            Not Before: Aug 16 14:11:57 2019 GMT
            Not After : Aug 15 14:12:26 2020 GMT
        Subject: O=XXXXXX, OU=XX, CN=server-name.domain.local
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
Signature Algorithm: sha256WithRSAEncryption

Will try VFS browsing. Sending update in few minutes. Just to reconfigure to new conf.

**Comment by Idriel** [comment]
File Browsing is working. 
Collect file from Client is working.

**Comment by scudette** [comment]
If file browsing is working then we have connectivity to the client. Therefore the comms and crypto are fine. I would investigate other reasons for why monitoring events are not working.

In the server logs we are looking for message like 
```
[DEBUG] 2019-10-10T11:04:46Z Received a post of length 163572 from 192.168.0.31:52073 (C.08ab587a3f39d2d7) 
```

The client should be sending those periodically and they should be received without errors.

I can see above from the client side that it is sending data so i expect to see the corresponding message on the server side.

Next I would check the journal file on the server filestore - in `<file store>/journals/Generic.Client.Stats/<date>` these files need to be growing as new events are received.

**Comment by Idriel** [comment]
In log I have my test client. 

{"level":"debug","msg":"Received a post of length 995 from XX.XXX.XX.XXX:56236 (C.217d559a0cdxxxxx)","time":"2019-10-10T11:14:40Z"}
{"level":"debug","msg":"Received a post of length 2627 from XX.XXX.XX.XXX:56252 (C.217d559a0cdxxxxx)","time":"2019-10-10T11:16:19Z"}

Journal files are not growing. 
I enable now Generic.Client.Stats -> and new file is not created.

**Comment by scudette** [comment]
I think I can replicate the issue - its a UI bug:
![image](https://user-images.githubusercontent.com/3856546/66613546-346e1080-ec09-11e9-942e-eb94a599028e.png)

It happens because the GUI only populates artifacts by searching for them. So first search for them and then click it should show it (it is still a bug though):
![image](https://user-images.githubusercontent.com/3856546/66613615-6aab9000-ec09-11e9-833c-c70d23003496.png)

Try to remove one of the event and then add them to force the client to resync the event table. 

I cant think of how this could be related to the certificates at all though - connectivity is good and everything else works well right?

**Comment by Idriel** [comment]
Hi,

Yes. Connectivity is good. I can browse VFS, I can connect to client shell.
I can search for Artifacts:
    and then Add it to Selected Artifacts.
    Save Client monitoring Artifacts. but again I have error: Error
Artifact not known.

same version, old config. Everything works fine. Just it's not our PKI.

Br,
Juraj

**Comment by Idriel** [comment]
When Clicking on Artifact:

Request URL:https://server-name.local:8889/api/v1/GetReport
Request method:POST
Remote address:xxx.xxx.xxx.xxx:8889
Status code: 500 - Internal Server Error
Version:HTTP/2.0
Referrer Policy:no-referrer-when-downgrade

Look like there is some error. I just can't figure out what is it. : )

**Comment by scudette** [comment]
Can you please check that the gateway certificate common name matches the config API.pinned_gw_name?

**Comment by Idriel** [comment]
openssl s_client -connect server-name.domain.local:8000

CONNECTED(00000003)
depth=0 O = domain, OU = test, CN = server-name.domain.local

Certificate chain
 0 s:/O=domain/OU=test/CN=server-name.domain.local
   i:/L=test/CN=domain test Issuing CA

pinned_gw_name: server-name.domain.local

**Comment by scudette** [comment]
This could be the problem - the gw name needs to be different from the server name - it is a different cert. It should also match the pinned_gw_cert. By default the common names are 

```
  pinned_gw_name: GRPC_GW
  pinned_server_name: VelociraptorServer
```

You can use `openssl -in file.pem -text` to check the common name in each cert.

Just to explain what it is - the GW certificate is used by the gRPC gateway proxy to connect to the API endpoint (which is secured using the server certificate). So it is actually a form of a client certificate. This is what the architecture looks like:

GUI JS app -> HTTP Server -> REST API -> GW -> gRPC

The http server listens for HTTP requests passes them to the rest api handlers which then use the gw certificate to act like a gRPC client to connect to the gRPC API. This is exactly the same as an API client connecting to Velociraptor (e.g. via a python script). But the GW user is special because they do not need to be authenticated to act on behalf of the user that made the original HTTP call. We trust that the gateway does proper authentication and if the gateway says they are acting on behalf of a user we just trust it. For this very important reason we absolutely **have** to have the common name of the gateway hard coded in the server config. We do not trust any other API caller in this way.

**Comment by Idriel** [comment]
Tnx. maybe that is the problem. I put the same cert for GUI and Frontend.

**Comment by scudette** [comment]
Yes this was the bug. I just pushed a change that relaxed this requirement - you may now use the same cert for both gw and frontend. You can check it on the ci builds.
