### ISSUE TITLE
Feature Request: Offline collector password

### ISSUE THREAD

**Issue by flukes86** [Velocidex/velociraptor#518]
Would it be possible to add the password encryption feature into the Build Offline collector tool on the frontend?

It would be great to specify the final zip file output name manually if possible?

**Comment by flukes86** [comment]
Is it posssible to add the option of creating a vhd with the collected files? this would just aid forensic analysis in tools such as X-ways. 

Truely awesome project.

**Comment by scudette** [comment]
A VHD is a disk image format - I guess you actually want us to write NTFS inside the VHD and replicate the timestamps in that new NTFS partition to match those of the source material.

I heard this request before but I am not super convinced of the merits of it - the point is that the timestamps can never be fully duplicated (for example we can not create all 16 NTFS timestamps in the destination NTFS becuase the NTFS API only exposes STANDARD INFORMATION timestamps) and this will definitely lead to confusion as tools like X-ways expect to look at the original evidence and so will actually present different information than the original (e.g. for time stomping etc).

It sounds like the only reason you would want to do this is because you wanted to timeline it with X-ways - but this does not make a lot of sense since the json/csv files already give you a timeline from the original evidence. 

I am just interested in the merits of this approach - not ruling it out right but I can see some problems with it.

**Comment by flukes86** [comment]
No problem thanks for replying. It was just so that the virtual file system is recreated in the forensic suites and as you say aids timelining incidents. It is possible to do this by mounting the MFT as a disk image in X-Ways but its a bit janky.

**Comment by scudette** [comment]
Yeah I know kape does it like that but it never made a lot of sense to me: we are analyzing the ntfs to get the data in the first place then we have to create an ntfs  image and we have to fake the evidence like timestamps, into the file system just so another tool can parse that file system and analyze those very same artifacts as if they were the original evidence...

Maybe it is just a big workaround to import a timeline into other tools? Would it make sense to just import a timeline?

I assume x ways can analyze the actual files out of the zip file (ie parse prefetch etc) so it's not an issue if actually importing the files themselves?

**Comment by scudette** [comment]
This is now available in CI builds and will be out in the next release
