### ISSUE TITLE
`artifact_definitions` always errors due to undeclared tools

### ISSUE THREAD

**Issue by CR-OmerYampel** [Velocidex/velociraptor#654]
Running the following query:

```
SELECT * FROM artifact_definitions(deps=False) LIMIT 1 
```

will always error since the `artifact_definitions` function causes the tools defined in all VQL to be pulled down to the server, this errors out due to the following two VQLs having tools which are meant to be uploaded using the `velociraptor tool upload` command, but they dont yet exist. 
1. https://github.com/Velocidex/velociraptor/blob/4bcd98db3f1d5107ba8e0fbfe05c3c04e449887f/artifacts/definitions/Windows/Search/Yara.yaml#L11
2. https://github.com/Velocidex/velociraptor/blob/10ce7f1cc2485d3dbe976dbe6eb944250f0914d6/artifacts/definitions/Admin/Client/Upgrade.yaml#L13

Here is the query I ran:
![image](https://user-images.githubusercontent.com/57952597/94225301-967b6080-fec2-11ea-8c63-cf233e117c3e.png)

And here is the frontend stdout log showing the tools automatically being download:
![image](https://user-images.githubusercontent.com/57952597/94225378-c0cd1e00-fec2-11ea-8e2b-6b5b2b4f4306.png)

Is it possible to make it so that the `artifact_definitions` function doesn't cause VRaptor to pull down the declared tools? or maybe just have it spit out all the artifacts on the server when the `names` param is empty without actually validating them (since they are already on the server)

**Comment by CR-OmerYampel** [comment]
@scudette  if I add a new boolean parameter to `artifact_definitions`, for example `artifact_definitions(raw=True)` where it simply returns the yaml from the repository, would that be a fine solution to this?

**Comment by scudette** [comment]
The original use case for artifact_definitions() is actually in discovering the dependency chain of artifacts. So if we want the definition for X and X calls Y then we need to see both X and Y. It does this by compiling the artifacts (as it would normally do this for the client) and then we can pick the dependencies from the compiled version.

Unfortunately pretending to compile the artifact as if we are sending to the client ensures the artifact is fully functional and this breaks when tools are not available. This is working as intended because we want to raise the error immediately when the user clicks the collect artifact button - then users have the option to fix the tool definition (e.g. by uploading the tool).

https://github.com/Velocidex/velociraptor/blob/master/services/launcher/launcher.go#L75

I think we might be able to get away with calling Compile()

https://github.com/Velocidex/velociraptor/blob/41256404e3174172aa3da66f4c58c93e8fb8377a/services/launcher/compiler.go#L2

That function just notes all the dependent artifacts but does not try to create a fully formed VQL request. 

One option is to expose a new API GetDependencies() which basically hoist the entire functionality to the launcher.

**Comment by scudette** [comment]
Can you please test #664 ?
