### ISSUE TITLE
Additional GUI features - collection management

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#667]
One issue I have in a large engagement if files piling up and with extensive hunts/collections disk space issues.

We can currently delete hunts and flows but I would like a delete button that removes the items on the filesystem to improve the workflow of clean the host.

I think this workflow is expected by the user when hitting delete on a hunt of a flow.

**Comment by scudette** [comment]
Currently we archive hunts and flows through the GUI instead of delete them. This approach comes from grr where the main consideration was about preserving evidence and audit logs.

This is why I was initially reluctant to implement actual deletion of data or at least not make it super easy to do. But realistically this only makes sense when you have infinite storage :-)

I don't mind just deleting data outright instead of archiving it first. What do you think?

Alternatively we could implement a server artifact that actually deletes archived flows or hunts so it will be a two step process, archive the flow in the gui and then run a server artifact to remove it.

**Comment by mgreen27** [comment]
I would be happy for the delete and have the responsibility of archive to the user. 
This is how I think most users would expect operation imho.

Matt

**Comment by scudette** [comment]
The new GUI have hunt/flow deletion
