### ISSUE TITLE
Show internal IP in Overview

### ISSUE THREAD

**Issue by cyb3rfox** [Velocidex/velociraptor#668]
It would be cool to see the internal/private IP/IPs of a host together with the NAT IP in the Host Information > Overview Screen. That helps when correlating with firewall logs. Right now it needs a drill-down.

**Comment by scudette** [comment]
There is not one internal IP - they are usually multiple interfaces and it is not clear which one we should show. It should be possible to add that to the Generic.Host.Info() artifact so can be visible in the Host Information -> DrillDown page.

We should probably add more things like that to the drill down page but maybe not show them as tables since it takes a lot of real estate for many pieces of information.

**Comment by scudette** [comment]
This type of correlation is easy to do with a VQL cell in the notebook so probably not worth adding a GUI feature just for it.
