### ISSUE TITLE
Embedding config on Windows / writeback.yaml not created

### ISSUE THREAD

**Issue by dboekhout** [Velocidex/velociraptor#7]
This is more of a question. Is it possible to do all of the steps mentioned in the quick start in a Windows environment? I kind of assumed that the release binaries have the same capabilities which seems to be the case up until actually starting the client or repacking the original exe to a exe with an embedded config.

So below are the steps I'm taking as described in the quick start, except everything is done on Windows (tried them on Linux, that worked). Generating the configs, adding a user, starting the front end works perfectly fine. When eventually I'd like to start a client instance, it says velociraptor.writeback.yaml could not be found, which is correct because it wasn't created. 

```powershell
PS C:\Users\user\Desktop> .\velociraptor-v0.2.7-windows-4.0-amd64.exe config generate > server.yaml
PS C:\Users\user\Desktop> .\velociraptor-v0.2.7-windows-4.0-amd64.exe --config .\server.yaml user add test test
PS C:\Users\user\Desktop> Start-Process .\velociraptor-v0.2.7-windows-4.0-amd64.exe -ArgumentList "--config .\server.yaml frontend"
PS C:\Users\user\Desktop> .\velociraptor-v0.2.7-windows-4.0-amd64.exe --config .\server.yaml config client > client.yaml
PS C:\Users\user\Desktop> .\velociraptor-v0.2.7-windows-4.0-amd64.exe --config .\client.yaml client
Genering new private key....
velociraptor-v0.2.7-windows-4.0-amd64.exe: error: Invalid config: open C:\Program Files\Velociraptor\velociraptor.writeback.yaml: The system cannot find the path specified.
```
Also, when I repack the original exe into an exe with an embedded config it actually passes with no errors but it has not actually embedded the config as confirmed by the error "agent.exe: error: Unable to load config file: No embedded config - try to pack one with the pack command or provide the --config flag." when invoking config show or using service install. The command that I used for repacking is:

```powershell
PS C:\Users\user\Desktop> .\velociraptor-v0.2.7-windows-4.0-amd64.exe config repack --exe .\velociraptor-v0.2.7-windows-4.0-amd64.exe client.yaml agent.exe
```

So question now is, is this behaviour expected because the binaries actually are different in their capabilities, is repacking/building not supported on windows or am I still doing something wrong?

**Comment by scudette** [comment]
The error " C:\Program Files\Velociraptor\velociraptor.writeback.yaml: The system cannot find the path specified." is because the client is trying to write the writeback file (which contains the keys it was just generating) but the directory does not exist. Normally the program files\velociraptor directory is created as part of the install process (which is why we specify in the config to put the write back there).

We dont want to create random directories in program files if users do not want to install Velociraptor permanently so we just bail out here. You can change the location of the write back in the config file or just create the directory yourself.

Repacking the executable works in windows as well. You can verify that your repacked binary has an embedded config using `velociraptor.exe config show` which will show it. You do not actually need to specify --exe when repacking on windows (by default the binary will use its own exe so you only need this flag when running the linux version to repack on windows). So this is enough `velociraptor config repack client.config.yaml agent.exe`

Just as a note repacking is useful only in some situations and generally I prefer to not use it - the reason being that repacking the binary will invalidate its digital signature (0.2.8 release is fully signed). So you either need to resign it or use the original downloaded exe with an external config file. The 0.2.8 installer will create the right config in the installation directory and launch the service with this args so the binary that ends up being installed is signed and valid.

**Comment by dboekhout** [comment]
Thank you for elaborating on this. I started by changing the default install path/writeback location in the config to an already existing location which fixed the first issue where the writeback file was not being written. I can now start the client using `velociraptor.exe --config client.yaml client`.

Still, I've not been able to get repacking working on Windows (with or without specifying --exe). I've tried both the 0.2.6 and 0.2.7 release all with the same result, no errors on repacking but `config show` gives me "No embedded config - try to pack one with the pack command or provide the --config flag.". In the same way I've not been able to use `service install` because that gives me the same error. 

Rest of the day I've been using the non-service way of running the client but I've also faced some issues with running a hunt. I'm not sure if this is related to running this on Windows but my setup is a 2016 server running the front end with two clients, one being a 2016 server while the other one runs windows 10 pro.

 I created and ran a hunt to list all the users on the clients. However about 30 minutes in the "scheduled clients" column stays at 0. I've watched your walkthrough video which shows that after starting the hunt, clients get scheduled either instantly or shortly thereafter. I noticed in the "manage launched flows" view some flows were done but one that wouldn't terminate is "F.Monitoring". Manually stopping / deleting the flows wasn't working either. The same goes for the hunt itself, using the 0.2.7 server the red button didn't actually stop the hunt so I had to redeploy a few times.

Similar behaviour occured when using the 0.2.6 release. I was able to pause the hunt with this release and start other ones so that saved me time but there was still this "F.Monitoring" job that seemed to block other flows from starting/completing. At the same time, clients were still not being scheduled. Later I noticed when running the client in debug mode it sometimes reported an error: "Unknown flow monitoring". I understand if you want me to create another issue for this as it's probably unrelated to this issue. Just tell me so and I'll put this in another issue.

**Comment by scudette** [comment]
This should just work as you describe so I am very interested in finding out why it doesn't for you. What would be really helpful for further debugging is:

- Use the latest 0.2.8 release
- start the client and frontend with the -v flag which will show logging to stderr
- you dont have to use repacking - you can just provide the pack to the config maybe try to install the service like that? You can also add the -v flag to that command to see more output.


When you client is connected (you get a green icon when you search for it) can you browse the VFS and click refresh directory on the files directory for example? 

The monitoring flow is an automated flow the system creates which collects the monitoring artifacts (i.e. process executions, dns lookups etc). It never terminates and automatically gets created. I think it only appeared in 0.2.7 so if you switch to 0.2.6 it probably does not know about it (this might explain the error you see there). You cant really stop the monitoring flow since it is a system flow.

Velociraptor can run multiple flows on the client at the same time so one flow cant actually block another flow any way.

**Comment by dboekhout** [comment]
Just noticed in the other issue you released 0.2.8. I will go ahead and test with that tomorrow and put on the v flags as well. 

To answer your question, yes I'm able to browse the vfs and recursively refresh directories for the clients.

Regarding the monitoring flow, that actually makes sense. Thanks for clarification on that. I'll start fresh with the 0.2.8 release and get back to you.

**Comment by scudette** [comment]
We need to hide the monitoring flow from the flows table - it is just confusing and you cant really see anything about it in the GUI - cant stop it and it doesnt really have a start or end time. Its just there now because technically it is a flow but this is an internal implementation detail.

**Comment by dboekhout** [comment]
The 0.2.8 release seems to have fixed the actual hunting issue. Clients get scheduled and results are gathered. Repacking is still not working for me but the alternative way of starting the client works fine and does the job. I guess this wraps up most of the issues I was encountering. 

Just on a side note, I don't think this has to do with velociraptor but I'll report it anyway; When I was running the file finder flow with a glob expression of "C:\Windows\System32\**3\*" to download the files it would error out after a few minutes saying "the file specified could not be found/accessed". Specifically the error occured when accessing/downloading a file with a long file name, that I guess was already deeper in the folder structure. I've seen this before with Windows where you couldn't access files directly if they were further down in the tree and had a long file name as well. You think velociraptor is running into the same issue?

**Comment by scudette** [comment]
The glob expression should be `"C:\Windows\System32\**3"`  Having a recursive glob in the same path component as something else does not really make any sense (it will try to match all files starting with System32 to a depth of 3).

It would be interesting to see if a long filename is involved - you can run the glob locally with the fs command:
```
velociraptor fs ls "C:\\Windows\\System32\\**3"  --format json -v
```
It will be easier to see with the json format as results are printed immediately (the default table view has to collect all the results so it can format the table cells).

**Comment by dboekhout** [comment]
I tested it out, still not working though with the glob expression you suggested. It does however work with the fs command, but that's not actually downloading the file so that's not really comparable. The exact error that I was given is along the lines of: open \tmp\velociraptor\clients\<client_id>\Windows\System32\cat root\<long_file_name> the system cannot find the path specified. As far as I've seen out of the three times that I tested this, the error occured downloading the same file.

**Comment by scudette** [comment]
Oh maybe the issue is it trying to download it from the VFS itself. It must
have managed to get it from the client to the server but maybe something is
going wrong writing it in the file store. Can you see if you can navigate
to that file from the VFS viewer and fetch or list it manually?

TBH we don't really test having the file store on Windows because the
filesystem performance is not great. But it should work. It may be
something like Windows unable to represent a character or something. Or
indeed can't have a long path name?

**Comment by dboekhout** [comment]
Sorry for getting back so late to you. I haven't been able to see if I could retrieve it from the VFS manually. I do however think this is a typical Windows issue where we are surpassing the 260 character limit of the full file path. I'll have to check some other time if the issue occurs when not using a file store on Windows.

After some more testing unrelated to the above I do have another question I hope you can assist with.
Is the file finder limited to collecting files which are currently not in use/locked by the system? Like say for example Amcache.hve could not be retrieved because a process is using it. I noticed that GRR had the option to use tsk which allowed raw retrieval from disk. Is there something I'm missing to get the same result? In your recent commits you seem to have added an artifact for the amcache that uses raw ntfs access, does this mean that the raw parsing is limited to predefined artifacts?

Also, does Velociraptor currently support getting a copy of the $MFT? I tried several globbing combinations in the file finder but couldn't get it to work. Using fs ls with the local binary did give me a stat on $MFT.

**Comment by scudette** [comment]
The file finder and other VQL plugins use a filesystem accessor for gaining access to various files. Here is more info about this https://docs.velociraptor.velocidex.com/blog/html/2018/09/30/velorciraptor_s_filesystem_s_accessors.html

The accessor is basically a driver which knows how to handle a particular file. The default usually is the file accessor so if you do not specify one that is what is used. That accessor uses the regular OS APIs which as you point out can not open locked files (e.g. reg hives or page file).

If you use the "ntfs" accessor then you can read files in an equivalent way to GRR's TSK. Velociraptor has its own NTFS implementation so it does not use TSK but it is conceptually the same. Furthermore you can do the same things regardless of the accessor, like glob search, yara scanning etc - regardless if using raw NTFS, registry etc (yes you can glob search a registry hive). 

We now also have a raw_reg accessor to parse reg hives as files (i.e. not using the API). As you pointed out in the case of the amcache we need to read the file from NTFS and then raw parse the hive to extract the required keys. This blog post (https://docs.velociraptor.velocidex.com/blog/html/2018/09/29/detecting_powershell_persistence_with_velociraptor_and_yara.html)  also explains why this is important for any artifacts that use HKEY_USERS. Since the user's hive will not be mounted into the HKEY_USERS part of the registry unless the user is actually logged on at the time, and conversely if they are logged on the file is locked and not readable. Hence we need to use NTFS raw access and raw reg parsing to analyze the user's hives.

**Comment by scudette** [comment]
Regard your $MFT question this blog post https://docs.velociraptor.velocidex.com/blog/html/2019/02/10/velociraptor_performance.html shows how we can upload the $MFT file using an artifact. Globbing should work the same if you specify the ntfs accessor.

I think there is an issue with the long path support on windows. https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file suggests we can just prepend \\?\ to the path name to support longer paths up to 32kb. I wonder if this works by changing the file store path in the config file to \\?\c:\tmp\velociraptor instead?

**Comment by dboekhout** [comment]
Thanks for the information, that helps a lot in understanding the inner workings. One more before I get to work with this. Is it possible to specify the accessor in the GUI or is it the custom to define your artifact and pass it in via the command line? Because I'm not sure how I would specify the glob with the ntfs accessor in case of the MFT using the GUI when setting up a hunt.

**Comment by scudette** [comment]
Velociraptor uses VQL to drive all its actions. The VQL is specified in the artifact. So an artifact is a yaml file which encapsulates a query, possibly providing parameters if needed. An artifact is specifically designed to extract a very specific set of information from the client - for example look for amcache entries. The users of the artifact does not need to worry about how this is done - just select the artifact they want.

The artifact's VQL statement provides the accessor as a parameter to the vql plugin. For example, if you want to glob the registry you would do something like `select ... from glob(globs=myglob, accessor='reg')`

You can write new artifacts or modify existing ones in the GUI. You navigate to server files, artifact definitions, select an existing artifact (select the text view in the tabs to view it) then click the edit artifact in the toolbar. You then get to write your own VQL query in the artifact and therefore specify the accessor.

Alternatively when you navigate the client VFS in the GUI, the top level directory represents some of the accessors (not all of them) like file, ntfs, registry etc.

**Comment by dboekhout** [comment]
> Regard your $MFT question this blog post https://docs.velociraptor.velocidex.com/blog/html/2019/02/10/velociraptor_performance.html shows how we can upload the $MFT file using an artifact. Globbing should work the same if you specify the ntfs accessor.

This worked well, wrote my own query to pull the Amcache and the $MFT. I'm learning VQL as I go from samples or just trying stuff out. I suppose there is no reference documentation yet with the available parameters and possibilities within VQL?

> I think there is an issue with the long path support on windows. https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file suggests we can just prepend \\?\ to the path name to support longer paths up to 32kb. I wonder if this works by changing the file store path in the config file to \\?\c:\tmp\velociraptor instead?

I've tested this but got stuck on setting up the new config file with that prefix. I tried several combinations(\\?\C:\tmp, \\?\C:/tmp, //?/C:/, \\?\tmp\ etc.)  but the config wouldn't validate when setting up the user account for the frontend, saying the location was invalid/incorrect/couldn't be found. Also, what is the difference between location and filestore_directory? I keep those identical.  Using the prefix in the file explorer with a file that was deep in the Sys32 folder, where it would normally break on long paths, did seem to work. 

While on the subject of paths. I've been experimenting with using system variables like %systemroot%, %windir% and %SystemDrive% as you were using it in the amcache artifact. But for me these don't work in the artifacts neither do they work with the client side fs ls queries.

**Comment by scudette** [comment]
This training material has (too much?) information about VQL https://docs.velociraptor.velocidex.com/blog/html/2018/11/13/velociraptor_training_at_nzitf.html but it does not exhaustively list all the vql plugins. The best way to develop VQL is using the console:

```
velociraptor console
```

Which will autocomplete stuff (plugins artifacts etc). In there you can also type `help glob` for example to get some help about the glob plugin.  You can also list all vql functions and plugins using `velociraptor vql list`.

In the config file, the Datastore.location is used to store the database files (basically protobufs). They are typically very small and read/written frequently so you probably want to store it on a filesystem that is good at that (or SSD). The filestore_directory is used to store uploaded files and csv files etc which can be large so you might want a spinning disk which is cheaper on AWS.

I looked into this in more detail and it turns out that on windows most APIs accept both \ and / as path separators, except when using long file names! Since the code uses / sometimes when we append that to the \\?\ prefix it refuses to work with it. So I had to fix this in code - it is something we need to watch on windows but it only affects servers running on windows (which I dont really think is a great idea but maybe its ok?).  Most of the time we run on AWS on centos or ubuntu/debian except when we do workshops - then its easier to get everyone to just run one windows system.

If you want to expand % expansions in VQL you need to explicitly do it (there are many keys/values which have % in them so we can't automatically do it):
```
SELECT expand(path="%TEMP%") as Temp from scope()
```

**Comment by scudette** [comment]
A [link](https://docs.velociraptor.velocidex.com/vql_reference/functions/#expand) into the documentation site.

This issue should be solved now.

**Comment by spark1-eqr** [comment]
@scudette Is there a new URL for your last comment? I get a 404.
