### ISSUE TITLE
Running pslist plugin in 32bit velociraptor on 64bit Windows OS gives wrong results

### ISSUE THREAD

**Issue by aspir** [Velocidex/velociraptor#711]
When running pslist plugin in 32bit velociraptor on 64bit Windows machine, it gives you wrong results regarding "SHA1", "SHA256", "MD5" and "WorkingSetSize" of processes.
The reason behind this is the use of package: "github.com/shirou/gopsutil".
When compiling 32bit Velociraptor, it will compile 'process_windows_386.go' in gopsutil, which includes different sizes in structs.
For the same reason there might be more problems in other plugins, like "stat" 

My recommendation is to write big warning in the documentation to be careful using velociraptor that was compiled in different architecture than the machine it runs on.

**Comment by scudette** [comment]
Yeah this is a very good point - there are lots of places where we define 64 bit structs that wont work with 32 bit binary. Also there are many issues with running the 32 bit binary on 64 bit Windows due to WOW64 - it is definitely not a recommended configuration.

We should add words to that extent both to the startup messages and to the VQL client collector to say that this configuration is not supported or recommended.

**Comment by scudette** [comment]
![image](https://user-images.githubusercontent.com/3856546/98664040-97deea80-2395-11eb-87ff-a7dc43ec14ff.png)

**Comment by scudette** [comment]
Should be fixed in 0.5.2
