### ISSUE TITLE
'Max Execution Time in Seconds' cannot update in GUI

### ISSUE THREAD

**Issue by flukes86** [Velocidex/velociraptor#720]
The Max Execution Time in Seconds default of 600 wont update in the GUI. It cant be adjusted in the final VQL however but doesnt allow input into the  Specify resource limits page.

**Comment by scudette** [comment]
This should have been fixed in 0.5.1-1 have you tried that release?

**Comment by flukes86** [comment]
Thanks, yes I have. It doesnt seem to be playing ball.

**Comment by scudette** [comment]
Can you please provide more information? What happens when you type into the input box? are there any messages in the javascript console? Can you attach the output of velociraptor version? What is the server's platform and the browser?

![image](https://user-images.githubusercontent.com/3856546/98366762-40ccd300-2080-11eb-924d-6dd6b2b6e18f.png)

You can verify the timeout is set in the review screen
![image](https://user-images.githubusercontent.com/3856546/98366846-5d690b00-2080-11eb-9059-6b8939a609a5.png)

**Comment by flukes86** [comment]
When typeing in the input box nothing changes, the figure is stuck on 600. When i then go to the review panel its just captured the last digit that was input. Velociraptor is running on a cloud instance in azure. Tested on Chrome and Firefox. 

name: velociraptor
version: 0.5.1
commit: b8ca284
build_time: "2020-10-27T17:43:11+10:00"


Server - Linux 5.4.0-1031-azure x86_64

**Comment by scudette** [comment]
Just to double check - are you talking about the new collection or new hunt screen? The new hunt was broken in 0.5.1-1 but the new collection was working. Both are fixed at head (you can download a head build from the actions tab on Github).

**Comment by flukes86** [comment]
ah ok, it was the hunt screen. Thanks for your help.

**Comment by scudette** [comment]
Should be fixed in 0.5.2
