### ISSUE TITLE
Certificate error when enrolling clients

### ISSUE THREAD

**Issue by anast20sm** [Velocidex/velociraptor#831]
Hello there!
I'm installing the Velociraptor environment and got stucked on installation.. When i start the clients (wherever linux or windows), the error "certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Velociraptor CA")" appears. I tried to install the CA cert directly on the computer but there is no diference. Can you suggest me what can be my deployment error? (i'm following https://www.velocidex.com/docs/getting-started/ as it is)

**Comment by scudette** [comment]
You can check the steps in there post https://www.velocidex.com/blog/medium/2020-09-28-velociraptor-network-communications-30568624043a/ to help debug communications.

The main part is to ensure client and server config are generated by the wizard. This ensures that they work. Have you changed the generated configs at all?

The velociraptor ca is a self signed ca that underpins the entire deployment. You do not need to load it into your root ca store because it is only used by velociraptor client.

**Comment by anast20sm** [comment]
Neither the server nor the client files have been modified. 
Tried to view certificate details as on the post https://www.velocidex.com/blog/medium/2020-09-28-velociraptor-network-communications-30568624043a/ and received the attached response.
![CA_error](https://user-images.githubusercontent.com/33606434/102891973-7296cf00-445f-11eb-9f13-eb8ea4978e5e.png)
![VirtualBox_Ubuntu Server Velociraptor_22_12_2020_14_01_35](https://user-images.githubusercontent.com/33606434/102891976-732f6580-445f-11eb-952b-4149236ff214.png)
![VirtualBox_Ubuntu Server Velociraptor_22_12_2020_13_27_24](https://user-images.githubusercontent.com/33606434/102891977-732f6580-445f-11eb-94d0-61ba6bcfdd94.png)

**Comment by scudette** [comment]
This error indicates that the client is unable to verify the certificate with the internal CA. Please check that the Client.ca_certificate is the same in both client.config.yaml and server.config.yaml. In fact the entire Client part should be the same in both files since the client.config.yaml is an extract of the server.config.yaml.

**Comment by anast20sm** [comment]
Thank you.
I deployed the same machines I had on Virtualbox on VMware and it works there, so seems it was a VBox problem.
Thanks for your quick responses!
