### ISSUE TITLE
Deprecate old crypto (RSA/SHA-1)

### ISSUE THREAD

**Issue by therealmik** [Velocidex/velociraptor#832]
I was having a read of the docs/code and I saw that the client/server protocol is using RSA and sha1 to exchange messages.

This is slow and fragile, and while not necessarily broken in this context, it is cutting it really close.

A better alternative might be nacl (https://godoc.org/golang.org/x/crypto/nacl/box)

**Comment by scudette** [comment]
The crypto protocol is carried over from GRR. It is true that it uses rsa which is slower but due to session key caching it's actually not that bad in practice. It uses aes cbc mode for symmetric crypto and sha1 for hmac only (rsa verification uses sha256).

While GRR used this crypto as the only way to secure client communication (over http), velociraptor actually uses regular tls on top. So weaknesses in the crypto are not as critical, it is simply used as a way to authenticate clients.

In practice tls overheads are much more significant so we suggest users implement tls offloading for large scale. Removing tls overheads allows performance to be very good (with session caching not significantly expensive memory wise)

You can learn more about the crypto in this post

https://www.velocidex.com/blog/medium/2020-09-28-velociraptor-network-communications-30568624043a/

We have no plans to change the crypto at this stage. It would be interesting to see if there are actual vulnerabilities or issues in the current implementation before we think about a possible migration. One thing to keep in mind is that we try to not break backwards compatibility with client comms. We sell have people using 0.4.7 releases with 0.5.3 (officially we support 2-3 versions behind). So any migration needs to be done carefully.
