### ISSUE TITLE
Feature Requests: Standalone Agent Event Streamer

### ISSUE THREAD

**Issue by bhjella-awake** [Velocidex/velociraptor#864]
Would it be possible to stream the artifact collections to a HTTPS server?  This would help with data ingestion pipelines vs having to parse files.

**Comment by scudette** [comment]
What do you mean by streaming? Are you talking about the offline collector? The regular client streams to the server anyway but you are suggesting to stream from the client without being connected to the server, but sending to say to an s3 bucket?

Are you asking about event streaming like logs or just regular file upload (which is already possible)?

**Comment by bhjella-awake** [comment]
Sorry, let me clarify.  Yes the Offline collector.  Instead of writing the events to a file which then can be uploaded (like to S3 or SFTP that it currently has) can you just stream then to like an HTTPS server or maybe even syslog (tcp with tls encryption)?

For example this would be 1 event from a SMB Server Security event log:
{
   "timestamp":"2020-11-08T21:56:48.953094482Z",
   "event_id":551,
   "host_name":"demo.redacted.com",
   "user":"",
   "user_sid":"S-1-5-18",
   "session_id":79165575397425
   ,"process_id":4,
   "src_host_name":"\\\\192.168.1.1"
   "collector": "Custom.Windows.EventLogs.SMBServerSecurity"
}

And this would be a sample run key collect event:
{
	"timestamp":"2020-03-24T16:08:25.6247052Z",
	"modified_time":"2020-03-24T16:08:25.6247052Z",
	"reg_key":"VMware User Process",
	"reg_path":"\\HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\\VMware User Process",
	"command_line":"\"C:\\Program Files\\VMware\\VMware Tools\\vmtoolsd.exe\" -n vmusr",
	"image_path":null,
	"Hash":null
	"collector": "Custom.Windows.Registry.RunKeys"
}

Would like to have each entry just streamed through a single HTTPS session (or multiple, but figured that would be a lot of unnecessary overhead)

**Comment by scudette** [comment]
The use case for the offline collector is as a one shot collector - i.e. a program that runs on a one off basis, collects some data and then terminates. While there is nothing technically stopping you from running an event query in the offline collector this will probably not work as desired because event queries never terminate - so the event collector will never terminate and will just appear to hang in the console when a user runs it.

To properly collect events in real time one needs to be running as a service and watch the events as they happen. This is what the Velociraptor client does with the added bonus of being able to task it, change config etc. If you are going to install as a service, you might as well just run the full client anyway instead of the offline collector.

The other issue is that pushing data periodically to S3 does not really work because S3 is a file store - so it is designed to write a complete file. I know on GCS, appending to a file is not generally supported (not sure about S3 but likely it is the same). I guess we could write an event per file but that is not really efficient.

OTOH you can easy make REST API calls in real time so if you can find a service that will receive the event data in real time this is easy to work (see this for example https://www.velocidex.com/blog/medium/2020-12-26-slack-and-velociraptor-b63803ba4b16/ ) but you can write this into the artifact already right now.

**Comment by bhjella-awake** [comment]
Sorry if I was not clear enough.  I am looking for a one shot collection.  But rather than have it upload a file, I want it to stream the results to a listener.  So instead of writing results to a file and zipping it up, just push the results to a http endpoint..

**Comment by scudette** [comment]
Ah I see - if you want to stream to a http listener (presumably you have some kind of REST API) then you just write an artifact to upload the data using the regular http_client(). See for example, Server.Slack.Clients.Online how to stream events to slack (but probably you want more of a bulk api there). This is just an example of a simple REST based API - no idea what API you want to support though.

Also worth looking at are the Elastic upload artifacts which just use elastic bulk upload API

There are practical limits with that based around security and network connectivity - can you ensure good connectivity from the collected machine to your API server? Can you just allow anyone to upload to your API and if not how do you protect the token (which will be embedded in the collector).

**Comment by scudette** [comment]
If you have more specific information about the REST API and what you would like to upload we can sketch up sample VQL. But I think all the tools you need to make it work are already available so im closing this as there is nothing to do from our end.
