### ISSUE TITLE
Feature Request: Dead Disk Analysis Support

### ISSUE THREAD

**Issue by slo-sleuth** [Velocidex/velociraptor#888]
Please consider adding analysis support for disk images, possibly by having the user mount the file system for Velociraptor to process as an endpoint using the local client.

Use Case: many examinations for intrusions, malware, misuse, criminal activity occur on systems taken offline to prevent further damage or data loss.  It doesn't make sense to boot the devices to install a client in such cases because of data change/loss, even if the devices are sand boxed from the network.

This might also allow for incremental change analysis, starting with a dead disk image as a baseline, followed by running the image in a VM/Live environment.

**Comment by CyberKaizen** [comment]
I two think this would be nice to have if it isn't possible to do already (I say this as I have not explored all the great powers of Veloci). Something better than this would be nice: https://github.com/orlikoski/CDQR.

**Comment by predictiple** [comment]
If you mount your disk image / volumes correctly then VR handles them fine already. For NTFS volumes this means use the `"show_sys_files,streams_interface=windows"` [ntfs-3g mount options](https://medium.com/@bromiley/torvalds-tuesday-mount-up-9313a4018d2) so that you can access things like $MFT and AFS. Everything can then be accessed using the VR "file" accessor.

In terms of relevant VR artifacts (i.e. relevant to offline analysis) you can derive these from the bundled artifacts by applying the following rules of thumb:

1. Remove the precondition OS = Windows if your offline analysis isn't being done on a Windows system.
2. Adjust any path references in the artifact so that they match your mounted disk's filesystem.
3. If the artifact uses Windows API calls then either remove these or substitute with a non-API equivalent/approximation, for example Windows registry artifacts need to use the raw_reg accessor and reg paths will not start with HKEY_.
4. Run your artifacts locally using `velociraptor artifacts collect --definitions=/path/to/artifacts/ artifact_name` command line or using the local GUI (`velociraptor gui`) in which you can develop the artifacts as well as kick them off using the Notebooks section.

**Comment by scudette** [comment]
Done will be out in 0.6.4
