### ISSUE TITLE
Feature Request: For S3 Upload, support presigned URL as alternative to Key/Secret

### ISSUE THREAD

**Issue by liteman** [Velocidex/velociraptor#945]
The AWS Access Key and Secret are recoverable in plaintext from an offline collector. 

If the offline collector could be built with a AWS Presigned URL -- then the key/secret do not need to be exposed. 

For the S3 Upload add optional parameter presigned_url

reference: https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html

**Comment by liteman** [comment]
Added benefit - the Presigned URL grants access to a specific object (bucket).  The AWS Key / Secret provide access to ALL buckets available to that IAM user.

**Comment by scudette** [comment]
It is possible to configure acls on the iam user so they can only upload and only have access to the upload bucket. This is essentially to prevent leak of the credentials as you mentioned. 

Using presigned URLs in this context is problematic because the url also contains the object key (ie. the filename) so the collector can only be used to write the same object ever. The offline collector uses the hostname and timestamp as the filename currently so we can separate the objects in the buckets later.

This also means anyone can overwrite the same object with the collector if they obtained the URL (maybe it is possible to configure bucket permissions to avoid that).

**Comment by liteman** [comment]
> the url also contains the object key
Ah -- that makes sense. I was thinking that a URL could grant access to a bucket - but you are right, the filename must be known at URL generation time. 

Yes - I will look in to ACLs for the IAM user.
