### ISSUE TITLE
Timeline plugin not working on notebook

### ISSUE THREAD

**Issue by valentino-xander** [Velocidex/velociraptor#978]
The Timeline plugin is not rendering in markdown mode within a notebook cell using the latest version 0.5.7.

**Comment by scudette** [comment]
The timeline plugin was removed a while ago - there were no artifacts using it (other than some eye candy).

Do you have a solid use case for it? It seems to me that it is not useful for real analysis since it can not handle many events (e.g. MFT timeline is best done using a query and export to csv + notepad actually).

**Comment by scudette** [comment]
#369 explains that the version we were using is not supported. Additionally the js dependency would add a lot of code to the binary size which did not seem worth it

**Comment by valentino-xander** [comment]
Hi thanx for the feedback, yes when trying to build a trajectory on when it entered the parent process. Maybe show the attacker's lateral movements but rather in a graphic presentation. Its more on the quality of evidence side and not technical. But I do appreciate.

**Comment by scudette** [comment]
Closing since we dont have plans to add the timeline plugin in again. 

If you disagree, please let us know how it can help analysis visualization in a way that is better/easier than e.g timesketch or another dedicated timelining tool. For example, is there a timeline library that can visualize a dense set of timelines in a useful way?
