### ISSUE TITLE
Velociraptor Offline Collector - Files collected are not inheriting original system's timestamps when added to an archive.

### ISSUE THREAD

**Issue by CyberKaizen** [Velocidex/velociraptor#984]
When the offline collector adds artifacts to a .zip file, some of the artifacts do not carry the original system's "Date Modified" timestamps with it.

I've observed this issue occurring for AutomaticDestinations and CustomDestinations artifacts.

**Comment by scudette** [comment]
This is working as intended. Zip files are used as just storage for data. They are not meant to replicate the original filesystem. 

You can see all the timestamps in the result set json file.

**Comment by CyberKaizen** [comment]
@scudette Your definitely not wrong. 

This is more a quality of life improvement then anything else.

When running scripts to parse zip data into one super timeline the timestamps are taking on dates of when files are uncompressed.

Other open source collection projects, that use compression libraries, have the zip file inherit the "date modified" of the files. 

It just makes things easier than having to copy and paste from another source.

**Comment by scudette** [comment]
We probably can not solve this in general - Velociraptor uses the VQL upload() function to place the files in the zip file (or in the client/server mode actually upload those). The upload() function just copies data - there is no concept of timestamps because the data may be obtained from anywhere (for example a string, a reg value, a memory region etc). 

In order to pass a timestamp to the upload() function we need to extend it and then in the vql artifacts decide what that actually means. Some files will have a timestamp because they got copied from actual files, but many might now (and the json files will not for sure). Maybe this makes sense as a general feature?

Does this issue come up specifically with one artifact or generally? It might be easier to just create a quick python script that extracts the zip and sets the timestamps based on the json. The script can be tailored to a specific artifact (say KapeFiles.Targers?)

**Comment by CyberKaizen** [comment]
It primarily affects Lnk (shortcut) files. There are tools out there that when they parse this data, are reliant on the actual timestamp of the file on disk. Other projects like CyLR manage to zip the data and preserve those timestamps.

**Comment by CyberKaizen** [comment]
The problem could likely be solved all together if it were possible to collect data to a VHDX file formatted in NTFS instead of a .zip.
